local({
 source('R/patient_adaptive_prediction.R')
 d<-validate_data(demo_data(),540);d$group<-rep(c('Control','Treatment'),length.out=nrow(d))
 cfg<-list(purpose='patient_prediction',cut=540,control='Control',origin='2025-01-01',d1=sum(d$event),d_plan=200,d_max=280,p=.5,alpha=.025,hr_assumed=.75,cp_target=.9,rule='bounded',display_unit='months',n2=400,window2=1800,enrollment='batch',dropout_rates=c(0,0),reps=40,seed=101,model_mode='fit',uncertainty='plugin',fit_method='exponential')
 set.seed(123);old<-.Random.seed;r<-run_patient_prediction(d,cfg)
 check(identical(old,.Random.seed),'IA conditional prediction preserves caller RNG')
 check(all(r$trials$z1==r$ia$benefit_z) && all(r$trials$events1==109),'conditional trials freeze actual IA Z and event count')
 check(all(subset(r$trials,design=='adaptive')$selected_d2==r$decision$selected_d2),'conditional prediction never recalculates D2 from future')
 x<-r$trials;tested<-x$action=='tested'
 check(all(x$reject[tested]==(r$plan$w1*x$z1[tested]+r$plan$w2*x$z2[tested]>=r$plan$critical)),'conditional rejection uses original fixed combination weights')
 check(identical(r$trials,run_patient_prediction(d,cfg)$trials),'conditional patient simulation exact repeat')
 more<-cfg;more$reps<-60;s<-run_patient_prediction(d,more)
 check(identical(r$trials,s$trials[s$trials$SIMID<=40,]),'conditional patient trials stable when B increases')
 sample<-patient_prediction_sample(r,20);o<-subset(sample$observed,design=='adaptive')
 check(!length(intersect(o$USUBJID[o$cohort==1],o$USUBJID[o$cohort==2])),'conditional new IDs disjoint from frozen IA')
 check(all(o$entry_day[o$cohort==2]>=540) && all(o$DCO_DAY[o$cohort==1]==540),'conditional new entries after IA; old DCO remains frozen')
 oo<-subset(o,cohort==1);check(identical(oo$time_day,d$time) && identical(oo$status,d$status),'conditional simulation preserves each IA observed history')
 sw<-survival::survdiff(survival::Surv(time_day,event)~group,data=subset(o,cohort==2));check(near(sample$rows$z2[1]^2,sw$chisq,1e-9),'conditional stage 2 agrees with independent survival software')
 check(identical(as.list(sample$rows),as.list(r$trials[r$trials$SIMID==20,])),'selected conditional sample regenerates same stage statistics')
 units<-cfg;units$display_unit<-'days';check(identical(run_patient_prediction(d,units)$trials,r$trials),'conditional display units leave day engine unchanged')
 fixed<-cfg;fixed$d_max<-cfg$d_plan;f<-run_patient_prediction(d,fixed)
 check(identical(subset(f$trials,design=='adaptive')$reject,subset(f$trials,design=='original')$reject) && f$paired$mean_rejection_difference==0,'no increase exactly pairs both conditional decisions')
 miss<-cfg;miss$window2<-.001;m<-run_patient_prediction(d,miss)
 check(all(m$trials$stage2_hit==FALSE) && all(m$trials$reject==FALSE),'conditional target miss closes without extra final test')
 check(all(is.infinite(m$trials$target_day)) && all(m$trials$final_day==540.001),'target misses distinguish infinite target from finite termination')
 check(all(is.na(m$resources$hit_wait_median_day)) && all(is.infinite(m$resources$generated_wait_median_day)),'timing summaries do not condition silently on target hits')
 check(all(m$summary$rejection_lower==0 & m$summary$rejection_upper==0),'completed target misses retained as valid nonrejections')
 check(all(m$resources$generated_median_date=='窗口内未达') && all(m$resources$termination_median_date=='2026-06-25'),'date fields separate target hit and termination')
 cancelled<-run_patient_prediction(d,cfg,should_cancel=local({i<--1L;function(){i<<-i+1L;i>5L}}))
 check(cancelled$completed==5 && all(cancelled$summary$pending==35),'conditional cancellation preserves paired completed/pending rounds')
 check(all(abs(cancelled$summary$rejection_upper-cancelled$summary$rejection_lower-35/40)<1e-12),'conditional full-request bounds account for pending')
 empty<-run_patient_prediction(d,cfg,should_cancel=function()TRUE)
 check(empty$completed==0 && all(empty$summary$rejection_lower==0 & empty$summary$rejection_upper==1),'immediate conditional cancellation retains 0-to-1 bounds')
 check(all(empty$resources$all_wait_median_lower_day==0 & is.infinite(empty$resources$all_wait_median_upper_day)),'all-request median bounds include every unknown trajectory')
 tmp<-tempfile(fileext='.R');writeLines(patient_prediction_reproduction(cancelled),tmp);e<-new.env();sys.source(tmp,e);unlink(tmp)
 check(identical(e$r$trials,cancelled$trials) && identical(e$r$resources,cancelled$resources),'conditional downloaded partial data and hex config replay lossless')
 unlink(c('patient_prediction_trials.csv','patient_prediction_summary.csv','patient_prediction_resources.csv'))
 failed<-new.env();sys.source('R/patient_adaptive_prediction.R',failed);failed$patient_prediction_draw<-function(...)stop('deliberate draw failure')
 ff<-failed$run_patient_prediction(d,cfg)
 check(all(ff$summary$invalid==40) && all(ff$summary$rejection_upper==1 & ff$summary$rejection_lower==0),'conditional draw failures never disappear from denominator')
 check(all(ff$trials$z1==r$ia$benefit_z) && all(ff$trials$events1==109),'draw failures retain frozen IA and selected target')
 check(all(is.na(ff$resources$mean_new_n)),'generation failure does not fabricate zero resource counts')
 g<-cfg;g$uncertainty<-'gamma';g$prior_shape<-.5;g$prior_rate<-50;gg<-run_patient_prediction(d,g)
 check(all(gg$trials$decision_valid) && gg$completed==40,'Gamma group posterior runs through conditional new cohort')
 boot<-cfg;boot$uncertainty<-'bootstrap';bb<-run_patient_prediction(d,boot)
 check(all(bb$trials$z1==r$ia$benefit_z) && identical(bb$observed$time_day[bb$observed$cohort==1],r$observed$time_day[r$observed$cohort==1]),'Bootstrap refits only model and preserves original IA records')
 manual<-cfg;manual$model_mode<-'manual';manual$manual_models<-list(parameter_model('exponential',list(median=300)),parameter_model('weibull',list(median=450,shape=1.4)))
 check(run_patient_prediction(d,manual)$completed==40,'manual separate distributions support non-PH new cohort')
 piece<-manual;piece$enrollment<-'piecewise';piece$enroll_cuts<-c(100,300);piece$enroll_rates<-c(.4,1,0)
 pp<-run_patient_prediction(d,piece);check(all(pp$trials$n2_observed<=400) && all(pp$trials$final_day>540),'piecewise new enrollment with zero tail preserves time origin and cap')
 coll<-d;coll$id[1]<-'NEW::SIM00001-SUB00001';cc<-run_patient_prediction(coll,manual)
 check(!length(intersect(cc$data$id,cc$observed$USUBJID[cc$observed$cohort==2])),'conditional ID collision receives alternate new prefix')
 for(bad in list(list(model_mode='manual',uncertainty='gamma'),list(n2=100),list(window2=4000),list(reps=19),list(uncertainty='gamma',fit_method='weibull'),list(uncertainty='bayes_weibull',fit_method='exponential')))check(fails(patient_prediction_validate(d,modifyList(cfg,bad))),paste('conditional validation rejects',names(bad)[1],bad[[1]]))
 bad<-d;bad$group<-'Control';check(fails(run_patient_prediction(bad,cfg)),'conditional adaptive prediction requires two known groups')
 bayes<-cfg;bayes$fit_method<-'weibull';bayes$uncertainty<-'bayes_weibull';bayes$log_eta_mean<-log(450);bayes$log_eta_sd<-1;bayes$log_shape_mean<-0;bayes$log_shape_sd<-.75;bayes$mcmc_chains<-4;bayes$mcmc_warmup<-1000;bayes$mcmc_draws<-3000
 rr<-run_patient_prediction(d,bayes);diag<-patient_prediction_diagnostics(rr)
 check(nrow(diag)==4 && all(diag$passed) && all(diag$rhat<=1.01 & diag$ess_bulk>=400 & diag$ess_tail>=400),'conditional Weibull posterior passes all group diagnostics before prediction')
 check(identical(rr$trials,run_patient_prediction(d,bayes)$trials),'conditional MCMC preparation and per-trial posterior draws reproduce exactly')
 bad<-bayes;bad$mcmc_chains<-1;check(fails(run_patient_prediction(d,bad)),'conditional invalid MCMC setup cannot produce posterior forecasts')
 e15<-new.env();sys.source('app.R',e15)
 shiny::testServer(e15$register_patient_adaptive_server,{
   session$setInputs(ad_engine='patient',pa_purpose='patient_prediction',pa_source='demo',pa_control='Control',pa_unit='months',ad_d1=109,ad_plan=200,ad_max=280,ad_p=.5,ad_alpha=.025,ad_hr=.75,ad_cp=.9,ad_rule='bounded',pg_n2=400,pg_window2=60,pg_enrollment='batch',pg_reps=20,pg_seed=101,pg_model_mode='fit',pg_uncertainty='plugin',pg_fit_method='exponential',pa_n1=NA_real_,pa_window1=NA_real_,pa_true_hr=NA_real_,pa_reps=NA_real_)
   session$setInputs(ad_run=1);submitted<-job()$config
   for(i in 1:100){Sys.sleep(.05);session$elapse(500);if(is.null(job()))break}
   check(is.null(error()) && result()$completed==20,'conditional Shiny ignores hidden from-origin fields and completes in worker')
   check(identical(result()$trials,e15$run_patient_prediction(result()$data,submitted)$trials),'conditional worker and synchronous patient engine agree exactly')
   prior<-result();session$setInputs(pg_view_trial=2);check(!is.null(output$pg_observed) && identical(result(),prior),'conditional selected sample renders without changing result snapshot')
   session$setInputs(pg_model_mode='manual',pg_uncertainty='gamma',pg_fit_method=NA_character_);z<-config()
   check(z$config$uncertainty=='plugin' && is.null(z$config$fit_method),'manual conditional input ignores hidden fit uncertainty and family')
   session$setInputs(pg_n2=10,ad_run=2)
   check(!is.null(error()) && identical(result(),prior),'conditional invalid submission retains prior successful result')
 })
 check(length(unlist(e15$handbook_index()))==44,'handbook exposes real IA conditional reassessment chapter')
})
