const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=process.cwd(),out=process.env.CORE_CHECK_OUTPUT||path.resolve(root,'../../work/core-check-downloads');
fs.mkdirSync(out,{recursive:true});
const checks=[],jsErrors=[],consoleErrors=[],requests=[];
const check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);console.log('PASS '+label)};
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1450,height:1050},acceptDownloads:true});page.setDefaultTimeout(30000);
 page.on('pageerror',e=>jsErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
 page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:3839'))requests.push(r.url())});
 const choose=async(id,value)=>{await page.locator('#'+id).waitFor({state:'attached'});await page.evaluate(({id,value})=>document.getElementById(id).selectize.setValue(value),{id,value});await page.waitForTimeout(450)};
 const tab=async(name)=>{await page.getByRole('tab',{name,exact:true}).click();await page.waitForTimeout(250)};
 const fill=async(id,value)=>{await page.locator('#'+id).fill(String(value));await page.locator('#'+id).dispatchEvent('change');await page.waitForTimeout(200)};
 const download=async(id,name)=>{await page.locator('#'+id).waitFor({state:'visible'});const wait=page.waitForEvent('download');await page.locator('#'+id).click();const d=await wait;await d.saveAs(path.join(out,name));return fs.readFileSync(path.join(out,name),'utf8')};
 const noErrors=async()=>check((await page.locator('.shiny-output-error:visible:not(:empty)').allTextContents()).length===0,'visible outputs have no errors');
 try {
  await page.goto('http://127.0.0.1:3839');await page.waitForSelector('#task_count');await page.waitForTimeout(1600);
  check(await page.locator('.task-card').count()===3,'home contains exactly three core tasks');
  check(!(await page.getByRole('tab',{name:'任务参数',exact:true}).isVisible()),'home hides unrelated task forms');await page.screenshot({path:path.join(out,'home.png')});
  await page.locator('#task_count').click();await page.waitForSelector('#run',{state:'visible'});
  await tab('运行设置');check(!(await page.locator('#target').isVisible()),'count task needs no target');await fill('sims',50);
  await tab('事件模型');await choose('design_model','exponential');await fill('median',12);
  check(await page.locator('#parameter_conversion').innerText().then(t=>t.includes('0.057')),'exponential equivalent risk shown beside input');
  await choose('exp_input','rate');check(Math.abs(Number(await page.locator('#exp_rate').inputValue())-Math.log(2)/12)<1e-9,'median to risk rate toggle preserves distribution');await choose('exp_input','median');
  await tab('未来入组与退出');await fill('future_n',60);await fill('enroll_rate',15);
  await page.locator('#run').click();await page.waitForSelector('#event_plot svg.main-svg');await page.waitForSelector('#new_count_table table');
  check(!(await page.locator('#prob_plot').isVisible())&&!(await page.locator('#milestones').isVisible()),'count results hide date and probability outputs');await noErrors();
  await tab('导出');const countConfig=JSON.parse(await download('config_download','count-config.json'));
  const countCSV=await download('curves_download','count-curves.csv');const countReport=await download('report_download','count-report.md');
  check(!('target' in countConfig.config)&&!countCSV.split('\n')[0].includes('probability'),'count exports omit unused target/probability');
  check(countConfig.config.uncertainty==='plugin'&&countConfig.config.clock==='occurred'&&!countConfig.config.ensemble,'core config locks declared statistical scope');
  check(countReport.includes('未包含参数估计不确定性'),'report states plug-in interval limitation');
  await tab('任务参数');await tab('运行设置');await fill('seed',123);
  await tab('预测结果');await tab('导出');const frozen=JSON.parse(await download('config_download','count-frozen-config.json'));
  check(frozen.config.seed===countConfig.config.seed,'editing controls does not rewrite saved result');
  await tab('任务参数');await tab('队列与资料');await choose('time_unit','days');await tab('事件模型');
  check(Math.abs(Number(await page.locator('#median').inputValue())-365.25)<1e-6,'month to day median conversion');
  await tab('未来入组与退出');check(Math.abs(Number(await page.locator('#enroll_rate').inputValue())-15/30.4375)<1e-9,'month to day enrollment rate conversion');
  await tab('队列与资料');await choose('time_unit','weeks');await tab('事件模型');check(Math.abs(Number(await page.locator('#median').inputValue())-365.25/7)<1e-6,'day to week median conversion');
  await tab('队列与资料');await choose('time_unit','months');await tab('事件模型');await choose('design_model','weibull');
  const median=Number(await page.locator('#median').inputValue()),shape=Number(await page.locator('#shape').inputValue());await choose('weibull_input','eta');
  check(Math.abs(Number(await page.locator('#eta').inputValue())-median/Math.pow(Math.log(2),1/shape))<1e-7,'Weibull equivalent scale toggle');await choose('weibull_input','median');
  await tab('需求入口');await page.locator('#task_target').click();await tab('运行设置');await fill('target',10000);await page.locator('#run').click();await page.waitForSelector('#milestones table');
  check(await page.locator('#milestones').innerText().then(t=>t.includes('未达标比例')&&t.includes('超过预测窗口')),'unreachable target returns failed-to-reach proportion and open date');
  check(!(await page.locator('#event_plot').isVisible()),'target results only show task outputs');await tab('导出');await download('summary_download','target-milestones.csv');await download('config_download','target-config.json');
  await tab('任务参数');await tab('运行设置');await fill('target',0);await page.locator('#run').click();await tab('预测结果');await page.waitForFunction(()=>document.querySelector('#run_status')?.textContent.includes('正整数'));
  await tab('导出');const retained=JSON.parse(await download('config_download','target-retained.json'));check(retained.config.target===10000,'failed run retains last successful configuration');await noErrors();
  // Distinct group parameter inputs; summed counts must remain meaningful.
  await tab('需求入口');await page.locator('#task_count').click();await tab('队列与资料');await page.locator('#analysis_mode input[value="grouped"]').check();await tab('分组参数');await page.waitForSelector('#g1_design_model',{state:'attached'});
  await choose('g1_design_model','exponential');await fill('g1_future_n',20);await page.locator('#group_inputs a[data-value="组 2 · B"]').click();await choose('g2_design_model','weibull');await fill('g2_future_n',20);
  await page.locator('#run').click();await page.waitForSelector('#event_plot svg.main-svg');await tab('分组事件');await page.waitForSelector('#group_event_table table');
  check(await page.locator('#group_event_table').innerText().then(t=>t.includes('A')&&t.includes('B')),'known groups render separate event summaries');await download('group_summary_download','group-summary.csv');
  // Real CSV upload and date/censor mapping, using synthetic ADTTE only.
  await tab('任务参数');await tab('队列与资料');await page.locator('#analysis_mode input[value="pooled"]').check();await page.locator('#input_mode input[value="adtte"]').check();
  const dataPath=path.join(out,'synthetic-adtte.csv');let csv='USUBJID,PARAMCD,STARTDT,ADT,AVAL,CNSR,TRTP,ANL01FL\n';
  for(let i=0;i<60;i++){let day=i<36?10+i*2:100;let date=new Date(Date.UTC(2025,0,1+day)).toISOString().slice(0,10);csv+=`S${i},PFS,2025-01-01,${date},${day+1},${i<36?0:1},${i%2?'B':'A'},Y\n`;}fs.writeFileSync(dataPath,csv);
  await page.locator('#file').setInputFiles(dataPath);await page.waitForFunction(()=>document.querySelector('#paramcd')?.selectize?.getValue()==='PFS');await fill('cut',100/30.4375);
  await tab('事件模型');for(const box of await page.locator('#methods input').all())await box.uncheck();await page.locator('#methods input[value="exponential"]').check();await page.locator('#run').click();await page.waitForSelector('#count_end_table table');
  await tab('输入数据与分布');await page.waitForSelector('#data_table table');check(await page.locator('#data_status').innerText().then(t=>t.includes('数据模式')),'ADTTE upload reaches fitted prediction workflow');
  await tab('预测结果');await tab('导出');const fitted=JSON.parse(await download('config_download','fitted-config.json'));await download('curves_download','fitted-curves.csv');check(fitted.data_summary.n===60&&fitted.data_summary.events===36,'uploaded ADTTE correctly counts rows and events');
  await tab('任务参数');await tab('队列与资料');await page.locator('#analysis_mode input[value="grouped"]').check();
  await page.waitForFunction(()=>document.getElementById('group_column')?.selectize?.getValue()==='TRTP');
  await page.locator('#run').click();await tab('分组事件');await page.waitForSelector('#group_event_table table');
  await download('group_summary_download','fitted-group-summary.csv');await tab('导出');
  const grouped=JSON.parse(await download('config_download','fitted-group-config.json'));await download('curves_download','fitted-group-curves.csv');
  check(grouped.config.analysis_mode==='grouped'&&grouped.config.adtte_mapping.group_column==='TRTP'&&Object.keys(grouped.config.groups).length===2,'actual ADTTE known-group prediction freezes selected treatment column');
  await tab('需求入口');await page.locator('#task_design').click();await tab('研究设置');await fill('sim_n',80);await fill('sim_reps',2);await fill('sim_cuts','12,24');await page.locator('#sim_run').click();await page.waitForSelector('#sim_km svg.main-svg');await noErrors();
  const observed=await download('sim_observed_download','sim-observed.csv');const adtte=await download('sim_adtte_download','sim-adtte.csv');
  check(!observed.split('\n')[0].includes('event_time_day')&&adtte.split('\n')[0].includes('CNSR'),'observation and ADTTE exports exclude latent clocks');
  await tab('导出');await download('sim_truth_download','sim-truth.csv');await download('sim_summary_download','sim-summary.csv');await download('sim_config_download','sim-config.json');await download('sim_script_download','sim-reproduce.R');await download('sim_report_download','sim-report.md');
  check(fs.readFileSync(path.join(out,'sim-truth.csv'),'utf8').split('\n')[0].includes('event_time_day'),'truth clocks available only in separate export');
  await tab('工作手册');await page.waitForFunction(()=>document.querySelectorAll('.core-handbook .hb-equation').length>10);await page.waitForTimeout(1200);
  const formula=await page.evaluate(()=>({equations:document.querySelectorAll('.core-handbook .hb-equation').length,errors:document.querySelectorAll('[data-mml-node="merror"]').length,raw:document.querySelectorAll('.core-handbook script[type^="math/tex"]').length}));
  check(formula.errors===0&&formula.raw===0,'all core manual equations render without MathJax errors');check(await page.locator('.handbook-toc a').count()===8,'core manual has eight working chapter links');
  await page.locator('.handbook-toc a[href="#core-section-5"]').click();check(await page.locator('#core-section-5').count()===1,'manual chapter anchor exists');
  await download('handbook_download','core-handbook.md');await download('handbook_html_download','core-handbook.html');await page.screenshot({path:path.join(out,'handbook.png')});
  // Open the actual standalone download with network blocked.
  const offline=await browser.newPage();await offline.route(/^https?:/,r=>r.abort());await offline.goto('file://'+path.join(out,'core-handbook.html'));
  await offline.waitForFunction(()=>document.querySelectorAll('.hb-equation').length>10);await offline.waitForTimeout(500);
  check(await offline.locator('[data-mml-node="merror"]').count()===0&&await offline.locator('script[type^="math/tex"]').count()===0,'downloaded manual renders equations offline');await offline.close();
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(500);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'manual fits narrow viewport');await page.screenshot({path:path.join(out,'manual-mobile.png')});
  await tab('需求入口');await page.evaluate(()=>window.scrollTo(0,0));check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'home fits narrow viewport');await page.screenshot({path:path.join(out,'home-mobile.png')});
  await page.locator('#task_count').click();await tab('队列与资料');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'prediction form fits narrow viewport');
  await noErrors();check(jsErrors.length===0,'browser has no uncaught JavaScript errors');check(requests.length===0,'core app and manual request no external resources');
  fs.writeFileSync(path.join(root,'validation/core_browser_results.json'),JSON.stringify({status:'passed',checks,passed:checks.length,formula,jsErrors,consoleErrors,externalRequests:requests},null,2)+'\n');
 } catch(e){await page.screenshot({path:path.join(out,'failure.png')});console.error('VISIBLE ERRORS',await page.locator('.shiny-output-error:visible:not(:empty)').allTextContents());console.error('JS',jsErrors);throw e;}
 finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exit(1)});
