local({
 for(f in c('units','models','forecast','inputs','bayes','simulation','conditional_simulation','nph','sequential','study','conditional_prediction','ia_history'))source(paste0('R/',f,'.R'),local=TRUE)
 raw<-ia_history_template();h<-normalize_ia_history(raw,'OS','2025-01-01',2,dropout_codes=2)
 g<-function(lab)list(name=lab,model=parameter_model('exponential',list(median=200)),future_n=0,enroll_mode='constant',enroll_rate=0,enroll_cuts=numeric(),enroll_rates=numeric(),dropout_rate=0,multiplier=1,fit_method='exponential',cuts=numeric(),tail_rate=.002)
 cfg<-list(purpose='rejection',source='history',origin=h$origin,paramcd='OS',cut=h$cut,display_unit='months',prediction_history=h$snapshots,prediction_design='sequential',prediction_control='Control',prediction_sided='benefit',prediction_alpha=.025,prediction_timing=c(.25,.5,.75,1),prediction_spending='asOF',prediction_futility='none',prediction_futility_z=numeric(),prediction_miss='no_reject',cut_mode='target',target=80,max_day=h$cut+500,groups=list(g('Control'),g('Treatment')),model_mode='manual',uncertainty='plugin',reps=20L,seed=18L,q_values=1,fixed_times=1)
 check(length(h$snapshots)==2&&h$cut==40&&nrow(h$data)==120,'history normalization selects a complete two-look prefix with later enrollment')
 check(identical(vapply(h$snapshots,function(s)sum(s$data$event),integer(1)),c(20L,40L)),'selected snapshots retain cumulative observed event counts')
 shuffled<-raw[rev(seq_len(nrow(raw))),];check(identical(h,normalize_ia_history(shuffled,'OS','2025-01-01',2,dropout_codes=2)),'raw file row order cannot alter snapshot normalization or patient order')
 bad<-raw;late<-bad$IASEQ==3;bad$ADT[late]<-'invalid';bad$TRTP[late]<-'Future';bad$AVAL[late]<--999;bad$CNSR[late]<--1
 check(identical(h,normalize_ia_history(bad,'OS','2025-01-01',2,dropout_codes=2)),'later clinical contents are excluded before dates, groups and outcomes are read')
 week<-raw;week$AVAL<-week$AVAL/7;week$AVALU<-'WEEKS';check(identical(h,normalize_ia_history(week,'OS','2025-01-01',2,dropout_codes=2,aval_unit='weeks')),'historical file AVAL units are independent from display units')
 sas<-raw;for(id in c('STARTDT','ADT','DCO'))sas[[id]]<-as.numeric(as.Date(sas[[id]])-as.Date('1960-01-01'))
 check(identical(h,normalize_ia_history(sas,'OS','2025-01-01',2,dropout_codes=2,date_encoding='sas')),'SAS-encoded snapshot and patient dates normalize identically')
 other<-raw;other$PARAMCD<-'PFS';other$IASEQ<-NA_real_;other$ADT<-'invalid';combined<-rbind(raw,other)
 check(identical(h,normalize_ia_history(combined,'OS','2025-01-01',2,dropout_codes=2)),'other endpoints do not enter selected endpoint history validation')
 check(identical(ia_history_choices(raw,'OS'),1:3),'file selector exposes original analysis numbers without renumbering')
 tryraw<-function(x,k=2,...)normalize_ia_history(x,'OS','2025-01-01',k,dropout_codes=2,...)
 bad<-raw;bad$DCO<-NULL;check(fails(tryraw(bad)),'historical file requires an explicit snapshot DCO variable')
 bad<-raw;bad$IASEQ[1]<-1.5;check(fails(tryraw(bad)),'non-integer historical analysis sequence rejected')
 bad<-raw[raw$IASEQ!=1,];check(fails(tryraw(bad)),'missing earlier analysis cannot be silently skipped')
 bad<-rbind(raw,raw[1,]);check(fails(tryraw(bad)),'duplicate patient within a snapshot rejected')
 bad<-raw;bad$DCO[bad$IASEQ==2][1]<-'2025-02-11';check(fails(tryraw(bad)),'each analysis requires one unique DCO')
 ix<-function(id)which(raw$IASEQ==2&raw$USUBJID==id)
 bad<-raw;bad<-bad[-ix('H079'),];check(fails(tryraw(bad)),'previously observed patient cannot disappear from a later snapshot')
 bad<-raw;i<-ix('H079');bad$TRTP[i]<-'Treatment';check(fails(tryraw(bad)),'patient group cannot change between original snapshots')
 bad<-raw;i<-ix('H079');bad$STARTDT[i]<-'2025-01-02';bad$AVAL[i]<-bad$AVAL[i]-1;check(fails(tryraw(bad)),'patient entry date cannot be changed while keeping internally valid AVAL')
 bad<-raw;i<-ix('H005');bad$CNSR[i]<-1;bad$ADT[i]<-'2025-02-10';bad$AVAL[i]<-41;check(fails(tryraw(bad)),'previous endpoint event cannot be changed back to an active subject')
 bad<-raw;i<-ix('H005');bad$ADT[i]<-'2025-01-07';bad$AVAL[i]<-7;check(fails(tryraw(bad)),'previous event date cannot be revised under immutable-history mode')
 bad<-raw;i<-ix('H090');bad$CNSR[i]<-1;bad$ADT[i]<-'2025-02-10';bad$AVAL[i]<-41;check(fails(tryraw(bad)),'permanent dropout cannot re-enter follow-up')
 bad<-raw;i<-ix('H090');bad$ADT[i]<-'2025-01-14';bad$AVAL[i]<-14;check(fails(tryraw(bad)),'previous dropout date cannot be revised')
 bad<-raw;i<-ix('H101');bad$STARTDT[i]<-'2025-01-01';bad$AVAL[i]<-41;check(fails(tryraw(bad)),'new patient already entered before previous DCO reveals an incomplete historical snapshot')
 bad<-raw;i<-ix('H079');bad$ADT[i]<-'2025-02-09';bad$AVAL[i]<-40;check(fails(tryraw(bad)),'current active patients must be confirmed to the actual current DCO')
 bad<-raw;i<-ix('H079');bad$AVAL[i]<-999;check(fails(tryraw(bad)),'AVAL and dates cannot disagree even with a valid historical sequence')
 bad<-h$snapshots;bad[[2]]$cut<-20;check(fails(validate_ia_history(bad)),'snapshot DCO cannot precede its patient observations or previous DCO')
 bad<-h$snapshots;bad[[2]]$look<-2.5;check(fails(validate_ia_history(bad)),'normalized snapshot sequence also rejects fractional values')
 bad<-h$snapshots;bad[[2]]$data$event[1]<-0;check(fails(validate_ia_history(bad)),'normalized event indicators must agree with recorded status')
 for(status in c('event','dropout')) {bad<-h$snapshots;i<-match('H021',bad[[2]]$data$id);bad[[2]]$data$status[i]<-status;bad[[2]]$data$event[i]<-as.integer(status=='event');bad[[2]]$data$time[i]<-20;bad[[2]]$data$obs_day[i]<-20;check(fails(validate_ia_history(bad)),paste('later',status,'must follow the previously confirmed active age strictly'))}
 bad<-h$snapshots;bad[[1]]$data$event[1]<-1.25;check(fails(validate_ia_history(bad)),'fractional normalized event indicators cannot pass via integer coercion')
 path<-conditional_history_path(h$snapshots,cfg)
 check(all(path$action=='continue')&&identical(path$look,1:2),'two completed valid analyses precede future prediction')
 for(k in 1:2) {
  d<-h$snapshots[[k]]$data;s<-survival::survdiff(survival::Surv(time,event)~group,d,rho=0);w<--(s$obs[2]-s$exp[2])/sqrt(s$var[2,2])
  check(near(path$benefit_z[k],w,1e-7)&&near(path$score_variance[k],s$var[2,2],1e-7),'each historical signed log-rank and variance agree with independent survival software')
 }
 bad<-cfg;bad$prediction_timing<-c(.2,.5,.75,1);check(fails(conditional_history_path(h$snapshots,bad)),'each original event target must match its actual snapshot count')
 bad<-cfg;bad$prediction_plan<-conditional_prediction_plan(cfg);bad$prediction_plan$upper_z[3]<-0
 check(fails(conditional_history_path(h$snapshots,bad)),'stored future efficacy boundary cannot be substituted without matching original configuration')
 bad<-cfg;bad$prediction_futility<-'z';bad$prediction_futility_z<-c(.1,.1,.1)
 check(fails(conditional_history_path(h$snapshots,bad)),'history after an earlier futility stop cannot become an ongoing trial')
 r<-run_conditional_prediction(h$data,cfg)
 check(nrow(r$decisions)==20&&r$config$prediction_look==2&&length(r$config$prediction_history)==2,'history prediction retains every requested simulation and only selected original prefix')
 check(identical(r$history_path,path),'saved historical analysis result is the validated actual path')
 z<-r$looks[r$looks$look<=2,];check(all(z$phase=='observed_history')&&all(z$benefit_z==path$benefit_z[match(z$look,path$look)])&&all(z$DCO_DAY==path$DCO_DAY[match(z$look,path$look)]),'all future trajectories share exactly the original historical statistics and dates')
 check(all(r$looks$phase[r$looks$look>2]=='simulated_future')&&all(r$looks$DCO_DAY[r$looks$look>2]>40),'future analyses start strictly after current IA and are labeled as simulated')
 check(all(r$decisions$future_analysis_count<=2)&&all(r$decisions$analysis_count==r$decisions$future_analysis_count+2),'historical and future analysis counts use the selected current look rather than assume look one')
 for(status in c('event','dropout')) {
  known<-h$data[h$data$status==status,];o<-r$observed[r$observed$USUBJID %in% known$id,];j<-match(o$USUBJID,known$id)
  check(all(o$status==status)&&near(o$time_day,known$time[j]),paste('multi-look continuation preserves current known',status,'patients'))
 }
 active<-r$observed[r$observed$USUBJID %in% h$data$id[h$data$status=='active'],];j<-match(active$USUBJID,h$data$id)
 check(all(active$time_day>=h$data$time[j]),'current active patients cannot have future events before their confirmed age')
 check(identical(r$decisions,run_conditional_prediction(h$data,cfg)$decisions),'multi-look prediction reproduces exact decisions from data and seed')
 more<-cfg;more$reps<-30;rr<-run_conditional_prediction(h$data,more)
 check(identical(r$decisions,rr$decisions[rr$decisions$SIMID<=20,]),'increasing repetitions preserves the previous decision prefix')
 uc<-cfg;uc$display_unit<-'days';check(identical(r$decisions,run_conditional_prediction(h$data,uc)$decisions),'display-unit changes do not change normalized historical prediction')
 h1<-normalize_ia_history(raw,'OS','2025-01-01',1,dropout_codes=2);one<-cfg;one$cut<-h1$cut;one$max_day<-h1$cut+500;one$prediction_history<-h1$snapshots
 history1<-run_conditional_prediction(h1$data,one);one$prediction_history<-NULL;legacy<-run_conditional_prediction(h1$data,one)
 check(isTRUE(all.equal(history1$decisions,legacy$decisions,tolerance=1e-12,check.attributes=FALSE)),'first-look historical prediction matches the existing first-IA algorithm')
 check(isTRUE(all.equal(history1$looks[,setdiff(names(history1$looks),'phase')],legacy$looks,tolerance=1e-12,check.attributes=FALSE)),'first-look compatibility includes all actual stopping records')
 q<-cfg;q$q_values<-c(.75,1,1.25);qr<-run_conditional_prediction(h$data,q)
 check(nrow(qr$decisions)==60&&all(qr$looks$benefit_z[qr$looks$look==2]==path$benefit_z[2]),'q scenarios change the future while preserving the actual multi-look IA statistic')
 for(mode in c('plugin','gamma','bootstrap')) {
  fit<-cfg;fit$model_mode<-'fit';fit$uncertainty<-mode;fit$prior_shape<-.5;fit$prior_rate<-50;fit$reps<-5L;fr<-run_conditional_prediction(h$data,fit)
  check(identical(fr$history_path,path)&&identical(fr$baseline$observed,r$baseline$observed),paste(mode,'model handling only refits the selected snapshot and retains its original risk set'))
  if(mode=='gamma')for(j in 1:2){d<-h$data[h$data$group==cfg$groups[[j]]$name,];check(sum(fr$models[[j]]$events)==sum(d$event)&&near(sum(fr$models[[j]]$exposure),sum(d$time)),'posterior sufficient statistics count each latest patient once rather than stack repeated snapshots')}
 }
 stopped<-cfg;stopped$prediction_futility<-'z';stopped$prediction_futility_z<-c(-1,.1,-1);stopped$groups<-NULL;stopped$reps<-NA_real_;stopped$q_values<-NA_real_;stopped$seed<-NA_real_;stopped$max_day<-NA_real_;stopped$model_mode<-'invalid';stopped$uncertainty<-'invalid'
 sr<-run_conditional_prediction(h$data,stopped)
 check(nrow(sr$decisions)==1&&sr$decisions$stop_reason=='futility'&&sr$decisions$future_analysis_count==0&&!length(sr$models),'actual current stopping needs no hidden future models, window or repetitions')
 check(conditional_prediction_overview(sr)$rejection_conditional==0&&conditional_prediction_overview(sr)$wilson_lower==0&&conditional_prediction_overview(sr)$wilson_upper==0,'already decided non-rejection is deterministic rather than an estimated future probability')
 h3<-normalize_ia_history(raw,'OS','2025-01-01',3,dropout_codes=2);final<-cfg;final$prediction_history<-h3$snapshots;final$cut<-60;final$target<-60;final$prediction_timing<-c(1/3,2/3,1)
 ff<-run_conditional_prediction(h3$data,final)
 check(ff$decisions$stop_reason=='final_no_reject'&&ff$decisions$future_analysis_count==0&&nrow(ff$history_path)==3,'completed original final analysis is accepted without requiring a larger final event target')
 eff<-raw;eff$TRTP<-ifelse(as.integer(sub('H','',eff$USUBJID))<=20,'Control','Treatment');eh<-normalize_ia_history(eff,'OS','2025-01-01',1,dropout_codes=2);ec<-cfg;ec$cut<-20;ec$prediction_history<-eh$snapshots;er<-run_conditional_prediction(eh$data,ec)
 check(er$decisions$stop_reason=='efficacy_benefit'&&er$decisions$decision_reject&&er$decisions$future_analysis_count==0,'actual historical early efficacy yields decided rejection without future tests')
 bad<-ec;bad$prediction_history<-normalize_ia_history(eff,'OS','2025-01-01',2,dropout_codes=2)$snapshots;bad$cut<-40
 check(fails(run_conditional_prediction(bad$prediction_history[[2]]$data,bad)),'historical records after early efficacy cannot restart the trial')
 two<-cfg;two$prediction_sided<-'two';two$prediction_alpha<-.05;t1<-run_conditional_prediction(h$data,two);two$prediction_control<-'Treatment';t2<-run_conditional_prediction(h$data,two)
 check(near(t1$history_path$benefit_z,-t2$history_path$benefit_z)&&identical(t1$decisions$decision_reject,t2$decisions$decision_reject),'two-sided history control reversal preserves decisions and reverses historical Z')
 no<-cfg;no$max_day<-40.000001;un<-run_conditional_prediction(h$data,no)
 check(all(un$decisions$stop_reason=='window_unreached')&&all(un$decisions$future_analysis_count==0)&&all(!un$looks$performed[un$looks$look==3]),'window closure does not append an unplanned test after historical IA two')
 bad<-h$data;bad$group[1]<-'Treatment';check(fails(run_conditional_prediction(bad,cfg)),'current data cannot differ from the selected immutable historical snapshot')
 bad<-cfg;bad$cut<-41;check(fails(run_conditional_prediction(h$data,bad)),'current DCO must match the selected historical snapshot')
 tf<-tempfile();writeLines(conditional_prediction_script(r),tf);e<-new.env(parent=environment());sys.source(tf,e)
 check(identical(r$decisions,e$r$decisions)&&identical(r$looks,e$r$looks)&&identical(r$history_path,e$r$history_path),'lossless history script reproduces decisions, full paths and observed-prefix analysis')
 check(nrow(read.csv('prediction_history.csv'))==2,'history reproduction exports the selected observed analysis prefix')
 unlink(c(tf,'prediction_trials.csv','prediction_looks.csv','prediction_summary.csv','prediction_history.csv'))
 # Exercise actual source selection, hidden fields, snapshots and deterministic stopped paths.
 ea<-new.env(parent=globalenv());invisible(sys.source('app.R',ea));tmp<-tempfile(fileext='.csv');write.csv(raw,tmp,row.names=FALSE)
 shiny::testServer(ea$server,{
  session$setInputs(task='conditional',ci_purpose='history',ci_source='demo',ci_file=list(datapath=tmp,name='history.csv'),ci_endpoint='OS',ci_origin='2025-01-01',ci_history_look='2',ci_group_column='TRTP',ci_offset='1',ci_dropout_codes='2',ci_date_encoding='iso',ci_aval_unit='days',ci_flag='',ci_flag_value='Y',ci_pr_control='Control',ci_pr_design='fixed',ci_pr_sided='benefit',ci_pr_alpha=.025,ci_pr_timing='.25,.5,.75,1',ci_pr_spending='asOF',ci_pr_futility='none',ci_pr_futility_z='invalid',ci_cut=NA_real_,ci_fixed='invalid',ci_cut_mode='fixed',ci_cuts='invalid',ci_horizon=500/30.4375,ci_unit='months',ci_model_mode='manual',ci_process='fixed',ci_reps=3L,ci_seed=18L,ci_scenarios=FALSE,c1_design_model='exponential',c2_design_model='exponential',c1_exp_input='median',c2_exp_input='median',c1_median=200/30.4375,c2_median=200/30.4375,c1_future_n=0,c2_future_n=0,c1_drop_input='rate',c2_drop_input='rate',c1_dropout_rate=0,c2_dropout_rate=0,c1_multiplier=1,c2_multiplier=1,ci_target=80)
  session$setInputs(ci_pr_timing='.5,1');check(grepl('不一致',output$ci_history_note$html),'history preview reports invalid original event timing before continuation')
  session$setInputs(ci_pr_timing='.25,.5,.75,1');check(grepl('通过完整性',output$ci_history_note$html),'editing original timing refreshes historical validation without uploading again')
  session$setInputs(ci_run=1,ci_trial='1',ci_view_cut='1',ci_view_q='1')
  check(output$ci_result_has_history=='yes'&&output$ci_result_purpose=='rejection'&&nzchar(output$ci_history_result),'history Shiny task forces observed multi-IA source and sequential rules despite hidden legacy input values')
  before<-output$ci_prediction_overview;session$setInputs(ci_history_look='1');check(identical(before,output$ci_prediction_overview),'editing the selected historical look preserves successful result snapshot')
  session$setInputs(ci_history_look='2',ci_pr_futility='z',ci_pr_futility_z='-1,0.1,-1',c1_median=NA_real_,c2_median=NA_real_,ci_horizon=NA_real_,ci_reps=NA_real_,ci_seed=NA_real_,ci_q_values='invalid',ci_scenarios=TRUE)
  session$setInputs(ci_run=2)
  check(output$ci_history_state=='stopped'&&grepl('所选IA已停止',output$ci_prediction_note$html,fixed=TRUE),'terminal history Shiny task ignores hidden future model parameters and reports current stopped decision')
  session$setInputs(ci_purpose='survival',ci_source='demo',ci_grouped='pooled');check(grepl('c1_fit_method',output$ci_groups_ui$html)&&!grepl('c2_fit_method',output$ci_groups_ui$html),'returning to pooled survival task restores one group form')
  session$setInputs(ci_purpose='rejection');check(grepl('c2_fit_method',output$ci_groups_ui$html),'returning to known-group rejection task restores both group forms')
 })
 unlink(tmp)
 check(nchar(ea$parameter_help[['ci_history_look']])>=40,'history look input has explanation and selection guidance')
 check(length(unlist(ea$handbook_index()))==44,'handbook navigation includes historical IA continuity chapter')
})
