local({
  for(f in c('simulation','study','adaptation','patient_adaptation'))source(paste0('R/',f,'.R'))
  cfg<-list(purpose='patient_simulation',d1=50,d_plan=100,d_max=140,p=.5,alpha=.025,hr_assumed=.75,cp_target=.9,cp_min=.8,rule='promising',display_unit='months',control_model=parameter_model('exponential',list(median=100)),n1=100,n2=150,window1=1000,window2=1500,enrollment='batch',dropout_rates=c(0,0),hr_true=.67,reps=40,seed=111)
  set.seed(23);old<-.Random.seed;r<-run_patient_adaptive(cfg)
  check(identical(old,.Random.seed),'patient reassessment preserves caller RNG')
  check(r$completed==80 && nrow(r$trials)==160 && all(r$summary$completed==40),'patient reassessment full requested H0/H1 and paired denominators')
  check(identical(r$trials,run_patient_adaptive(cfg)$trials),'patient reassessment exact seed repeat')
  more<-cfg;more$reps<-60;s<-run_patient_adaptive(more)
  check(identical(r$trials,s$trials[s$trials$SIMID<=40,]),'patient reassessment prefix stable when B changes')
  a<-patient_adaptive_plan(cfg);x<-r$trials
  check(all(x$reject==(a$w1*x$z1+a$w2*x$z2>=a$critical)),'patient final rejects only fixed original weight combination')
  check(all(x$selected_d2>=a$d2_min & x$selected_d2<=a$d2_max) && all(x$events1==cfg$d1) && all(x$events2==x$selected_d2),'patient targets follow independent cohort events')
  o<-r$observed;one<-subset(o,true_hr==1 & design=='adaptive')
  check(!length(intersect(one$USUBJID[one$cohort==1],one$USUBJID[one$cohort==2])),'patient cohorts never reuse subjects')
  check(all(one$entry_day[one$cohort==2]>=x$ia_day[1]) && all(one$DCO_DAY[one$cohort==1]==x$ia_day[1]),'patient IA frozen and stage 2 calendar times start after IA')
  lr<-patient_adaptive_score(subset(one,cohort==1));sw<-survival::survdiff(survival::Surv(time_day,event)~group,data=subset(one,cohort==1))
  check(near(lr$z^2,sw$chisq,1e-10) && near(lr$variance,sw$var[2,2],1e-10),'patient stage logrank agrees with survival software')
  tied<-data.frame(time_day=c(1,1,2,2,3,4,4,5),event=c(1,0,1,1,0,1,0,1),group=rep(c('Control','Treatment'),4))
  st<-survival::survdiff(survival::Surv(time_day,event)~group,data=tied)
  check(near(patient_adaptive_score(tied)$z^2,st$chisq,1e-10),'patient hypergeometric event ties agree with independent reference')
  ci<-cfg;ci$purpose<-'patient_interim';ci$cut<-x$ia_day[1];ci$control<-'Control'
  ia<-subset(one,cohort==1);d<-data.frame(id=ia$USUBJID,group=ia$group,entry=ia$entry_day,time=ia$time_day,obs_day=ia$obs_day,status=ia$status)
  v<-patient_adaptive_interim(d,ci)
  check(near(v$ia$benefit_z,x$z1[1]) && v$decision$selected_d2==x$selected_d2[1],'actual IA stage statistic and target match full generated trial')
  check(!'final_events' %in% names(v$decision) && 'combined_target_events' %in% names(v$decision),'patient output distinguishes combined cohort target from all trial events')
  flip<-ci;flip$control<-'Treatment'
  check(near(patient_adaptive_interim(d,flip)$ia$benefit_z,-v$ia$benefit_z),'patient explicit Control reversal changes stage direction')
  bad<-ci;bad$d1<-bad$d1+1;check(fails(patient_adaptive_interim(d,bad)),'actual IA must equal prespecified first event target')
  bad<-d;bad$group<-'Control';check(fails(patient_adaptive_interim(bad,ci)),'patient reassessment rejects pooled data')
  bad<-d;j<-which(bad$status=='active')[1];bad$time[j]<-bad$time[j]-1;bad$obs_day[j]<-bad$obs_day[j]-1
  check(fails(patient_adaptive_interim(bad,ci)),'patient reassessment rejects stale active follow-up')
  fixed<-cfg;fixed$d_max<-fixed$d_plan;f<-run_patient_adaptive(fixed)
  check(identical(subset(f$trials,design=='adaptive')$reject,subset(f$trials,design=='original')$reject),'patient no-increase special case exactly pairs original decisions')
  miss1<-cfg;miss1$window1<-.01;m1<-run_patient_adaptive(miss1)
  check(all(m1$trials$action=='stage1_window_unreached') && all(m1$trials$reject==FALSE) && all(m1$summary$valid==40),'stage 1 window closure retained as valid nonrejection')
  miss2<-cfg;miss2$window2<-.01;m2<-run_patient_adaptive(miss2)
  check(all(m2$trials$action=='stage2_window_unreached') && all(m2$trials$reject==FALSE) && all(m2$trials$n2_observed==150),'stage 2 target miss does not trigger extra window-end test')
  check(all(m2$summary$rejection_lower==0 & m2$summary$rejection_upper==0),'completed target misses stay in full denominator')
  cancelled<-run_patient_adaptive(cfg,should_cancel=local({i<-0;function(){i<<-i+1;i>5}}))
  check(cancelled$status=='cancelled' && cancelled$completed==10 && all(cancelled$summary$pending==35),'patient cancellation retains completed paired trials and pending count')
  check(all(cancelled$summary$rejection_upper-cancelled$summary$rejection_lower==35/40),'cancelled patient all-requested bounds include pending trials')
  empty<-run_patient_adaptive(cfg,should_cancel=function()TRUE)
  check(empty$completed==0 && all(empty$summary$rejection_lower==0 & empty$summary$rejection_upper==1),'patient immediate cancel has honest zero-to-one bounds')
  tmp<-tempfile(fileext='.R');writeLines(patient_adaptive_reproduction(cancelled),tmp);e<-new.env();sys.source(tmp,e);unlink(tmp)
  check(identical(e$r$trials,cancelled$trials) && identical(e$r$summary,cancelled$summary),'patient exported partial hex config replay lossless')
  unlink(c('patient_adaptive_trials.csv','patient_adaptive_summary.csv'))
  writeLines(patient_adaptive_reproduction(v),tmp);e<-new.env();sys.source(tmp,e);unlink(tmp)
  check(identical(v$decision,e$r$decision) && identical(v$data,e$r$data),'actual IA data and decision export replay lossless');unlink('patient_adaptive_decision.csv')
  # Artificial information-free stage and explicit generated failure preserve probability bounds.
  check(!patient_adaptive_score(transform(tied,group='Control'))$valid,'one-arm stage cannot fabricate Z')
  for(z in list(list(n2=20),list(window2=4000),list(reps=19),list(rate1=0,enrollment='constant'),list(dropout_rates=c(-1,0))))check(fails(patient_adaptive_validate(modifyList(cfg,z))),paste('patient configuration rejects',names(z)[1]))
  units<-cfg;units$display_unit<-'days'
  check(identical(run_patient_adaptive(units)$trials,r$trials),'patient canonical day computation unaffected by display unit')
  e14<-new.env();sys.source('app.R',e14)
  shiny::testServer(e14$register_patient_adaptive_server,{
    session$setInputs(ad_engine='patient',pa_purpose='patient_interim',pa_source='demo',pa_control='Control',pa_unit='months',ad_d1=sum(demo_data()$status=='event'),ad_plan=200,ad_max=280,ad_p=.5,ad_alpha=.025,ad_hr=.75,ad_cp=.9,ad_rule='bounded',ad_cp_min=NA_real_,pa_n1=NA_real_,pa_reps=NA_real_)
    session$setInputs(ad_run=1)
    check(is.null(error()) && !is.null(result()) && result()$config$purpose=='patient_interim','patient Shiny IA task ignores hidden simulation fields')
    prior<-result();session$setInputs(ad_max=300)
    check(identical(result(),prior),'patient Shiny form edits preserve data and configuration snapshot')
    session$setInputs(ad_run=2,ad_d1=1)
    check(!is.null(error()) && identical(result(),prior),'patient invalid IA run retains prior successful result')
    session$setInputs(pa_purpose='patient_simulation',ad_d1=50,ad_plan=100,ad_max=140,pa_n1=100,pa_n2=150,pa_window1=30,pa_window2=50,pa_enrollment='batch',pa_true_hr=.67,pa_reps=20,pa_seed=101,pa_design_model='exponential',pa_exp_input='median',pa_median=3)
    session$setInputs(ad_run=3);submitted<-job()$config
    for(i in 1:100){Sys.sleep(.05);session$elapse(500);if(is.null(job()))break}
    check(is.null(job()) && is.null(error()) && result()$status=='complete','patient background job finishes after an earlier invalid IA')
    check(grepl('运行完成',output$pa_status$html,fixed=TRUE),'patient background completion updates status after earlier error')
    check(identical(result()$trials,e14$run_patient_adaptive(submitted)$trials),'patient worker agrees exactly with submitted synchronous configuration')
    session$setInputs(pa_reps=1000,ad_run=4);session$setInputs(pa_cancel=1)
    for(i in 1:100){Sys.sleep(.05);session$elapse(500);if(is.null(job()))break}
    check(is.null(job()) && result()$status=='cancelled' && all(result()$summary$pending>0),'patient server cancel preserves partial results and requested denominator')
    check(grepl('部分结果',output$pa_status$html,fixed=TRUE) && all(result()$summary$rejection_upper>=result()$summary$rejection_lower),'patient cancelled status and probability bounds render')
  })
  check(length(unlist(e14$handbook_index()))==44,'handbook exposes independent patient reassessment chapter')
})
