local({
  source("R/adaptation.R")
  c<-list(purpose="interim",d1=140,d_plan=280,d_max=420,p=.5,alpha=.025,hr_assumed=.75,
    cp_target=.9,cp_min=.8,rule="promising",z1=2)
  a<-adaptive_plan(c);r<-adaptive_decision(c(1,1.5,2,3),c)
  check(near(c(a$w1,a$w2),sqrt(c(.5,.5))) && near(a$w1^2+a$w2^2,1),"adaptive fixed original-information weights sum to one")
  check(near(a$critical,qnorm(.975)),"adaptive no-early-efficacy threshold agrees with one-sided alpha")
  check(identical(r$final_events,c(280,420,344,280)),"adaptive promising-zone handbook event examples match independent values")
  check(near(r$cp_selected,c(.472153518,.871836066,.900193213,.973205405),1e-8),"adaptive handbook CP examples agree with independent normal calculation")
  check(identical(r$reason,c("maximum_below_cp_min","maximum_target_unattainable","increase_to_target","original_sufficient")),"adaptive all four event-rule branches retained")
  check(near(r$conditional_error,pnorm((qnorm(.975)-sqrt(.5)*r$z1)/sqrt(.5),lower.tail=FALSE)),"adaptive conditional errors equal original design conditional errors")
  check(near(adaptive_cp(r$z1,r$selected_d2,c),r$cp_selected),"adaptive selected event CP recomputes from stage threshold")
  check(!r$target_reached[2] && r$target_reached[3],"adaptive cap does not falsely report desired CP achieved")
  check(adaptive_cp(2,203,c)<.9 && adaptive_cp(2,204,c)>=.9,"adaptive analytic integer minimum independently checked below and at crossing")
  cb<-c;cb$rule<-"bounded";cb$cp_min<-NA_real_
  check(adaptive_decision(1,cb)$final_events==420,"adaptive bounded rule increases despite low promising-zone CP")
  check(!fails(adaptive_plan(cb)),"adaptive hidden promising-zone threshold ignored in bounded rule")
  ca<-c;ca$p<-.3;ca$d1<-84
  ref<-rpact::getDesignInverseNormal(kMax=2,informationRates=c(.3,1),alpha=.025,sided=1,typeOfDesign="noEarlyEfficacy")
  check(near(adaptive_plan(ca)$critical,ref$criticalValues[2]) && is.infinite(ref$criticalValues[1]),"adaptive independent rpact noEarlyEfficacy critical-value reference")
  check(abs(adaptive_exact(c,1)-c$alpha)<1e-9 && abs(adaptive_exact(cb,1)-c$alpha)<1e-9,"adaptive full null rejection integral equals alpha for both adaptation rules")
  fixed<-c;fixed$d_max<-fixed$d_plan
  expected<-pnorm(-log(.67)*sqrt(fixed$d_plan*.25)-qnorm(.975))
  check(abs(adaptive_exact(fixed,.67)-expected)<1e-9,"adaptive no-increase special case agrees with fixed-design analytic power")
  cs<-c;cs$purpose<-"simulation";cs$reps<-10000;cs$seed<-19;cs$hr_true<-.67;cs$z1<-NULL
  set.seed(27);saved<-.Random.seed;z<-run_adaptive_simulation(cs)
  check(identical(saved,.Random.seed),"adaptive simulation preserves caller random state")
  check(nrow(z$trials)==20000 && nrow(z$summary)==4 && all(z$summary$repetitions==10000),"adaptive complete H0/H1 paths retain planned denominators")
  check(identical(z$trials,run_adaptive_simulation(cs)$trials),"adaptive seed exactly reproduces both stage trajectories")
  null<-subset(z$trials,true_hr==1)
  check(identical(null$reject_adaptive,null$reject_original),"adaptive fixed weights yield identical H0 decisions under shared stage noise")
  check(all(z$trials$final_events>=cs$d_plan & z$trials$final_events<=cs$d_max) && all(z$trials$selected_d2==z$trials$final_events-cs$d1),"adaptive event bounds and incremental/cumulative distinction hold every trial")
  check(all(z$trials$reject_adaptive==(z$trials$combination_z>=a$critical)),"adaptive final rejection uses fixed combination score")
  check(all(z$summary$wilson_low<=z$summary$rejection_rate & z$summary$wilson_high>=z$summary$rejection_rate),"adaptive Wilson intervals contain estimated rates")
  tmp<-tempfile(fileext=".R");writeLines(adaptive_reproduction(z),tmp)
  localenv<-new.env();sys.source(tmp,envir=localenv);unlink(tmp)
  check(identical(z$trials,localenv$r$trials) && identical(z$summary,localenv$r$summary),"adaptive exported hex config replay is lossless")
  unlink(c("adaptive_trials.csv","adaptive_summary.csv"))
  for(item in list(list(d1=280),list(d_max=279),list(d_max=2281),list(hr_assumed=1),list(p=0),list(cp_target=1),list(cp_min=.95),list(z1=NA_real_),list(d1=1.5))) {
    bad<-modifyList(c,item)
    check(fails(adaptive_plan(bad)),paste("adaptive rejects invalid",names(item)))
  }
  e13<-new.env();sys.source("app.R",e13)
  shiny::testServer(e13$register_adaptive_server,{
    session$setInputs(ad_purpose="interim",ad_d1=140,ad_plan=280,ad_max=420,ad_p=.5,ad_alpha=.025,ad_hr=.75,ad_cp=.9,ad_rule="bounded",ad_cp_min=NA_real_,ad_z1=2,ad_true_hr=NA_real_,ad_reps=NA_real_,ad_seed=NA_real_)
    session$setInputs(ad_run=1)
    check(!is.null(result()) && result()$decision$final_events==344,"adaptive Shiny IA task excludes hidden simulation and promising-zone fields")
    prior<-result();session$setInputs(ad_z1=-2)
    check(identical(result(),prior),"adaptive Shiny form edits preserve last successful snapshot")
    session$setInputs(ad_run=2,ad_plan=100)
    check(!is.null(error()) && identical(result(),prior),"adaptive Shiny invalid run retains prior results and reports reason")
    session$setInputs(ad_run=3,ad_plan=280,ad_purpose="simulation",ad_z1=NA_real_,ad_true_hr=1,ad_reps=1000,ad_seed=20)
    check(is.null(error()) && nrow(result()$trials)==1000,"adaptive Shiny full design ignores hidden IA Z and avoids duplicate H0 scenario")
  })
  meta<-jsonlite::read_json("docs/handbook-rendered.json")
  h<-e13$handbook_reading_html()
  check(meta$equations==lengths(regmatches(h,gregexpr('data-equation="',h,fixed=TRUE))) && meta$parse_errors==0,"handbook every math source maps to one prerendered vector equation")
  check(identical(meta$markdown_md5,unname(tools::md5sum("docs/METHODS.md"))) && !grepl('type="math/tex',h,fixed=TRUE),"handbook cache matches exact authored source and needs no runtime math")
  check(!grepl('<script',e13$handbook_standalone_html(),fixed=TRUE) && grepl('<svg',h,fixed=TRUE),"handbook reading HTML contains self-contained SVG without scripts")
  check(length(do.call(base::c,unname(e13$handbook_index())))==44,"handbook includes 44 distinct navigation links")
})
