local({
 source("R/sequential_inference.R")
 make_cfg<-function(side="benefit",spend="asOF",timing=c(.5,1),p=.5,futility="none")list(design_mode="sequential",alpha=if(side=="two").05 else .025,sided=side,gs_spending=spend,gs_futility=futility,gs_timing=timing,gs_futility_z=rep(0,length(timing)-1),treatment_fraction=p)
 make_path<-function(cfg,plan,z) {
  k<-length(z);data.frame(SCENARIO=1L,SIMID=2L,look=seq_len(k),events=plan$target_events[seq_len(k)],performed=TRUE,valid=TRUE,target_reached=TRUE,benefit_z=z,information_fraction=plan$information_fraction[seq_len(k)],upper_z=plan$upper_z[seq_len(k)],lower_efficacy_z=plan$lower_efficacy_z[seq_len(k)],futility_z=plan$futility_z[seq_len(k)],action=vapply(seq_len(k),function(j)gs_action(z[j],TRUE,j,plan,cfg$sided),character(1)))
 }
 c<-make_cfg();p<-gs_plan(c,100);d<-make_path(c,p,c(2.5,2.3));r<-gs_inference(c,p,d,2)
 check(near(r$repeated$hr_approx,exp(-c(2.5,2.3)/sqrt(c(50,100)*.25))),'event-information HR conversion preserves benefit direction')
 check(near(r$repeated$repeated_hr_lower,exp((-d$benefit_z-p$upper_z)/sqrt(d$events*.25)),1e-6)&&near(r$repeated$repeated_hr_upper,exp((-d$benefit_z+p$upper_z)/sqrt(d$events*.25)),1e-6),'repeated HR intervals agree with independent boundary inversion')
 check(near(r$repeated$repeated_p,c(.05299060195633574,.01083131367789373),1e-8),'synthetic two-look repeated p reference values')
 check(r$final$available&&near(r$final$adjusted_p,.01149213,1e-6)&&near(r$final$median_unbiased_hr,.6325918,1e-6),'synthetic stage-ordering p and median-unbiased HR reference values')
 check(all(r$repeated$interval_level==.95)&&r$final$interval_level==.95,'single-sided .025 uses symmetric 95% interval rather than 97.5% two-sided interval')
 nonmonotone<-gs_inference(c,p,make_path(c,p,c(2.5,1)),2);check(nonmonotone$repeated$repeated_p[2]>nonmonotone$repeated$repeated_p[1],"current-look repeated p can increase and is not overwritten by a running minimum")
 # Independent one-dimensional integration of the stage-ordering tail, without rpact.
 rho<-sqrt(.5);b<-p$upper_z[1];w<-d$benefit_z[2]
 tail_order<-function(hr) {mu<--log(hr)*sqrt(c(50,100)*.25);pnorm(mu[1]-b)+integrate(function(x)dnorm(x-mu[1])*pnorm((mu[2]+rho*(x-mu[1])-w)/sqrt(1-rho^2)),lower=-Inf,upper=b,rel.tol=1e-10)$value}
 check(near(r$final$adjusted_p,tail_order(1),1e-7),'adjusted p agrees with independent stage-ordering normal quadrature')
 check(near(tail_order(r$final$median_unbiased_hr),.5,1e-6),'median-unbiased estimate inverts stage-ordering probability .5')
 check(near(tail_order(r$final$adjusted_hr_lower),.975,1e-6)&&near(tail_order(r$final$adjusted_hr_upper),.025,1e-6),'adjusted HR confidence limits independently invert the two tail probabilities')
 ongoing<-gs_inference(c,p,d,1)
 check(!ongoing$final$available&&is.na(ongoing$final$adjusted_p)&&nrow(ongoing$repeated)==1,'ongoing prefix has repeated inference without hypothetical final inference')
 dd<-d;dd$benefit_z[2]<-NA;dd$valid[2]<-FALSE;dd$SCENARIO[2]<-999L
 check(identical(gs_inference(c,p,dd,1),ongoing),'all later record values are excluded before validation and inference')
 dd<-d;dd$benefit_z[2]<--4;dd$action[2]<-'final_no_reject'
 check(identical(gs_inference(c,p,dd,1),ongoing),'later analysis Z cannot leak into the selected earlier prefix')
 early<-make_path(c,p,3.2);er<-gs_inference(c,p,early,1)
 check(er$final$available&&near(er$final$adjusted_p,pnorm(-3.2))&&near(er$final$median_unbiased_hr,exp(-3.2/sqrt(12.5))),'first-look efficacy stopping reduces final ordering to first-look normal inference')
 no<-make_path(c,p,c(.5,.1));nr<-gs_inference(c,p,no,2)
 check(nr$final$available&&nr$final$adjusted_p>.025,'planned final non-rejection still receives stage-ordering inference')
 tc<-make_cfg('two','asP',c(.3,.7,1),.4);tp<-gs_plan(tc,103);td<-make_path(tc,tp,c(.2,-.3,-2.8));tr<-gs_inference(tc,tp,td,3)
 check(identical(td$events,c(31,73,103))&&near(tr$repeated$event_information,td$events*.24),'rounded unequal-information targets and unequal allocation use actual planned event counts')
 check(tr$final$available&&tr$final$action=='efficacy_reverse'&&tail(tr$repeated$hr_approx,1)>1,'two-sided reverse-direction stopping provides correctly oriented repeated inference')
 tn<-rpact::getAnalysisResults(rpact::getDesignGroupSequential(informationRates=tp$information_fraction,alpha=.05,sided=2,typeOfDesign='asP',tolerance=1e-10),rpact::getDataset(cumulativeEvents=td$events,cumulativeLogRanks=-td$benefit_z,cumulativeAllocationRatio=rep(.4/.6,3)),tolerance=1e-8)
 check(near(tr$repeated$repeated_p,tn$repeatedPValues)&&near(tr$repeated$repeated_hr_lower,tn$repeatedConfidenceIntervalLowerBounds)&&near(tr$repeated$repeated_hr_upper,tn$repeatedConfidenceIntervalUpperBounds),'two-sided repeated inference agrees with the native rpact path calculation')
 check(all(tr$repeated$interval_level==.95)&&near(tr$repeated$repeated_hr_upper,exp((-td$benefit_z+tp$upper_z)/sqrt(td$events*.24)),1e-6),'two-sided intervals invert the frozen Pocock efficacy boundaries')
 opposite<-td;opposite$benefit_z<--td$benefit_z;opposite$action<-vapply(1:3,function(j)gs_action(opposite$benefit_z[j],TRUE,j,tp,'two'),character(1));or<-gs_inference(tc,tp,opposite,3)
 check(near(tr$repeated$repeated_p,or$repeated$repeated_p)&&near(tr$repeated$repeated_hr_lower,1/or$repeated$repeated_hr_upper,1e-6),'two-sided repeated inference is direction symmetric')
 fc<-make_cfg(futility='z');fp<-gs_plan(fc,100);fd<-make_path(fc,fp,-.1);fr<-gs_inference(fc,fp,fd,1)
 check(fr$final$available&&all(is.finite(fr$repeated$repeated_p))&&fr$final$action=='futility','nonbinding futility stopping provides repeated inference and provides signed stagewise ordering')
 fd<-make_path(fc,fp,c(.5,2.3));check(gs_inference(fc,fp,fd,2)$final$available,'futility-configured design uses its executed original stopping path')
 # Fail closed on invalid history, mixed trials, overshoot, changed design and post-stop data.
 bad<-d;bad$look[1]<-2;check(fails(gs_inference(c,p,bad,2)),'duplicate or missing look numbers rejected')
 bad<-d;bad$valid[1]<-FALSE;check(fails(gs_inference(c,p,bad,2)),'invalid prior analysis cannot be skipped')
 bad<-d;bad$performed[1]<-FALSE;check(fails(gs_inference(c,p,bad,2)),'unperformed prior analysis cannot be treated as observed')
 bad<-d;bad$target_reached[1]<-FALSE;check(fails(gs_inference(c,p,bad,2)),'window cutoff cannot become an extra significance analysis')
 bad<-d;bad$events[1]<-51;check(fails(gs_inference(c,p,bad,2)),'event overshoot requires a separate information-time treatment')
 bad<-d;bad$SIMID[2]<-3;check(fails(gs_inference(c,p,bad,2)),'mixed replicate histories rejected')
 bad<-d;bad$SCENARIO[2]<-3;check(fails(gs_inference(c,p,bad,2)),'mixed scenario histories rejected')
 bad<-p;bad$upper_z[1]<-bad$upper_z[1]+.01;check(fails(gs_inference(c,bad,d,2)),'tampered efficacy boundaries rejected against reconstructed original design')
 bad<-p;bad$information_fraction[1]<-.6;check(fails(gs_inference(c,bad,d,2)),'tampered information fractions rejected')
 bad<-d;bad$upper_z[1]<-0;check(fails(gs_inference(c,p,bad,2)),'record boundary differs from frozen plan')
 bad<-d;bad$action[1]<-'efficacy_benefit';check(fails(gs_inference(c,p,bad,2)),'record actions must agree with observed Z and original plan')
 bad<-make_path(c,p,c(3.2,2.3));check(fails(gs_inference(c,p,bad,2)),'post-efficacy-stop observations rejected')
 check(fails(gs_inference(c,p,d,3))&&fails(gs_inference(c,p,d,NA_real_)),'nonexistent and missing selected looks rejected')
 set.seed(710);seed<-.Random.seed;invisible(gs_inference(c,p,d,2));check(identical(seed,.Random.seed),'inference preserves caller RNG state')
 rm('.Random.seed',envir=.GlobalEnv);invisible(gs_inference(c,p,d,2));check(!exists('.Random.seed',envir=.GlobalEnv,inherits=FALSE),'inference does not create a caller RNG seed')
 uc<-c;uc$display_unit<-'weeks';check(identical(gs_inference(uc,p,d,2),r),'HR and p inference invariant to display time units')
 uc<-c;uc$future_hr<-.01;uc$control_model<-list(id='invalid');uc$true_hr<-50;check(identical(gs_inference(uc,p,d,2),r),'inference ignores future HR and patient-generation truth')
 script<-gs_inference_script(r);check(!any(grepl('true_hr|control_model|future_hr|DCO_DAY',script)),'reproduction contains frozen design and observed prefix only')
 tf<-tempfile();writeLines(script,tf);env<-new.env(parent=globalenv());sys.source(tf,env);unlink(tf)
 check(identical(env$inference,r),'saved inference script reproduces exact in-memory tables')
 check(near(read.csv('sequential_repeated_replayed.csv')$repeated_p,r$repeated$repeated_p)&&near(read.csv('sequential_final_replayed.csv')$adjusted_p,r$final$adjusted_p),'script writes matching repeated and final CSVs');unlink(c('sequential_repeated_replayed.csv','sequential_final_replayed.csv'))
 ei<-new.env(parent=globalenv());invisible(sys.source('app.R',ei));ui<-as.character(ei$ui)
 check(grepl('st_inference',ui,fixed=TRUE)&&grepl('st_inf_look',ui,fixed=TRUE)&&nchar(ei$parameter_help[['st_inf_look']])>=40,'inference UI provides separate navigation and adjacent parameter guidance')
 check(inherits(ei$gs_inference_table(r$repeated),'datatables')&&inherits(ei$gs_inference_table(r$final),'datatables'),'inference tables render their full Chinese numeric column definitions')
 check(inherits(ei$gs_inference_table(data.frame()),'datatables'),'unavailable inference renders an empty table without a column-definition error')
 check(length(unlist(ei$handbook_index()))==44,'handbook includes the adjusted inference chapter')
})
