local({
 source('R/patient_prediction_process.R')
 d<-validate_data(demo_data(),540);d$group<-rep(c('Control','Treatment'),length.out=nrow(d))
 cfg<-list(purpose='patient_prediction',cut=540,control='Control',origin='2025-01-01',d1=sum(d$event),d_plan=200,d_max=280,p=.5,alpha=.025,hr_assumed=.75,cp_target=.9,rule='bounded',display_unit='months',n2=400,window2=1800,enrollment='batch',dropout_rates=c(.001,.002),reps=40,seed=101,model_mode='fit',uncertainty='plugin',fit_method='exponential')
 sc<-data.frame(name=c('same','lowT','noCdrop','moreDrop'),event_control_q=1,event_treatment_q=c(1,.75,1,1),enroll_q=1,dropout_control_q=c(1,1,0,2),dropout_treatment_q=c(1,1,1,2))
 plain<-run_patient_prediction(d,cfg);cfg$scenarios<-sc
 set.seed(5);old<-.Random.seed;r<-run_patient_prediction(d,cfg)
 check(identical(old,.Random.seed),'process/scenario prediction preserves caller RNG')
 base<-subset(r$trials,SCENARIO=='输入基准');x<-base;x$SCENARIO<-NULL
 check(identical(as.list(x),as.list(plain$trials)),'paired baseline retains original fixed-process patient simulation exactly')
 same<-subset(r$trials,SCENARIO=='same');same$SCENARIO<-NULL
 check(identical(as.list(same),as.list(plain$trials)),'identical future scenario yields identical cuts, scores and decisions')
 check(r$completed==200 && r$completed_batches==40 && nrow(r$trials)==400 && all(r$summary$requested==40),'scenario progress counts batches and every summary retains B denominator')
 check(all(r$trials$z1==r$ia$benefit_z) && length(unique(subset(r$trials,design=='adaptive')$selected_d2))==1,'all future scenarios freeze current IA and selected D2')
 check(all(r$scenario_contrasts$mean_rejection_difference[r$scenario_contrasts$SCENARIO=='same']==0) && all(r$scenario_contrasts$both_hit_wait_difference_day[r$scenario_contrasts$SCENARIO=='same']==0),'identity scenario paired rejection and timing differences are zero')
 low<-subset(r$trials,SCENARIO=='lowT');high<-subset(r$trials,SCENARIO=='moreDrop')
 check(all(low$target_wait_day>=base$target_wait_day) && all(high$target_wait_day>=base$target_wait_day),'shared random numbers preserve monotone target time for lower events or higher dropout')
 c2<-cfg;c2$scenarios<-sc[c(4,2,1,3),];r2<-run_patient_prediction(d,c2)
 check(identical(as.list(subset(r2$trials,SCENARIO=='lowT')),as.list(subset(r$trials,SCENARIO=='lowT'))),'scenario reordering does not change an existing trajectory')
 c3<-cfg;c3$scenarios<-sc[1:2,];r3<-run_patient_prediction(d,c3)
 check(identical(as.list(subset(r3$trials,SCENARIO=='输入基准')),as.list(base)),'adding scenarios preserves baseline parameter and patient random numbers')
 more<-cfg;more$reps<-60;rr<-run_patient_prediction(d,more)
 check(identical(as.list(r$trials),as.list(rr$trials[rr$trials$SIMID<=40,])),'process/scenario result prefixes stable when B increases')
 sample<-patient_prediction_sample(r,3,'noCdrop');check(identical(as.list(sample$rows),as.list(subset(r$trials,SIMID==3&SCENARIO=='noCdrop'))),'scenario selection regenerates exactly the saved replicate')
 a<-r$plan;z<-subset(r$trials,action=='tested')
 check(all(z$reject==(a$w1*z$z1+a$w2*z$z2>=a$critical)),'future scenarios keep the original confirmatory weights')
 po<-cfg;po$process_uncertainty<-'gamma';po$enrollment<-'constant';po$dropout_rates<-NULL;po$rate2<-NULL;po$recruit_start<-0;po$recruit_end<-300;po$recruit_complete<-TRUE;po$enroll_prior_shape<-1;po$enroll_prior_rate<-30;po$drop_prior_shape<-.5;po$drop_prior_rate<-50
 pp<-run_patient_prediction(d,po);p<-pp$process_posteriors
 check(near(p$enroll,c(shape=1+sum(d$entry<=300),rate=330)),'overall enrollment Gamma posterior uses complete count and actual open-window length')
 for(lab in names(p$dropout)) {dd<-d[d$group==lab,];check(near(p$dropout[[lab]],c(shape=.5+sum(dd$status=='dropout'),rate=50+sum(dd$time))),paste(lab,'dropout posterior uses all censor/event/exit exposure'))}
 check(nrow(pp$process_draws)==40 && all(is.finite(as.matrix(pp$process_draws))) && all(pp$process_draws[,-1]>0),'one common set of process-rate draws is recorded per batch')
 table<-patient_prediction_process_table(pp)
 check(nrow(table)==3 && near(table$posterior_mean[1],p$enroll['shape']/p$enroll['rate']*time_factor('months')),'posterior process table converts mean rates to selected time units')
 check(near(table$posterior_rate[1],330/time_factor('months')) && near(table$historical_exposure[1],300/time_factor('months')),'posterior table converts rate exposure and historical window consistently')
 pe<-patient_prediction_process_export(pp)
 check(near(pe$enroll_rate_per_months,pe$enroll_rate_per_day*time_factor('months')),'process draw export retains day rates and selected-unit rates')
 drop<-cfg;drop$process_uncertainty<-'gamma_dropout';drop$dropout_rates<-NULL;drop$drop_prior_shape<-.5;drop$drop_prior_rate<-50;drop$recruit_start<-NA_real_;drop$enroll_prior_shape<-NA_real_
 dr<-run_patient_prediction(d,drop)
 check(is.null(dr$process_posteriors$enroll) && nrow(patient_prediction_process_table(dr))==2,'dropout-only posterior ignores hidden enrollment posterior inputs')
 nonph<-drop;nonph$model_mode<-'manual';nonph$manual_models<-list(parameter_model('lognormal',list(median=300,scale=.7)),parameter_model('weibull',list(median=450,shape=1.4)))
 check(run_patient_prediction(d,nonph)$completed==200,'manual distinct group distributions combine with dropout posterior and scenarios')
 gam<-po;gam$uncertainty<-'gamma';gam$prior_shape<-.5;gam$prior_rate<-50
 gr<-run_patient_prediction(d,gam)
 check(gr$completed==200 && all(gr$trials$generation_valid),'event Gamma and process Gamma jointly propagate through future patients')
 bt<-drop;bt$uncertainty<-'bootstrap';br<-run_patient_prediction(d,bt)
 check(all(br$trials$z1==r$ia$benefit_z) && identical(br$ia_observed,r$ia_observed),'Bootstrap plus process posterior never resamples fixed IA')
 bay<-po;bay$reps<-20;bay$uncertainty<-'bayes_weibull';bay$fit_method<-'weibull';bay$log_eta_mean<-log(450);bay$log_eta_sd<-1;bay$log_shape_mean<-0;bay$log_shape_sd<-.75;bay$mcmc_chains<-4;bay$mcmc_warmup<-1000;bay$mcmc_draws<-3000
 byr<-run_patient_prediction(d,bay);check(all(patient_prediction_diagnostics(byr)$passed) && byr$completed==100 && all(byr$trials$generation_valid),'diagnosed Weibull posterior combines with process posterior and shared scenarios')
 unit<-po;unit$display_unit<-'weeks'
 check(identical(as.list(run_patient_prediction(d,unit)$trials),as.list(pp$trials)),'process posterior and scenarios invariant to display units')
 # Component-level coupling: zero Control dropout does not perturb Treatment draws.
 ia<-list(plan=r$plan,ia=r$ia,decision=r$decision,observed=r$ia_observed,data=r$data)
 z<-patient_prediction_extended_batch(d,cfg,r$models,NULL,ia,3)
 process<-list(enroll_rate=NA_real_,dropout_rates=cfg$dropout_rates)
 t0<-patient_prediction_scenario_truth(cfg,z$draws,process,z$latent,r$scenarios[1,],names(r$models),d$id,3)
 tc<-patient_prediction_scenario_truth(cfg,z$draws,process,z$latent,r$scenarios[r$scenarios$name=='noCdrop',],names(r$models),d$id,3)
 ix<-t0$group=='Treatment';check(identical(t0[ix,],tc[ix,]),'zero dropout scenario does not shift another group event or dropout stream')
 fast<-po;fast$scenarios<-data.frame(name='faster',event_control_q=1,event_treatment_q=1,enroll_q=2,dropout_control_q=1,dropout_treatment_q=1)
 fr<-run_patient_prediction(d,fast)
 check(all(subset(fr$trials,SCENARIO=='faster')$target_wait_day<=subset(fr$trials,SCENARIO=='输入基准')$target_wait_day),'paired faster enrollment cannot delay any observable event target')
 cancel<-run_patient_prediction(d,po,should_cancel=local({i<--1;function(){i<<-i+1;i>5}}))
 check(cancel$completed_batches==5 && cancel$completed==25 && all(cancel$summary$pending==35),'cancellation occurs after whole scenario batch and retains per-scenario pending')
 check(all(abs(cancel$summary$rejection_upper-cancel$summary$rejection_lower-35/40)<1e-12),'all-request rejection bounds account for pending in each scenario')
 empty<-run_patient_prediction(d,po,should_cancel=function()TRUE)
 check(empty$completed==0 && all(empty$summary$rejection_lower==0 & empty$summary$rejection_upper==1) && all(empty$resources$all_wait_median_lower_day==0),'immediate process/scenario cancellation has full unknown probability and time bounds')
 check(nrow(patient_prediction_process_export(empty))==0 && nrow(unit_export(empty$trials,'months','ia_day'))==0 && all(c('time_unit','days_per_unit','enroll_rate_per_months') %in% names(patient_prediction_process_export(empty))),'immediate cancellation exports zero rows with rate and unit column schemas intact')
 tmp<-tempfile(fileext='.R');writeLines(patient_prediction_reproduction(cancel),tmp);e<-new.env();sys.source(tmp,e);unlink(tmp)
 check(identical(as.list(e$r$trials),as.list(cancel$trials)) && identical(e$r$process_draws,cancel$process_draws) && identical(e$r$scenario_contrasts,cancel$scenario_contrasts),'partial posterior/scenario reproduction restores all paired paths and common rates losslessly')
 unlink(c('patient_prediction_trials.csv','patient_prediction_summary.csv','patient_prediction_resources.csv','patient_prediction_scenario_contrasts.csv','patient_prediction_paired.csv','patient_prediction_process_draws.csv'))
 broken<-new.env();sys.source('R/patient_prediction_process.R',broken);original<-broken$patient_prediction_scenario_truth
 broken$patient_prediction_scenario_truth<-function(cfg,draws,process,latent,s,labs,ids,b){if(s$name=='lowT')stop('deliberate scenario failure');original(cfg,draws,process,latent,s,labs,ids,b)}
 bad<-broken$run_patient_prediction_extended(d,cfg)
 check(all(subset(bad$summary,SCENARIO=='lowT')$invalid==40) && all(subset(bad$summary,SCENARIO=='输入基准')$valid==40),'one failed scenario does not discard valid paired baseline or other scenarios')
 check(all(subset(bad$summary,SCENARIO=='lowT')$rejection_lower==0 & subset(bad$summary,SCENARIO=='lowT')$rejection_upper==1),'scenario-specific failure has complete-request bounds')
 check(all(subset(bad$scenario_contrasts,SCENARIO=='lowT')$difference_lower==-1 & subset(bad$scenario_contrasts,SCENARIO=='lowT')$difference_upper==1),'missing paired scenario decision gives honest minus-one-to-one contrast bounds')
 broken$patient_prediction_process_draw<-function(...)stop('deliberate common posterior draw failure');bad<-broken$run_patient_prediction_extended(d,po)
 check(all(bad$summary$invalid==40) && all(is.na(bad$resources$mean_new_n)),'common posterior failure retained in every scenario without fabricating resource counts')
 for(change in list(list(recruit_complete=FALSE),list(recruit_end=600),list(recruit_start=300),list(enrollment='piecewise'),list(drop_prior_shape=0),list(enroll_prior_rate=0)))check(fails(patient_prediction_validate(d,modifyList(po,change))),paste('process validation rejects',names(change)[1]))
 invalid<-cfg;invalid$scenarios$name[2]<-'same';check(fails(patient_prediction_validate(d,invalid)),'duplicate scenario names cannot merge results')
 invalid<-cfg;invalid$scenarios$event_control_q[1]<-0;check(fails(patient_prediction_validate(d,invalid)),'event hazard multiplier cannot be zero')
 invalid<-cfg;invalid$scenarios$enroll_q[1]<-2;check(fails(patient_prediction_validate(d,invalid)),'batch enrollment does not accept unused rate multiplier')
 invalid<-cfg;invalid$reps<-10000;invalid$n2<-5000;check(fails(patient_prediction_validate(d,invalid)),'patient-scenario product enforces shared resource limit')
 parsed<-patient_prediction_parse_scenarios('情景,Control事件倍率,Treatment事件倍率,入组倍率,Control脱落倍率,Treatment脱落倍率\n示例,1,.75,1,0,1')
 check(nrow(parsed)==1 && parsed$dropout_control_q==0 && parsed$event_treatment_q==.75,'scenario CSV maps exact required names and values')
 check(fails(patient_prediction_parse_scenarios('a,b\nx,1')),'scenario CSV rejects ambiguous structure')
 e16<-new.env();sys.source('app.R',e16)
 shiny::testServer(e16$register_patient_adaptive_server,{
  session$setInputs(ad_engine='patient',pa_purpose='patient_prediction',pa_source='demo',pa_control='Control',pa_unit='months',ad_d1=109,ad_plan=200,ad_max=280,ad_p=.5,ad_alpha=.025,ad_hr=.75,ad_cp=.9,ad_rule='bounded',pg_n2=400,pg_window2=60,pg_reps=20,pg_seed=101,pg_model_mode='fit',pg_uncertainty='plugin',pg_fit_method='exponential',pg_process='gamma',pg_recruit_start=0,pg_recruit_end=10,pg_recruit_complete=TRUE,pg_enroll_prior_shape=1,pg_enroll_prior_rate=1,pg_drop_prior_shape=.5,pg_drop_prior_rate=50/30.4375,pg_compare=TRUE,pg_scenario_csv='情景,Control事件倍率,Treatment事件倍率,入组倍率,Control脱落倍率,Treatment脱落倍率\n风险下降,1,.75,1,1,1',pg_enrollment='batch',pg_rate2=NA_real_,pgdc_dropout_rate=NA_real_)
  session$setInputs(ad_run=1);submitted<-job()$config
  for(i in 1:100){Sys.sleep(.05);session$elapse(500);if(is.null(job()))break}
  check(is.null(error()) && result()$completed==40 && result()$total==40,'posterior/scenario Shiny worker ignores hidden fixed-rate controls and reports full progress')
  check(identical(as.list(result()$trials),as.list(e16$run_patient_prediction(result()$data,submitted)$trials)),'posterior/scenario private worker agrees with synchronous engine')
  prior<-result();session$setInputs(pg_view_scenario='风险下降',pg_view_trial=3)
  check(nzchar(output$pg_observed) && identical(result(),prior),'scenario/replicate preview uses result snapshot without refitting')
  session$setInputs(pg_recruit_complete=FALSE,ad_run=2)
  check(!is.null(error()) && identical(result(),prior),'unconfirmed enrollment window preserves previous successful result')
  session$setInputs(pg_process='gamma_dropout',pg_enrollment='batch',pg_compare=FALSE,pg_scenario_csv='invalid',pg_recruit_end=NA_real_,pg_enroll_prior_rate=NA_real_)
  z<-config();check(is.null(z$config$scenarios) && is.null(z$config$recruit_end) && z$config$enrollment=='batch','dropout-only task ignores hidden comparison and enrollment-posterior fields')
  check(identical(output$pg_has_scenarios,'true') && identical(output$pg_has_process,'true'),'result display follows successful snapshot rather than edited input options')
 })
 check(length(unlist(e16$handbook_index()))==44,'handbook exposes process posterior and scenario derivations')
})
