register_batch_help <- function() {
  h<-get("parameter_help",envir=parent.frame())
  h<-c(h,c(
    ba_mode="固定真值批量研究比较指定参数下的拒绝概率；assurance按设计先验抽整轮真值并积分成功概率；仅参数校准只计算Weibull等价参数，不需情景、入组或模拟数。",
    ba_unit="输入和显示的经过时间单位，默认月，1月=30.4375日。切换会转换已填时间、风险率和入组率，形状/概率/倍数不变；已提交结果及下载保持原单位。",
    ba_source="Control分布可直接指定，或用两个固定时点生存率反向校准Weibull。校准概率应为同一总体的给定目标，不是把两次KM估计当成无误差真实概率。",
    ba_cal_t1="Weibull校准第一个正随访时点t1，自患者风险起点起算。例如6月；需t1<t2，不能使用研究DCO或时间0。时点与输入单位一致。",
    ba_cal_t2="第二个正随访时点t2，需严格大于t1。选择不同风险年龄，例如12月；两个时点与对应生存率须来自同一目标总体。",
    ba_cal_s1="第一个时点目标生存率S1，在(0,1)，且严格大于第二个S2。它是指定总体概率；不能把校准称为患者似然拟合或给形状参数估计区间。",
    ba_cal_s2="第二个时点目标生存率S2，在(0,1)，需S2<S1。相等概率没有有限正Weibull形状；默认示例0.5不是通用研究参数建议。",
    ba_origin="研究时间0的日期用于所选模拟ADTTE导出。建议填方案研究起点，患者风险时间自各自入组开始；仅参数校准不使用此日期。",
    ba_endpoint="固定Final分析的目标终点，PFS或OS；此批量入口每次生成一个终点，不是联合PFS/OS研究。联合轨迹另在第八入口提供。",
    ba_allocation="Treatment简单随机分配概率p，0.01–0.99，1:1填0.5、Treatment:Control=2:1填2/3。Treatment按恒定HR或风险年龄分段HR作用于Control生成分布。",
    ba_enroll_mode="基准总体入组支持恒定或分段Poisson，情景enroll_scale乘各段强度，切点保持原研究时间。批量首批不提供固定日程、中心或分层随机。",
    ba_enroll_rate="基准恒定入组率，人/当前单位，需正，例如15人/月。实际情景率乘enroll_scale，达到该情景N后停止；不是每期固定入组人数。",
    ba_enroll_cuts="分段基准总体入组切点，正递增、逗号分隔，自研究起点起算。情景改变入组强度但不改变这些切点；只有分段入组分支读取。",
    ba_enroll_rates="分段基准入组率，非负、人/当前单位，数量=切点数+1。尾段0可使计划入组不完成；窗口末及未知规则状态仍保留。",
    ba_scenario_source="列表组合生成各轴笛卡尔积，最多60情景；或上传与效应模式对应的七/八列CSV直接给每行情景。文件可选；CSV分支不解析隐藏的各轴列表。",
    ba_csv_unit="CSV中cut_value为时间时使用的文件单位，默认月，独立于界面单位；变更界面单位不改写文件。事件规则时cut_value始终为整数事件数，此字段不参与计算。",
    ba_file="情景CSV需且仅需label,n,hr,time_scale,enroll_scale,dropout_scale,cut_value七列；NPH另加文本profile列匹配定义名称。label唯一，非label/profile列数值；cut_value按所选规则为文件声明单位时间或整数D*，不是患者数据。",
    ba_n_values="N情景列表，10–5000整数，逗号分隔。如200,300；列表组合与其余轴形成笛卡尔积，全部规模有上限，不输入重复值。",
    ba_hr_values="固定真值模式为真实Treatment/Control HR列表；assurance为logHR先验中位HR列表。0.01–100，如0.7,1；先验不以均值HR等同于中位HR，首批assurance只单侧获益。",
    ba_time_scales="Control全部生存时间的缩放倍数列表，0.01–100。1保留基准，1.25使相同分位时间延长25%；PWE切点/率成对缩放，混合两成分均缩放，不只改第一成分。",
    ba_enroll_scales="基准总体入组强度倍数，0.01–100，如0.8,1,1.2。各段强度同乘倍数，切点不变；不直接改变每个患者的生存时间。",
    ba_dropout_scales="两组基准独立退出风险同乘的情景倍数，0–100，0表示不退出。每组基准率分别输入；不把退出与行政DCO合并为一个风险参数。",
    ba_cut_values="固定规则填写共同DCO时间；target/event_minimum填写累计D*整数；last_entry_followup填写最后计划患者入组后的追加随访时间。时间使用当前单位，最多60情景。",
    ba_cut_rule="固定Final；事件目标；事件目标且满足最短研究持续时间；全部计划N入组完成后追加随访。每轮只进行一次Final检验，本入口不执行组序贯监测或重估。",
    ba_max="非固定规则最大研究窗口，正数、最长3650日。目标/全部入组/随访规则未满足仍保留该轮，按预先选择的窗口规则处理，不能事后挑选。",
    ba_minimum="事件+最短研究时间的下限，自研究起点起算，正数且不超过最大窗口。达到D*较早时继续至此下限；不是每名患者的最短随访年龄。",
    ba_miss="窗口内未满足完整规则时预设关闭且不拒绝，或窗口末执行一次Final检验。必须在模拟前确定；未达标轮次保留，单独报告完整规则满足比例。",
    ba_primary="预定一次Final主分析可选log-rank、Cox、FH、RMST差或固定时点生存率差。只有主分析决定本次正式成功；可另外比较预定方法，不能按结果择优拒绝。",
    ba_sided="固定真值可单侧Treatment获益或双侧差异。assurance固定单侧获益，仍由所填alpha决定；切换模式/方向不会自动调整alpha。",
    ba_alpha="预定一次Final检验alpha，0.0001–0.2，如单侧0.025或双侧0.05。情景比较是计算比较，不自动构造跨情景的临床多重性检验。",
    ba_estimate="勾选时额外保存各轮Cox估计与普通95%区间；Cox主检验时必做。PH的覆盖/偏倚对照实际抽取HR；NPH的Cox仅描述，不赋单一HR真值或报告覆盖/偏倚。",
    ba_prior_hr_sd="logHR设计先验SD，0–2。中心为情景log(hr)，因此hr列为先验中位HR；0退化为固定HR。每轮只抽一次供全部患者使用，范围外抽样保留失败、不重抽或截断。",
    ba_prior_time_sd="Control全时间尺度倍数的log先验SD，0–1，log均值固定0。0表示无该项不确定性；非0按试验抽一倍数，两组共同缩放，不作为患者脆弱性。",
    ba_reps="每情景20–10000轮；总轮次≤20万、患者×轮次≤3000万、方法×轮次≤50万。可先100探索设置；每轮独立，概率MCSE与失败/取消下的概率范围分别报告。",
    ba_seed="主种子0–2147483647整数。按原情景ID及轮次派生，情景独立生成；相同SIMID不是配对患者或公共随机数。本轮复现代码尚未执行。",
    ba_reference="参照情景ID，需在提交情景表内；输出其他情景相对它的成功概率差及独立MCSE。不是按结果自动选择最佳参照，提交后保存此选择。",
    ba_filter="选择是否按预先设定成功概率依据及阈值列出候选。只做候选表，未实现自动搜索或唯一最优设计；不勾选时隐藏阈值不参与本次配置。",
    ba_filter_basis="全部请求成功概率下界把未知轮次作为最坏情况；有效轮次Wilson下界只描述有效决策中的Monte Carlo区间。二者分母/含义不同，请预定一种，部分运行不判定候选。",
    ba_threshold="预定候选计算阈值，0.5–0.999，如0.8。达到该估计依据不保证实际真实功效；尚未处理搜索筛选引起的估计偏差或临床多重性。",
    ba_design_mode="固定Final支持PH/NPH和五类方法；组序贯只用PH/log-rank、事件驱动、原计划2–5次分析，窗口未达下一目标关闭不拒绝。两种设计均需运行前确定。",
    ba_gs_timing="计划信息比例，2–5个递增值，首个≥0.1，最后1，如0.5,0.75,1。每个情景D*乘比例后向上取整，边界按取整后的事件比例建立；不能出现重复目标。",
    ba_gs_spending="原alpha消耗，OBF型或Pocock型，按每个原D*取整信息比例建立。真实HR、基准生存或入组倍数不改变原效力界。",
    ba_gs_futility="单侧获益可不设无效界、预设非约束性Z界或约束性beta消耗。模拟始终执行所选原规则；双侧首批不设无效界，隐藏值不参与配置。",
    ba_gs_z="非约束性无效Z界，需K−1个，−5至5，正Z为Treatment获益。如3次分析可填0,0；不是名义p或HR，停止后不补做Final。",
    ba_beta_basis="约束性beta设计可输入beta或目标功效1−beta；只读取所选形式，另一形式用于等价换算。该设计参数不是某个真实HR情景的模拟功效。",
    ba_gs_beta="原设计beta，0.01–0.5，对应目标功效0.5–0.99，常以0.2表示目标功效0.8；实际取整D*下的功效仍须模拟和校准。",
    ba_gs_power="原设计目标功效1−beta，0.5–0.99；切换到beta时按1−power换算。此目标用于beta边界，不替代研究结果。",
    ba_gs_beta_spending="约束性beta消耗支持OBF/Pocock/HSD；连同alpha联合建立效力/无效界。该引擎及本批接入均仍待复核。",
    ba_gs_gamma="HSD beta消耗形状gamma，−10至5，仅HSD读取。0对应线性消耗极限，负/正形状改变消耗时序；请按方案填写。",
    ba_gs_design_hr="原设计备择HR，0.01≤HR<1，用于beta所需事件数参照。它独立于每个真实HR情景及CP未来HR；更改真实情景不改原设计HR。",
    ba_fixed_benchmark="额外生成同轮患者潜在轨迹到原Final D*的一次固定检验，保留其窗口关闭与失败，并与GS成功作配对比较。仅模拟参照，不在实际早停后追加正式检验。",
    ba_cp_look="从保存的所选情景/轮次选择有效且按原规则继续的IA。停止、未达目标、无效或尚未运行的分析不计算CP；使用该IA已观察Z，不使用未来潜在结局。",
    ba_cp_hr="条件功效诊断中假定的未来HR，0.01–100，如0.7。它是用户给定未来效应，不自动读取模拟真实HR或设计HR；不改变已保存路径。",
    ba_cp_respect="非约束性Z可计算遵守原无效界或假定未来忽略无效界的CP；约束性beta必须遵守。诊断不修改原模拟执行规则，也不触发重估。",
    ba_effect_mode="固定真值批量可用恒定PH或风险年龄分段HR。assurance首批仍固定PH；NPH只在固定真值模式读取定义与效应幅度，不读取隐藏PH HR列表。",
    ba_profiles="每行：名称 | 风险年龄切点列表 | 各段HR。无切点写名称 | | HR；切点正递增，HR数=切点数+1且0.01–100。最多12个唯一名称；列表组合使用全部定义，CSV可按profile指定。示例只说明结构。",
    ba_effect_scales="NPH各段HR共同乘的情景幅度，默认1。最终各段HR也需0.01–100。H0定义为全部HR=1，只有幅度1保持H0；小于1会同时降低延迟前段，不能仍称纯延迟效应。",
    ba_compare_methods="运行前指定附加方法，复用同轮患者、组别、退出和同一个DCO。各方法独立报告功效/失败及相对主方法的配对差值；不是任一显著即成功的联合检验。",
    ba_extra_methods="只选择本次要比较的方法；共有五类，主分析自动保留。FH使用本次一组rho/gamma，RMST和生存率差使用同一个预定tau；不根据本轮结果改变方法或时点。",
    ba_fh_rho="FH权重S(t−)^rho[1−S(t−)]^gamma中的rho，0–5；0,0为普通log-rank。较大rho相对增加较早事件权重；仅FH参与主/附加分析时读取。",
    ba_fh_gamma="FH权重中的gamma，0–5；如rho=0,gamma=1相对强调较晚事件。早期无事件信息时权重可能为0，无有效方差保留该方法无效，不删除整个情景。",
    ba_tau="RMST积分上限或固定时点生存率的风险年龄tau，正、最长3650日；不是研究DCO。两组观察需支持tau，KM未降至0且随访不足时不外推，保留无效方法轮次。",
    ba_view_scenario="从最近提交结果选择情景，仅影响样例及明细；不重新运行批量。情景号顺序保存在配置/计划，不按当前未提交的表重新编号。",
    ba_view_trial="选择该情景已生成的轮次，用保存配置和种子恢复所选观察数据。恢复代码及实际下载重放尚未验证；失败轮次留在全部明细中。"))
  for(pre in c("b_","bc_","bt_")) {
    for(k in names(simulation_defaults()))if(paste0("s1_",k) %in% names(h))h[paste0(pre,k)]<-h[[paste0("s1_",k)]]
  }
  h<-register_batch_workspace_help(h)
  assign("parameter_help",h,envir=parent.frame())
}
batch_research_ui <- function() {
  has_fh<-"input.ba_design_mode !== 'sequential' && (input.ba_primary === 'fh' || (input.ba_compare_methods && input.ba_extra_methods && input.ba_extra_methods.indexOf('fh') >= 0))"
  has_tau<-"input.ba_design_mode !== 'sequential' && (input.ba_primary === 'rmst' || input.ba_primary === 'survival' || (input.ba_compare_methods && input.ba_extra_methods && (input.ba_extra_methods.indexOf('rmst') >= 0 || input.ba_extra_methods.indexOf('survival') >= 0)))"
  nav_panel("批量研究与参数校准",value="batch",
    div(class="page-title",h2("批量研究与参数校准"),actionButton("ba_run","运行所选需求",class="btn-primary"),actionButton("ba_cancel","取消后台模拟")),
    batch_workspace_entry_ui(),
    conditionalPanel("input.ba_run_source !== 'config_json'",section("本次需求",fields(selectInput("ba_mode","需求",c("固定真值批量设计比较"="fixed_truth","设计保证概率 assurance"="assurance","仅校准Weibull参数"="calibration")),selectInput("ba_unit","时间单位",c("日"="days","周"="weeks","月"="months"),"months")))),
    conditionalPanel("input.ba_run_source !== 'config_json' && input.ba_mode !== 'calibration'",section("试验设计",selectInput("ba_design_mode","设计",c("预定一次Final"="fixed","组序贯"="sequential")))),
    p(class="field-note","开发稿待复核。两组、单终点、按预定原规则分析；参数校准只填写时点和生存率。"),
    navset_card_tab(id="ba_tabs",
      nav_panel("基准与校准",value="ba_baseline",
        conditionalPanel("input.ba_mode !== 'calibration'",
          section("Control分布来源",selectInput("ba_source","参数来源",c("直接指定参数"="parameters","两个时点生存率校准Weibull"="two_survival"))),
          conditionalPanel("input.ba_source === 'parameters'",section("基准Control生成分布",event_parameter_fields("b_","months",simulation_defaults(),simulation=TRUE)))),
        conditionalPanel("input.ba_mode === 'calibration' || input.ba_source === 'two_survival'",
          section("Weibull两时点校准",
            fields(numericInput("ba_cal_t1","第一随访时点（月）",6,min=.001),numericInput("ba_cal_s1","第一时点生存率",.75,min=.000001,max=.999999)),
            fields(numericInput("ba_cal_t2","第二随访时点（月）",12,min=.001),numericInput("ba_cal_s2","第二时点生存率",.5,min=.000001,max=.999999)),
            p(class="field-note","由指定总体概率求形状、尺度和中位时间，不是个体数据拟合。批量模式使用校准模型作为基准。"))),
        conditionalPanel("input.ba_mode !== 'calibration'",
          section("Treatment效应",
            conditionalPanel("input.ba_mode === 'fixed_truth' && input.ba_design_mode !== 'sequential'",selectInput("ba_effect_mode","效应模式",c("恒定PH"="ph","风险年龄分段HR"="nph"))),
            conditionalPanel("input.ba_mode === 'fixed_truth' && input.ba_design_mode !== 'sequential' && input.ba_effect_mode === 'nph'",
              textAreaInput("ba_profiles","分段HR定义：名称 | 切点（月） | HR列表","H0 | | 1\ndelay | 6 | 1,0.65\nwaning | 6 | 0.65,1\ncross | 6 | 1.25,0.65",rows=5,width="100%"),
              p(class="field-note","列表组合使用全部定义；CSV另加profile列选择定义。切点为个体风险年龄；HR再乘各情景效应幅度。")),
            conditionalPanel("input.ba_mode === 'assurance'",p(class="field-note","assurance使用PH设计先验，每轮抽取整轮HR和时间尺度。"))),
          section("研究与入组",fields(dateInput("ba_origin","研究起点日期","2025-01-01"),selectInput("ba_endpoint","终点",c("PFS","OS"))),numericInput("ba_allocation","Treatment分配概率 p",.5,min=.01,max=.99),
            selectInput("ba_enroll_mode","基准总体入组",c("恒定Poisson"="constant","分段Poisson"="piecewise")),
            conditionalPanel("input.ba_enroll_mode === 'constant'",numericInput("ba_enroll_rate","基准入组率（人/月）",15,min=.000001)),
            conditionalPanel("input.ba_enroll_mode === 'piecewise'",fields(textInput("ba_enroll_cuts","入组切点（研究月数）","3,6"),textInput("ba_enroll_rates","基准各段入组率（人/月）","9,18,12")))),
          section("两组基准退出",h4("Control"),dropout_parameter_fields("bc_","months",simulation_defaults()),h4("Treatment"),dropout_parameter_fields("bt_","months",simulation_defaults())))),
      nav_panel("情景与规则",value="ba_scenarios",
        conditionalPanel("input.ba_mode !== 'calibration'",
          section("截点与窗口",conditionalPanel("input.ba_design_mode !== 'sequential'",selectInput("ba_cut_rule","截点规则",c("固定研究DCO"="fixed","达到事件D*"="target","达到D*且满足最短研究时间"="event_minimum","全部N入组后追加随访"="last_entry_followup"))),
            conditionalPanel("input.ba_design_mode === 'sequential'",p(class="field-note","各情景cut_value为原Final D*；逐次事件目标按原信息比例取整，窗口未达下一目标关闭不拒绝。")),
            conditionalPanel("input.ba_design_mode === 'sequential' || input.ba_cut_rule !== 'fixed'",numericInput("ba_max","最大研究窗口（月）",48,min=.001),conditionalPanel("input.ba_design_mode !== 'sequential'",selectInput("ba_miss","窗口末未满足规则",c("关闭且不拒绝"="no_reject","窗口末一次Final检验"="analyze")))),
            conditionalPanel("input.ba_design_mode !== 'sequential' && input.ba_cut_rule === 'event_minimum'",numericInput("ba_minimum","最短研究持续时间（月）",24,min=.001))),
          section("情景输入",selectInput("ba_scenario_source","情景来源",c("各轴列表组合"="grid","情景CSV"="csv")),
            conditionalPanel("input.ba_scenario_source === 'csv'",fileInput("ba_file","情景 CSV",accept=".csv"),
              conditionalPanel("input.ba_design_mode !== 'sequential' && (input.ba_cut_rule === 'fixed' || input.ba_cut_rule === 'last_entry_followup')",selectInput("ba_csv_unit","文件中的时间单位",c("日"="days","周"="weeks","月"="months"),"months")),
              p(class="field-note","PH七列：label,n,hr,time_scale,enroll_scale,dropout_scale,cut_value。NPH另加profile；hr为各段HR幅度。时间使用文件声明单位，事件规则cut_value为D*整数。")),
            conditionalPanel("input.ba_scenario_source === 'grid'",textInput("ba_n_values","N列表","200,300"),
              conditionalPanel("input.ba_design_mode === 'sequential' || input.ba_mode === 'assurance' || input.ba_effect_mode !== 'nph'",textInput("ba_hr_values","HR / 先验中位HR列表","0.7,1")),
              conditionalPanel("input.ba_mode === 'fixed_truth' && input.ba_design_mode !== 'sequential' && input.ba_effect_mode === 'nph'",textInput("ba_effect_scales","各段HR幅度列表","1")),
              fields(textInput("ba_time_scales","基准生存时间缩放","1"),textInput("ba_enroll_scales","入组强度倍数","1")),
              fields(textInput("ba_dropout_scales","两组退出风险倍数","1"),textInput("ba_cut_values","DCO（月）/ D* / 追加随访（月）","24"))),
            downloadButton("ba_template","下载当前模式的情景模板"),p(class="field-note","同参数重复情景会拒绝；最多60情景。CSV为设计参数表，无需患者数据。")))),
      nav_panel("检验与模拟",value="ba_analysis",
        conditionalPanel("input.ba_mode !== 'calibration'",
          section("预定Final分析",fields(conditionalPanel("input.ba_design_mode !== 'sequential'",selectInput("ba_primary","主分析",setNames(names(batch_method_names),unname(batch_method_names)))),numericInput("ba_alpha","一次Final alpha",.025,min=.0001,max=.2)),
            conditionalPanel("input.ba_mode === 'fixed_truth'",selectInput("ba_sided","方向",c("单侧Treatment获益"="benefit","双侧差异"="two"))),
            conditionalPanel("input.ba_mode === 'assurance'",p(class="field-note","assurance固定单侧Treatment获益；alpha沿用填写值。")),
            conditionalPanel("input.ba_design_mode !== 'sequential'",checkboxInput("ba_estimate","额外保存Cox估计及普通95%区间",FALSE)),
            conditionalPanel("input.ba_design_mode !== 'sequential'",checkboxInput("ba_compare_methods","同轮比较预定附加方法",FALSE)),
            conditionalPanel("input.ba_design_mode !== 'sequential' && input.ba_compare_methods",checkboxGroupInput("ba_extra_methods","附加方法",setNames(names(batch_method_names)[-1],unname(batch_method_names[-1])),selected=c("fh","rmst","survival")),p(class="field-note","附加方法分别评价，不以任一显著改写主决策。")),
            conditionalPanel(has_fh,fields(numericInput("ba_fh_rho","FH rho",0,min=0,max=5),numericInput("ba_fh_gamma","FH gamma",1,min=0,max=5))),
            conditionalPanel(has_tau,numericInput("ba_tau","预定随访时点 tau（月）",12,min=.001),p(class="field-note","RMST与生存率差使用同一tau；随访不支持时不作KM外推。NPH的Cox无单一HR真值，不报告偏倚/覆盖。"))),
          conditionalPanel("input.ba_design_mode === 'sequential'",section("原组序贯计划",
            p(class="field-note","主分析固定为PH普通log-rank，不输出停止后的未经调整Cox区间。"),
            fields(textInput("ba_gs_timing","原计划信息比例","0.5,0.75,1"),selectInput("ba_gs_spending","alpha消耗",c("OBF型"="asOF","Pocock型"="asP"))),
            conditionalPanel("input.ba_mode === 'assurance' || input.ba_sided === 'benefit'",selectInput("ba_gs_futility","原无效规则",c("不设"="none","非约束性Z"="z","约束性beta消耗"="beta")),
              conditionalPanel("input.ba_gs_futility === 'z'",textInput("ba_gs_z","K−1个正向获益Z界","0,0")),
              conditionalPanel("input.ba_gs_futility === 'beta'",selectInput("ba_beta_basis","原设计输入形式",c("beta"="beta","目标功效"="power")),
                conditionalPanel("input.ba_beta_basis === 'beta'",numericInput("ba_gs_beta","原设计beta",.2,min=.01,max=.5)),
                conditionalPanel("input.ba_beta_basis === 'power'",numericInput("ba_gs_power","原目标功效",.8,min=.5,max=.99)),
                fields(selectInput("ba_gs_beta_spending","beta消耗",c("OBF型"="bsOF","Pocock型"="bsP","HSD型"="bsHSD")),numericInput("ba_gs_design_hr","原设计备择HR",.7,min=.01,max=.999999)),
                conditionalPanel("input.ba_gs_beta_spending === 'bsHSD'",numericInput("ba_gs_gamma","HSD gamma",-4,min=-10,max=5)))),
            checkboxInput("ba_fixed_benchmark","同时生成原D*固定Final参照",FALSE))),
          conditionalPanel("input.ba_mode === 'assurance'",section("设计先验",fields(numericInput("ba_prior_hr_sd","logHR先验SD",.25,min=0,max=2),numericInput("ba_prior_time_sd","log时间倍数先验SD",.15,min=0,max=1)),
            p(class="field-note","logHR均值为log(情景hr)；log时间倍数均值为0。每轮抽一次供整轮共享，范围外失败不重抽。"))),
          section("计算设置",fields(numericInput("ba_reps","每情景重复数",100,min=20,max=10000,step=20),numericInput("ba_seed","主种子",20261005,min=0,max=2147483647,step=1)),numericInput("ba_reference","参照情景ID",1,min=1,max=60,step=1),
            checkboxInput("ba_filter","按预定主分析阈值列出候选",FALSE),conditionalPanel("input.ba_filter",fields(selectInput("ba_filter_basis","候选依据",c("全部请求成功概率下界"="request_lower","有效轮次Wilson下界"="wilson_lower")),numericInput("ba_threshold","成功概率阈值",.8,min=.5,max=.999)))))),
      nav_panel("结果",value="ba_results",uiOutput("ba_status"),
        conditionalPanel("output.ba_result_kind === 'calibration'",section("已提交Weibull校准",DTOutput("ba_calibrated",fill=FALSE),DTOutput("ba_calibration_targets",fill=FALSE))),
        conditionalPanel("output.ba_result_kind === 'batch'",section("保存的情景计划",DTOutput("ba_plan",fill=FALSE)),section("主分析成功概率与资源",DTOutput("ba_overview",fill=FALSE)),section("主分析相对参照情景",DTOutput("ba_comparisons",fill=FALSE)),section("预定候选表",DTOutput("ba_candidates",fill=FALSE)),
          conditionalPanel("output.ba_methods_saved === 'yes'",section("预设方法汇总与估计恢复",DTOutput("ba_method_overview",fill=FALSE)),section("同轮方法配对比较",DTOutput("ba_method_pairs",fill=FALSE))),
          fields(selectInput("ba_view_scenario","查看情景",character()),selectInput("ba_view_trial","查看已生成轮次",character())),section("所选情景主分析轮次",DTOutput("ba_rows",fill=FALSE)),
          conditionalPanel("output.ba_sequential_saved === 'yes'",section("原组序贯计划",DTOutput("ba_gs_plans",fill=FALSE)),section("停止路径",DTOutput("ba_stops",fill=FALSE)),section("停止资源",DTOutput("ba_resources",fill=FALSE)),section("所选轮次分析路径",DTOutput("ba_looks",fill=FALSE)),section("所选继续IA的CP诊断",selectInput("ba_cp_look","原继续IA",character()),numericInput("ba_cp_hr","假定未来HR",.7,min=.01,max=100),conditionalPanel("output.ba_nonbinding_z_saved === 'yes'",checkboxInput("ba_cp_respect","CP遵守原无效界",TRUE)),actionButton("ba_cp_run","计算诊断CP"),uiOutput("ba_cp_note"),DTOutput("ba_cp",fill=FALSE),downloadButton("ba_cp_download","CP CSV"),downloadButton("ba_cp_json","CP及原配置 JSON"))),conditionalPanel("output.ba_methods_saved === 'yes'",section("所选情景方法明细",DTOutput("ba_method_rows",fill=FALSE))))),
      batch_workspace_ui(),
      nav_panel("导出",value="ba_exports",
        conditionalPanel("output.ba_result_kind === 'calibration'",div(class="export-bar",downloadButton("ba_calibration_csv","校准参数 CSV"),downloadButton("ba_calibration_json","校准 JSON"))),
        conditionalPanel("output.ba_result_kind === 'batch'",p(class="field-note","导出保存的配置/结果，含失败、取消及尚未完成轮次。所选观察记录与真值分别下载。"),div(class="export-bar",
          downloadButton("ba_plan_download","情景计划 CSV"),downloadButton("ba_rows_download","主分析轮次 CSV"),downloadButton("ba_overview_download","主分析汇总 CSV"),downloadButton("ba_comparisons_download","参照情景 CSV"),downloadButton("ba_candidates_download","候选 CSV"),
          conditionalPanel("output.ba_sequential_saved === 'yes'",downloadButton("ba_gs_plans_download","原边界 CSV"),downloadButton("ba_looks_download","全部分析路径 CSV"),downloadButton("ba_stops_download","停止路径 CSV"),downloadButton("ba_resources_download","停止资源 CSV")),
          downloadButton("ba_method_rows_download","方法轮次 CSV"),downloadButton("ba_method_overview_download","方法汇总 CSV"),downloadButton("ba_method_pairs_download","配对方法 CSV"),
          downloadButton("ba_config_download","配置 JSON"),downloadButton("ba_result_download","结果 RDS"),downloadButton("ba_script_download","复现 R 脚本"),downloadButton("ba_report_download","统一报告 Markdown"),
          downloadButton("ba_observed_download","所选观察 CSV"),downloadButton("ba_adtte_download","所选 ADTTE CSV"),downloadButton("ba_truth_download","所选模拟真值 CSV"))))))
}
