register_expansion_two_help <- function(){h<-get("parameter_help",envir=parent.frame());extra<-c(
  ic_unit="日/周/月，默认月。年龄/时间/退出率和页面CSV同步换算；人数/q/事件目标不变。文件单位单独选择。",ic_transport="页面参数或本入口冻结配置JSON二选一；JSON模式不叠加页面参数。",ic_config_file="event_pred.ia_reverse.v1无损配置，≤5MB；可能含IA患者资料，只读参数和记录，不执行表达式。",ic_mode="一次反求一个变量，或用多个预定DCO期望计数联合校准2–3个未来变量。不是自由估计真实HR。",ic_source="汇总无事件年龄/人数无需文件；实际IA CSV或连续日ADTTE。永久退出不贡献未来事件。",ic_cut="当前IA研究经过时间，默认6月；active须确认至IA，不能静默补确认间隙。",ic_endpoint="选择单一PFS/OS；没有联合终点推断。",ic_ages="AGE,N CSV：仍无事件且仍随访年龄及人数，AGE从入组算、0至IA；正整数N。不同精确年龄保留，不自动分箱。",ic_known="IA已知累计事件D0，非负整数；已退出无事件者无需列入参数风险集。",ic_file="CSV严格USUBJID,ENTRY,AGE,STATUS；STATUS active/event/dropout。ADTTE需USUBJID,PARAMCD,CNSR和连续日ENGINE_ENTRY_DAY/TIME_DAY/OBS_DAY。",ic_file_unit="专用CSV ENTRY/AGE时间单位，与页面独立；ADTTE ENGINE字段固定日。",ic_group="ADTTE可指定一个TRTP值；留空为合并工作模型。未来q为共同风险调整，不是估计治疗HR。",ic_solve="单变量q/未来N/独立退出率/研究DCO四选一，其余量冻结。",ic_free="联合预定2–3个q、未来N、独立退出率；目标数至少自由度数，多个目标仍可能弱识别。",ic_q="IA后风险乘数q，0.001–100，默认1。累计风险差乘q，不回改历史事件或IA组成。",ic_future_n="IA后有限计划总新人数，非负整数，默认100；不是每组人数或不限人数Poisson过程。",ic_dropout="IA后共同独立指数退出风险，非负每当前单位，默认0.01每月；不估计已有退出机制。",ic_accrual="IA后有限新人数的均匀入组期，正，默认12月；入组起点是IA。",ic_dco="目标研究DCO从研究起点计时，IA之后，默认18月；不是额外随访年龄。",ic_target="目标期望累计观察事件数，含D0，可为非整数，默认100。不是保证事件数。",ic_tolerance="期望计数容许绝对偏差（事件），正，默认0.1；根残差和目标容差分别解释。",ic_bounds="parameter,lower,upper；q为倍数，future_n为人数，dropout_rate为每页面时间，dco为页面时间。单变量只一行，联合每自由度一行。边界在运行前冻结，不自动扩大。",ic_targets="DCO,target,weight,tolerance四列；DCO从研究起点算，递增且IA后。目标≥D0，正权重/容差。最多10目标，初始模板不是推荐设计。",ic_starts="联合确定性预定多起点1–7，默认3；都在归一化边界内，不调用随机种子。收敛不证明全局最优或唯一。",
  pn_unit="日/周/月，默认月；风险率/年龄/均匀入组期同步换算；状态人数/权重不变。",pn_transport="页面填写或event_pred.panel_model.v1冻结配置二选一。",pn_config_file="本入口typed配置JSON，≤5MB，可能含患者panel记录；不接受任意RDS。",pn_purpose="模型拟合/参考不读取未来计划；期望事件计数另读取未来入组/独立退出。没有预测区间、达标日期分布或正式适应检验。",pn_source="指定三常数转移率和汇总状态人数，或实际panel CSV联合拟合每组3个率。",pn_cut="当前IA研究经过时间，默认6月；活动患者末条需明确存活/状态确认至IA。",pn_file="七列USUBJID,GROUP,ENTRY,AGE,STATE,KIND,EXIT。每人基线AGE0/STATE0及末条；STATE 0/1/2/ALIVE，KIND panel/exact_death，末条EXIT active/dropout/event，中间followup。",pn_file_unit="CSV ENTRY/AGE单位，独立于页面；不会将区间中点视为实际转移日期。",pn_rates="GROUP,lambda01,lambda02,lambda12 CSV，三正风险率每当前单位。参数模式为给定模型，资料模式仅初值；组名须完全匹配。0→1进展/0→2直接死亡/1→2进展后死亡。",pn_states="GROUP,n0,n1,n2 CSV：IA无进展存活/已进展存活/死亡人数，非负整数。参数模式汇总状态，不伪造患者进展日期。",pn_reference="1–30个正递增风险年龄，例6,12,18月；参考PFS/OS从状态0起点，无入组/退出。",pn_future="GROUP,weight,dropout_rate CSV：未来分配正权重和共同组内独立退出率；已退出患者不恢复。",pn_new_n="有限未来总N，非负整数，默认100。各人IA后均匀入组，组概率按权重。",pn_accrual="IA后的均匀入组期，正，默认12月；不是从研究起点算。",pn_horizons="未来研究DCO，IA后正递增，例12,18,24月。输出模型期望；IA未确认进展补全单列，不称已报告事件。")
  h[names(extra)]<-extra;for(k in c("model","exp_basis","median","rate","shape","cuts","rates"))h[paste0("ic_",k)]<-h[paste0("rc_",k)];assign("parameter_help",h,envir=parent.frame())
}
e2_result_condition <- function(pre,k){if(pre=="pn_"){if(k=="count_overview")return("output.pn_saved_purpose === 'counts'");if(k %in% c("fit_diagnostics","filter_records"))return("output.pn_saved_source === 'data'");if(k=="current_states")return("output.pn_saved_source === 'data' || output.pn_saved_purpose === 'counts'")}else if(pre=="ic_"){if(k=="starts")return("output.ic_saved_mode === 'joint'");if(k=="rounded_constraints")return("output.ic_saved_has_n === 'yes'")};"true"}
e2_transport_ui <- function(pre,title){id<-function(k)paste0(pre,k);section("参数来源",radioButtons(id("transport"),"来源",c("填写页面"="ui","冻结配置JSON"="json"),inline=TRUE),conditionalPanel(paste0("input.",id("transport")," === 'json'"),fileInput(id("config_file"),title,accept=".json")))}
e2_export_ui <- function(pre,tables){id<-function(k)paste0(pre,k);section("导出",div(class="export-bar",lapply(names(tables),function(k)conditionalPanel(e2_result_condition(pre,k),downloadButton(id(paste0(k,"_download")),paste0(tables[[k]],"CSV")))),downloadButton(id("config_download"),"冻结配置JSON"),downloadButton(id("result_download"),"结果RDS"),downloadButton(id("report_download"),"报告Markdown"),downloadButton(id("script_download"),"匹配源码复现脚本")))}
ia_reverse_ui <- function(){tables<-c(overview="校准状态",solution="自由度解",constraints="目标偏差",rounded_constraints="人数取整后目标",identification="局部识别诊断",age_overview="冻结年龄人数",starts="起点结果",jacobian="局部Jacobian",trace="求解记录");nav_panel("IA期望事件反校准",value="ia_reverse",
  div(class="page-title",h2("基于IA风险集反求未来参数"),actionButton("ic_run","运行校准",class="btn-primary")),e2_transport_ui("ic_","IA校准配置JSON"),
  conditionalPanel("input.ic_transport === 'ui'",section("本次需求",fields(selectInput("ic_unit","时间单位",c("日"="days","周"="weeks","月"="months"),"months"),selectInput("ic_mode","校准",c("单变量反求"="single","多目标联合校准"="joint"))),fields(numericInput("ic_cut","IA研究时间（月）",6,min=0),selectInput("ic_endpoint","终点",c("PFS","OS"))),selectInput("ic_source","IA来源",c("汇总无事件年龄/人数"="parameters","IA专用CSV"="snapshot","连续日ADTTE"="adtte"))),
    conditionalPanel("input.ic_source === 'parameters'",section("IA风险集",textAreaInput("ic_ages","AGE,N（AGE为月）","AGE,N\n1,20\n3,40\n6,40",rows=5),numericInput("ic_known","IA已知事件D0",20,min=0,step=1))),
    conditionalPanel("input.ic_source !== 'parameters'",section("IA资料",fileInput("ic_file","IA资料CSV",accept=".csv"),conditionalPanel("input.ic_source === 'snapshot'",selectInput("ic_file_unit","文件时间单位",c("日"="days","周"="weeks","月"="months"),"months")),conditionalPanel("input.ic_source === 'adtte'",textInput("ic_group","TRTP值（留空合并）","")),downloadButton("ic_template","IA CSV模板"))),
    section("给定基准事件模型",r5_model_ui("ic_")),
    section("求解变量",conditionalPanel("input.ic_mode === 'single'",selectInput("ic_solve","反求",c("IA后风险倍数q"="q","未来计划N"="future_n","IA后退出率"="dropout_rate","研究DCO"="dco"))),conditionalPanel("input.ic_mode === 'joint'",checkboxGroupInput("ic_free","联合自由度",c("q"="q","未来N"="future_n","退出率"="dropout_rate"),c("q","future_n")),numericInput("ic_starts","预定起点数",3,min=1,max=7,step=1))),
    section("冻结未来过程",conditionalPanel("(input.ic_mode === 'single' && input.ic_solve !== 'q') || (input.ic_mode === 'joint' && input.ic_free && input.ic_free.indexOf('q') < 0)",numericInput("ic_q","IA后风险倍数q",1,min=.001,max=100)),conditionalPanel("(input.ic_mode === 'single' && input.ic_solve !== 'future_n') || (input.ic_mode === 'joint' && input.ic_free && input.ic_free.indexOf('future_n') < 0)",numericInput("ic_future_n","未来总计划N",100,min=0,step=1)),conditionalPanel("(input.ic_mode === 'single' && input.ic_solve !== 'dropout_rate') || (input.ic_mode === 'joint' && input.ic_free && input.ic_free.indexOf('dropout_rate') < 0)",numericInput("ic_dropout","IA后独立退出率（每月）",.01,min=0)),numericInput("ic_accrual","IA后均匀入组期（月）",12,min=.001)),
    conditionalPanel("input.ic_mode === 'single'",section("单目标",conditionalPanel("input.ic_solve !== 'dco'",numericInput("ic_dco","研究DCO（月）",18,min=.001)),fields(numericInput("ic_target","目标期望累计事件",100,min=0),numericInput("ic_tolerance","容许绝对事件偏差",.1,min=.000001)))),
    conditionalPanel("input.ic_mode === 'joint'",section("多目标",textAreaInput("ic_targets","DCO,target,weight,tolerance（DCO为月）","DCO,target,weight,tolerance\n12,80,1,1\n18,120,1,1",rows=4,width="100%"))),
    section("冻结求解范围",textAreaInput("ic_bounds","parameter,lower,upper","parameter,lower,upper\nq,0.1,5",rows=5,width="100%"))),
  uiOutput("ic_status"),plotOutput("ic_curve",height="300px"),lapply(names(tables),function(k)conditionalPanel(e2_result_condition("ic_",k),section(tables[[k]],DTOutput(paste0("ic_",k),fill=FALSE)))),e2_export_ui("ic_",c(tables,curve="期望曲线")))}
panel_multistate_ui <- function(){tables<-c(model_overview="转移风险率",fit_diagnostics="拟合/信息诊断",current_states="IA过滤状态",reference="联合生存参考",count_overview="期望事件数",filter_records="逐观察过滤记录");nav_panel("Panel多状态模型",value="panel_model",
  div(class="page-title",h2("访视状态的三状态Markov模型"),actionButton("pn_run","拟合/计算",class="btn-primary")),e2_transport_ui("pn_","Panel模型配置JSON"),
  conditionalPanel("input.pn_transport === 'ui'",section("本次需求",fields(selectInput("pn_unit","时间单位",c("日"="days","周"="weeks","月"="months"),"months"),selectInput("pn_purpose","需求",c("模型拟合/参考"="fit","条件期望事件数"="counts"))),selectInput("pn_source","来源",c("指定风险率/状态人数"="parameters","实际panel CSV联合拟合"="data")),conditionalPanel("input.pn_source === 'data' || input.pn_purpose === 'counts'",numericInput("pn_cut","IA研究时间（月）",6,min=0))),
    conditionalPanel("input.pn_source === 'data'",section("实际状态资料",fileInput("pn_file","Panel CSV",accept=".csv"),selectInput("pn_file_unit","文件时间单位",c("日"="days","周"="weeks","月"="months"),"months"),downloadButton("pn_template","Panel CSV模板"),p(class="field-note","USUBJID,GROUP,ENTRY,AGE,STATE,KIND,EXIT。ALIVE仅知存活；exact_death为精确死亡，其余panel。"))),
    section("转移模型",textAreaInput("pn_rates","GROUP,lambda01,lambda02,lambda12（每月，资料模式为初值）","GROUP,lambda01,lambda02,lambda12\nControl,0.05,0.02,0.04",rows=4,width="100%"),conditionalPanel("input.pn_source === 'parameters' && input.pn_purpose === 'counts'",textAreaInput("pn_states","GROUP,n0,n1,n2","GROUP,n0,n1,n2\nControl,100,30,20",rows=3,width="100%")),textInput("pn_reference","参考风险年龄（月）","6,12,18")),
    conditionalPanel("input.pn_purpose === 'counts'",section("未来计划",textAreaInput("pn_future","GROUP,weight,dropout_rate（每月）","GROUP,weight,dropout_rate\nControl,1,0.01",rows=3,width="100%"),fields(numericInput("pn_new_n","有限未来总N",100,min=0,step=1),numericInput("pn_accrual","IA后均匀入组期（月）",12,min=.001)),textInput("pn_horizons","未来研究DCO（月）","12,18,24")))),
  uiOutput("pn_status"),plotOutput("pn_curve",height="300px"),lapply(names(tables),function(k)conditionalPanel(e2_result_condition("pn_",k),section(tables[[k]],DTOutput(paste0("pn_",k),fill=FALSE)))),e2_export_ui("pn_",tables))}
