ic_input <- function(input) {
  u<-input$ic_unit %||% "months";f<-time_factor(u);cut<-input$ic_cut*f;mode<-input$ic_mode;free<-if(mode=="single")input$ic_solve else input$ic_free
  c<-list(source=if(input$ic_source=="parameters")"parameters" else "data",mode=mode,solve=if(mode=="single")input$ic_solve else NULL,free=if(mode=="joint")input$ic_free else NULL,cut=cut,paramcd=input$ic_endpoint,model=r5_model_input(input,"ic_",u),q=if("q" %in% free)1 else input$ic_q,future_n=if("future_n" %in% free)1L else input$ic_future_n,dropout_rate=if("dropout_rate" %in% free).01/f else input$ic_dropout/f,accrual_day=input$ic_accrual*f,display_unit=u,engine_unit="days",starts=if(mode=="joint")input$ic_starts else 1L)
  if(c$source=="parameters"){d<-r5_read_csv(input$ic_ages);if(!identical(names(d),c("AGE","N")))stop("年龄表AGE,N。");d$AGE<-d$AGE*f;c$age_counts<-d;c$known_events<-input$ic_known} else {if(is.null(input$ic_file))stop("提供本次IA资料CSV。");raw<-read.csv(input$ic_file$datapath,check.names=FALSE,stringsAsFactors=FALSE);c$data<-if(input$ic_source=="adtte")ic_from_adtte(raw,cut,c$paramcd,input$ic_group) else ic_snapshot(raw,cut,input$ic_file_unit);c$input_format<-input$ic_source;c$selected_group<-if(input$ic_source=="adtte")input$ic_group else ""}
  t<-if(mode=="single")data.frame(DCO=if(input$ic_solve=="dco")input$ic_cut+1 else input$ic_dco,target=input$ic_target,weight=1,tolerance=input$ic_tolerance) else r5_read_csv(input$ic_targets)
  if(!identical(names(t),c("DCO","target","weight","tolerance")))stop("目标表DCO,target,weight,tolerance。");t$DCO<-t$DCO*f;names(t)[1]<-"DCO_DAY";c$targets<-t
  b<-r5_read_csv(input$ic_bounds);if(!identical(names(b),c("parameter","lower","upper")))stop("范围表parameter,lower,upper。");if(any(b$parameter=="dropout_rate")){ix<-b$parameter=="dropout_rate";b[ix,c("lower","upper")]<-b[ix,c("lower","upper")]/f};if(any(b$parameter=="dco")){ix<-b$parameter=="dco";b[ix,c("lower","upper")]<-b[ix,c("lower","upper")]*f};c$bounds<-b;ic_validate(c);c
}
pn_input <- function(input) {
  u<-input$pn_unit %||% "months";f<-time_factor(u);purpose<-input$pn_purpose;cut<-if(input$pn_source=="parameters"&&purpose=="fit")0 else input$pn_cut*f;tab<-r5_read_csv(input$pn_rates)
  if(!identical(names(tab),c("GROUP","lambda01","lambda02","lambda12")))stop("风险表GROUP,lambda01,lambda02,lambda12。");tab[-1]<-lapply(tab[-1],function(x)x/f)
  c<-list(source=input$pn_source,purpose=purpose,cut=cut,rate_table=tab,reference_ages=parse_unit_numbers(input$pn_reference)*f,display_unit=u,engine_unit="days")
  if(c$source=="data"){if(is.null(input$pn_file))stop("请提供panel状态CSV。");c$data<-pn_snapshot(read.csv(input$pn_file$datapath,check.names=FALSE,stringsAsFactors=FALSE),cut,input$pn_file_unit)}else if(purpose=="counts")c$state_counts<-r5_read_csv(input$pn_states)
  if(purpose=="counts"){p<-r5_read_csv(input$pn_future);if(!identical(names(p),c("GROUP","weight","dropout_rate")))stop("未来表GROUP,weight,dropout_rate。");p$dropout_rate<-p$dropout_rate/f;c$future_table<-p;c$new_n<-input$pn_new_n;c$accrual_day<-input$pn_accrual*f;c$horizons<-parse_unit_numbers(input$pn_horizons)*f}
  pn_validate(c);c
}
e2_read_config <- function(file,schema) {
  if(is.null(file))stop("先选择本入口冻结配置JSON。");if(file.info(file$datapath)$size>5*1024^2)stop("配置最多5MB。")
  d<-jsonlite::read_json(file$datapath,simplifyVector=FALSE);if(!identical(d$schema,schema))stop("配置所属需求入口不符。");c<-batch_decode_tree(d$exact_config);if(!identical(batch_config_hash(c),d$configuration_hash))stop("冻结配置摘要不符。");c
}
e2_display_table <- function(d,c) {
  if(!is.data.frame(d))return(data.frame());f<-time_factor(c$display_unit);label<-time_label(c$display_unit)
  for(k in intersect(c("DCO_DAY","AGE_DAY","ENTRY","AGE"),names(d))){d[[k]]<-d[[k]]/f;names(d)[names(d)==k]<-paste0(k,"（",label,"）")}
  if("dropout_rate" %in% names(d)){d$dropout_rate<-d$dropout_rate*f;names(d)[names(d)=="dropout_rate"]<-paste0("dropout_rate（每",label,"）")}
  if("call" %in% names(d)&&"value" %in% names(d)&&identical(c$mode,"single")){if(c$solve=="dropout_rate")d$value<-d$value*f else if(c$solve=="dco")d$value<-d$value/f}
  if("rate_per_day" %in% names(d)){d$rate_per_day<-d$rate_per_day*f;names(d)[names(d)=="rate_per_day"]<-paste0("risk_rate（每",label,"）")}
  if(all(c("parameter","value","unit","lower","upper") %in% names(d)))for(i in seq_len(nrow(d))){if(d$unit[i]=="days"){d[i,c("value","lower","upper")]<-d[i,c("value","lower","upper")]/f;d$unit[i]<-label}else if(d$unit[i]=="per_day"){d[i,c("value","lower","upper")]<-d[i,c("value","lower","upper")]*f;d$unit[i]<-paste0("每",label)}}
  d
}
e2_register_result <- function(input,output,session,pre,schema,builder,runner,reporter,tables) {
  id<-function(k)paste0(pre,k);saved<-reactiveVal(NULL);error<-reactiveVal(NULL)
  observeEvent(input[[id("run")]],{error(NULL);tryCatch({c<-if(input[[id("transport")]]=="json")e2_read_config(input[[id("config_file")]],schema) else builder(input);r<-runner(c);saved(r)},error=function(e)error(conditionMessage(e)))},ignoreInit=TRUE)
  output[[id("status")]]<-renderUI(tagList(if(!is.null(error()))p(class="field-note",error()),if(!is.null(saved()))p(class="field-note",paste0("已保存本次冻结配置结果；v",saved()$version,"开发稿待复核。",if(pre=="pn_")"常数Markov工作模型，输出期望数。" else "未来参数规划校准，不是HR估计。"))))
  for(k0 in names(tables))local({k<-k0;output[[id(k)]]<-renderDT({r<-saved();req(r);study_table(e2_display_table(r[[k]],r$config))});output[[id(paste0(k,"_download"))]]<-downloadHandler(filename=paste0(pre,k,"_days.csv"),content=function(file){r<-saved();req(r);write.csv(r[[k]],file,row.names=FALSE)})})
  output[[id("config_download")]]<-downloadHandler(filename=paste0(pre,"frozen_config.json"),content=function(file){r<-saved();req(r);jsonlite::write_json(list(schema=schema,version=r$version,configuration_hash=batch_config_hash(r$config),exact_config=batch_encode_tree(r$config)),file,auto_unbox=TRUE,pretty=TRUE,digits=NA)})
  output[[id("result_download")]]<-downloadHandler(filename=paste0(pre,"result_draft.rds"),content=function(file){r<-saved();req(r);saveRDS(r,file,version=3)})
  output[[id("report_download")]]<-downloadHandler(filename=paste0(pre,"report_draft.md"),content=function(file){r<-saved();req(r);writeLines(reporter(r),file,useBytes=TRUE)})
  output[[id("script_download")]]<-downloadHandler(filename=paste0(pre,"replay_draft.R"),content=function(file){r<-saved();req(r);dump<-function(x)paste(capture.output(dput(x,control=c("keepNA","keepInteger","niceNames","showAttributes","hexNumeric"))),collapse="\n");runname<-if(pre=="ic_")"run_ia_reverse_calibration" else "run_panel_multistate";writeLines(c("# Draft; may include frozen patient records. No replay validation performed.",'source("R/research_sources.R")',paste0("cfg <- ",dump(r$config)),paste0('if(batch_version!="',r$version,'" || batch_source_hash()!="',r$source_hash,'")stop("Source/version differs")'),paste0("expected_dependencies <- ",dump(r$dependencies)),'if(!identical(batch_dependencies(list()),expected_dependencies))stop("Dependencies differ")',paste0("result <- ",runname,"(cfg)"),'saveRDS(result,"replayed_result.rds")',vapply(names(tables),function(k)paste0('write.csv(result$',k,',"replayed_',pre,k,'.csv",row.names=FALSE)'),character(1))),file,useBytes=TRUE)})
  saved
}
register_expansion_two_server <- function(input,output,session) {
  register_r5_units(input,session,"ic_");round_four_units(input,session,"ic_",list(duration=c(ic_cut="IA研究时间")))
  round_four_units(input,session,"pn_",list(duration=c(pn_cut="IA研究时间",pn_accrual="IA后均匀入组期"),duration_text=c(pn_reference="参考风险年龄",pn_horizons="未来研究DCO")))
  previous_ic<-reactiveVal("months");observeEvent(input$ic_unit,{to<-input$ic_unit;from<-previous_ic();if(to==from)return();ratio<-time_factor(from)/time_factor(to)
    for(k in c("ages","targets","bounds")){value<-isolate(input[[paste0("ic_",k)]]);if(is.null(value))next;new<-tryCatch({d<-r5_read_csv(value);if(k=="ages")d$AGE<-d$AGE*ratio else if(k=="targets")d$DCO<-d$DCO*ratio else {for(p in c("dropout_rate","dco")){ix<-d$parameter==p;d[ix,c("lower","upper")]<-d[ix,c("lower","upper")]*if(p=="dco")ratio else 1/ratio}};r5_csv_text(d)},error=function(e)value);freezeReactiveValue(input,paste0("ic_",k));updateTextAreaInput(session,paste0("ic_",k),label=parameter_label(paste0("ic_",k),switch(k,ages=paste0("AGE,N（AGE为",time_label(to),"）"),targets=paste0("DCO,target,weight,tolerance（DCO为",time_label(to),"）"),bounds=paste0("parameter,lower,upper（时间为",time_label(to),"；率为每",time_label(to),"）"))),value=new)};previous_ic(to)},ignoreInit=TRUE)
  previous_pn<-reactiveVal("months");observeEvent(input$pn_unit,{to<-input$pn_unit;from<-previous_pn();if(to==from)return();ratio<-time_factor(from)/time_factor(to);for(k in c("rates","future")){id<-paste0("pn_",k);v<-isolate(input[[id]]);new<-tryCatch({d<-r5_read_csv(v);if(k=="rates")d[-1]<-lapply(d[-1],function(x)x/ratio) else d$dropout_rate<-d$dropout_rate/ratio;r5_csv_text(d)},error=function(e)v);freezeReactiveValue(input,id);updateTextAreaInput(session,id,label=parameter_label(id,if(k=="rates")paste0("GROUP,lambda01,lambda02,lambda12（每",time_label(to),"）") else paste0("GROUP,weight,dropout_rate（每",time_label(to),"）")),value=new)};previous_pn(to)},ignoreInit=TRUE)
  old_free<-reactiveVal(NULL);observeEvent(list(input$ic_mode,input$ic_solve,input$ic_free),{free<-if(input$ic_mode=="single")input$ic_solve else input$ic_free;if(identical(free,old_free())||!length(free))return();old_free(free);f<-time_factor(isolate(input$ic_unit));b<-batch_bind_columns(lapply(free,function(k){v<-switch(k,q=c(.1,5),future_n=c(0,1000),dropout_rate=c(0,.2/time_factor("months")*f),dco=c(isolate(input$ic_cut)+.1,min(3650/f,isolate(input$ic_cut)+36*time_factor("months")/f)));data.frame(parameter=k,lower=v[1],upper=v[2])}));updateTextAreaInput(session,"ic_bounds",value=r5_csv_text(b))},ignoreInit=FALSE)
  ic<-e2_register_result(input,output,session,"ic_","event_pred.ia_reverse.v1",ic_input,run_ia_reverse_calibration,ic_report,c(overview="校准状态",solution="自由度解",constraints="目标偏差",rounded_constraints="人数取整后",identification="识别诊断",age_overview="年龄人数",starts="起点",jacobian="Jacobian",trace="轨迹",curve="曲线"))
  pn<-e2_register_result(input,output,session,"pn_","event_pred.panel_model.v1",pn_input,run_panel_multistate,pn_report,c(model_overview="风险率",fit_diagnostics="拟合诊断",current_states="当前状态",reference="参考",count_overview="期望计数",filter_records="过滤记录"))
  output$ic_curve<-renderPlot({r<-ic();req(r);f<-time_factor(r$config$display_unit);plot(r$curve$DCO_DAY/f,r$curve$expected,type="l",lwd=2,xlab=paste0("研究时间（",time_label(r$config$display_unit),"）"),ylab="期望累计观察事件");points(r$constraints$DCO_DAY/f,r$constraints$target,pch=19,col="#bc5b3a")})
  output$pn_curve<-renderPlot({r<-pn();req(r);d<-r$reference;f<-time_factor(r$config$display_unit);plot(range(d$AGE_DAY/f),c(0,1),type="n",xlab=paste0("风险年龄（",time_label(r$config$display_unit),"）"),ylab="S(t)");g<-unique(d$GROUP);for(j in seq_along(g)){x<-d[d$GROUP==g[j],];lines(x$AGE_DAY/f,x$PFS_survival,col=j,lwd=2);lines(x$AGE_DAY/f,x$OS_survival,col=j,lwd=2,lty=2)};legend("topright",legend=c(paste(g,"PFS"),paste(g,"OS")),col=rep(seq_along(g),2),lty=rep(c(1,2),each=length(g)),bty="n")})
  output$pn_saved_source<-renderText(if(is.null(pn()))"" else pn()$config$source);outputOptions(output,"pn_saved_source",suspendWhenHidden=FALSE)
  output$ic_saved_mode<-renderText(if(is.null(ic()))"" else ic()$config$mode);outputOptions(output,"ic_saved_mode",suspendWhenHidden=FALSE)
  output$ic_saved_has_n<-renderText(if(!is.null(ic())&&"future_n" %in% ic()$solution$parameter)"yes" else "no");outputOptions(output,"ic_saved_has_n",suspendWhenHidden=FALSE)
  output$pn_saved_purpose<-renderText(if(is.null(pn()))"" else pn()$config$purpose);outputOptions(output,"pn_saved_purpose",suspendWhenHidden=FALSE)
  output$ic_template<-downloadHandler(filename="ia_snapshot_months.csv",content=function(file)write.csv(data.frame(USUBJID=c("P01","P02","P03","P04"),ENTRY=c(0,3,1,2),AGE=c(6,3,4,2),STATUS=c("active","active","event","dropout")),file,row.names=FALSE))
  output$pn_template<-downloadHandler(filename="panel_records_months.csv",content=function(file)write.csv(data.frame(USUBJID=rep(paste0("P0",1:6),each=3),GROUP="Control",ENTRY=0,AGE=rep(c(0,3,6),6),STATE=c("0","0","ALIVE","0","1","1","0","0","2","0","ALIVE","ALIVE","0","1","2","0","0","0"),KIND=c(rep("panel",8),"exact_death",rep("panel",9)),EXIT=c("followup","followup","active","followup","followup","active","followup","followup","event","followup","followup","active","followup","followup","event","followup","followup","active")),file,row.names=FALSE))
  invisible(list(ia_reverse=ic,panel=pn))
}
