# Proper cumulative-hazard splines. Neither model is the existing log-hazard ns model.
fs_rp_locations <- function(m)log(c(m$lower,m$knots,m$tail)/m$time_scale)
fs_rp_basis <- function(m,x,derivative=FALSE){loc<-fs_rp_locations(m);l<-loc[1];r<-tail(loc,1);k<-loc[-c(1,length(loc))];basis<-matrix(0,length(x),length(k));if(length(k))for(j in seq_along(k)){power<-if(derivative)2 else 3;factor<-if(derivative)3 else 1;basis[,j]<-factor*(pmax(x-k[j],0)^power-(r-k[j])/(r-l)*pmax(x-l,0)^power-(k[j]-l)/(r-l)*pmax(x-r,0)^power)/(r-l)^2};if(derivative)cbind(0,1,basis) else cbind(1,x,basis)}
fs_rp_min_slope <- function(m){loc<-fs_rp_locations(m);points<-loc;for(j in seq_len(length(loc)-1L)){l<-loc[j];r<-loc[j+1];mid<-(l+r)/2;v<-as.numeric(fs_rp_basis(m,c(l,mid,r),TRUE)%*%m$params);w<-r-l;a<-2*(v[3]+v[1]-2*v[2])/w^2;b<-(v[3]-v[1])/w-a*w;if(a>0){u<--b/(2*a);if(u>0&&u<w)points<-c(points,l+u)}};slopes<-as.numeric(fs_rp_basis(m,points,TRUE)%*%m$params);list(min=min(slopes),points=points,slopes=slopes)}
fs_valid <- function(m){if(!is.numeric(m$params)||any(!is.finite(m$params))||!is.numeric(m$knots)||length(m$knots)>6||any(!is.finite(m$knots)|m$knots<=0)||is.unsorted(m$knots,strictly=TRUE)||!is.finite(m$tail)||m$tail<=max(c(0,m$knots)))return(FALSE);if(m$id=="rp_hazard")return(length(m$params)==length(m$knots)+2&&is.finite(m$lower)&&m$lower>0&&m$lower<min(c(m$tail,m$knots))&&is.finite(m$time_scale)&&m$time_scale>0&&fs_rp_min_slope(m)$min>0);if(m$id=="ispline_hazard")return(length(m$params)==length(m$knots)+5&&all(m$params>= -30&m$params<=30));FALSE}
fs_is_knots <- function(m)c(rep(0,4L),m$knots,rep(m$tail,4L))
fs_m_basis <- function(m,t){K<-fs_is_knots(m);n<-length(K)-4L;out<-matrix(0,length(t),n);ix<-which(t>=0&t<m$tail);if(length(ix)){B<-splines::splineDesign(K,t[ix],ord=4L,outer.ok=TRUE);den<-K[seq_len(n)+4L]-K[seq_len(n)];out[ix,]<-sweep(B,2,4/den,"*")};out}
fs_i_basis <- function(m,t){n<-length(m$knots)+4L;nodes<-c(-.8611363115940526,-.3399810435848563,.3399810435848563,.8611363115940526);w<-c(.3478548451374539,.6521451548625461,.6521451548625461,.3478548451374539);calc<-function(age){if(age<=0)return(rep(0,n));end<-min(age,m$tail);cuts<-sort(unique(c(0,m$knots[m$knots<end],end)));v<-rep(0,n);for(j in seq_len(length(cuts)-1L)){l<-cuts[j];r<-cuts[j+1L];x<-(l+r)/2+(r-l)/2*nodes;v<-v+(r-l)/2*colSums(fs_m_basis(m,x)*w)};v};if(!length(t))return(matrix(numeric(),0,n));do.call(rbind,lapply(t,calc))}
fs_cumhaz <- function(m,t){t<-pmax(t,0);if(m$id=="rp_hazard"){v<-rep(0,length(t));ix<-which(t>0);if(length(ix))v[ix]<-exp(as.numeric(fs_rp_basis(m,log(t[ix]/m$time_scale))%*%m$params));return(v)};exp(m$params[1])*t+as.numeric(fs_i_basis(m,t)%*%exp(m$params[-1]))}
fs_logdensity <- function(m,t){if(m$id=="rp_hazard"){out<-rep(-Inf,length(t));ix<-which(t>0);if(length(ix)){x<-log(t[ix]/m$time_scale);eta<-as.numeric(fs_rp_basis(m,x)%*%m$params);d<-as.numeric(fs_rp_basis(m,x,TRUE)%*%m$params);out[ix]<-ifelse(d>0,eta+log(d)-log(t[ix])-exp(eta),-Inf)};return(out)};h<-exp(m$params[1])+as.numeric(fs_m_basis(m,t)%*%exp(m$params[-1]));log(h)-fs_cumhaz(m,t)}
fs_model_vector <- function(v,id,cfg){list(id=id,label=if(id=="rp_hazard")"Royston-Parmar log累计风险（全区间单调约束）" else "正系数I-spline累计风险+正线性尾",params=v,knots=cfg$knots,tail=cfg$tail,lower=cfg$rp_lower %||% min(c(cfg$knots,cfg$tail))/10,time_scale=cfg$time_scale)}
fs_fit_rp <- function(d,cfg){if(sum(d$TYPE!="right")<2)stop("RP拟合至少2条已知事件。");n<-length(cfg$knots)+2L;ages<-ifelse(d$TYPE=="right",d$L,d$R);rate<-sum(d$TYPE!="right")/max(sum(ages),1);initial<-c(log(rate*cfg$time_scale),1,rep(0,n-2L));lower<-c(-30,.02,rep(-10,n-2L));upper<-c(20,8,rep(10,n-2L));initial<-pmin(pmax(initial,lower+.01),upper-.01);skeleton<-fs_model_vector(initial,"rp_hazard",cfg);loc<-fs_rp_locations(skeleton);points<-sort(unique(c(loc,seq(min(loc),max(loc),length.out=41))));objective<-function(v){m<-fx_wrap_blind(fs_model_vector(v,"rp_hazard",cfg),cfg);ll<-tryCatch(fx_record_loglik(m,d),error=function(e)rep(-Inf,nrow(d)));if(any(!is.finite(ll)))1e100 else -sum(ll)};start<-initial;fit<-NULL
  for(iter in seq_len(12L)){rows<-fs_rp_basis(skeleton,points,TRUE);ui<-rbind(rows,diag(n),-diag(n));ci<-c(rep(1e-6,nrow(rows)),lower,-upper);# Move toward strictly feasible Weibull start before adding a new cutting plane.
    blend<-0;while(any(as.numeric(ui%*%start-ci)<=1e-8)){blend<-if(blend==0).01 else blend*2;if(blend>=1){start<-initial;break};start<-(1-blend)*start+blend*initial};fit<-constrOptim(start,objective,grad=NULL,ui=ui,ci=ci,method="Nelder-Mead",control=list(maxit=4000,reltol=1e-9),outer.iterations=20L);if(fit$convergence!=0||!is.finite(fit$value)||fit$value>=1e99)stop("RP约束似然未获得收敛有限解。");m<-fs_model_vector(fit$par,"rp_hazard",cfg);v<-fs_rp_min_slope(m);if(v$min>=1e-6){base<-fx_wrap_blind(m,cfg);base$loglik<--fit$value;base$parameter_count<-n;base$aic<-2*n+2*fit$value;base$fit_id<-"rp_hazard";base$constraint_note<-"每个自然三次片段导数端点/顶点及两个线性尾均正；切平面约束拟合";return(base)};points<-sort(unique(c(points,v$points[v$slopes<1e-6])));start<-fit$par}
  stop("RP全域单调约束未完成；不接受仅在网格上单调的模型。")}
fs_fit_i <- function(d,cfg){if(sum(d$TYPE!="right")<2)stop("I-spline拟合至少2条已知事件。");n<-length(cfg$knots)+5L;ages<-ifelse(d$TYPE=="right",d$L,d$R);rate<-sum(d$TYPE!="right")/max(sum(ages),1);initial<-c(log(rate),rep(log(.1),n-1L));objective<-function(v){m<-fx_wrap_blind(fs_model_vector(v,"ispline_hazard",cfg),cfg);ll<-tryCatch(fx_record_loglik(m,d),error=function(e)rep(-Inf,nrow(d)));if(any(!is.finite(ll)))1e100 else -sum(ll)};fit<-optim(initial,objective,method="L-BFGS-B",lower=c(-25,rep(-20,n-1L)),upper=c(5,rep(10,n-1L)),control=list(maxit=1500L));if(fit$convergence!=0||!is.finite(fit$value)||fit$value>=1e99)stop("I-spline似然未获得收敛有限解。");if(any(fit$par<=c(-25,rep(-20,n-1L))+1e-5|fit$par>=c(5,rep(10,n-1L))-1e-5))stop("I-spline参数到达数值边界，不接受该拟合。");m<-fx_wrap_blind(fs_model_vector(fit$par,"ispline_hazard",cfg),cfg);m$loglik<--fit$value;m$parameter_count<-n;m$aic<-2*n+2*fit$value;m$fit_id<-"ispline_hazard";m}
