# Shared controls with fixed/calendar or stage-specific event targets; stage2 is new patients only.
ma_is <- function(cfg)identical(cfg$research_family,"multiarm_independent_design")
ma_names <- c(design="预定多臂设计")
ma_scenarios <- function(cfg){d<-cfg$scenario_table;arms<-cfg$arms$arm[cfg$arms$arm!="Control"];keys<-c("label",paste0("hr_",arms),if(cfg$design=="two_in_one")paste0("prog_",arms));if(!is.data.frame(d)||!identical(sort(names(d)),sort(keys))||!nrow(d)||nrow(d)>24||anyNA(d)||anyDuplicated(d$label)||any(!nzchar(d$label)))stop(paste0("情景严格列：",paste(keys,collapse=","),"；1–24行、唯一名称。"));for(k in setdiff(keys,"label"))if(!is.numeric(d[[k]])||any(!is.finite(d[[k]])|d[[k]]<.05|d[[k]]>5))stop("各臂HR及进展风险倍数0.05–5。");d$SCENARIO<-seq_len(nrow(d));d}
ma_validate_model <- function(m){p<-m$params;if(!is.numeric(p)||any(!is.finite(p)))stop("模型参数必须有限。");if(m$id=="exponential"&&(length(p)!=1||p[1]<=0)||m$id=="weibull"&&(length(p)!=2||p[2]<=0)||m$id %in% c("lognormal","loglogistic")&&(length(p)!=2||p[2]<=0)||m$id=="gompertz"&&(length(p)!=2||p[1]<=0))stop("事件分布参数无效。");if(m$id=="pwe"){parameter_model("pwe",list(rates=p),m$cuts);if(tail(p,1)<=0)stop("分段指数末段风险需正。")};invisible(TRUE)}
ma_integer <- function(x,lo,hi)is.numeric(x)&&length(x)==1&&is.finite(x)&&x==floor(x)&&x>=lo&&x<=hi
ma_scalar <- function(x,lo,hi)is.numeric(x)&&length(x)==1&&is.finite(x)&&x>=lo&&x<=hi
validate_multiarm <- function(cfg){if(!ma_is(cfg)||!cfg$design %in% c("final","selected","two_in_one")||!cfg$test %in% c("logrank","landmark_exact","cox_wald")||!cfg$multiplicity %in% c("bonferroni","holm","dunnett","closed_dunnett")||!cfg$confirmation %in% c("combination","stage2"))stop("选择多臂一次Final、独立两阶段或PFS筛选/OS确认，以及检验与多重性规则。");if(!mx_rule(cfg) %in% c("fixed","target"))stop("多臂规则为固定日历或事件目标。");if(mx_rule(cfg)=="target"){if(cfg$test=="landmark_exact")stop("事件驱动只用渐近log-rank/Cox，不把完整landmark检验用于事件停止。");if(!ma_integer(cfg$event_d1,1,100000)||cfg$design!="final"&&!ma_integer(cfg$event_d2,1,100000))stop("预定阶段目标为1–100000事件整数。")};if(cfg$multiplicity %in% c("dunnett","closed_dunnett")&&cfg$test!="cox_wald")stop("Dunnett型相关正态使用联合Cox Wald，不为普通log-rank编造独立相关矩阵。");if(cfg$multiplicity=="dunnett"&&cfg$design!="final")stop("单步Dunnett仅一次Final；选臂两阶段使用闭合交集。");if(isTRUE(cfg$interval_enabled)&&(cfg$test!="cox_wald"||!ma_scalar(cfg$interval_alpha,.0001,.2)))stop("适应后组合近似区间限Cox PH，家族区间alpha0.0001–0.2。");if(!ma_integer(cfg$dunnett_steps %||% 128L,32,512))stop("Miwa网格点32–512整数。");a<-cfg$arms;if(!is.data.frame(a)||!identical(sort(names(a)),sort(c("arm","weight","dropout_rate")))||nrow(a)<2||nrow(a)>6||anyNA(a)||anyDuplicated(a$arm)||a$arm[1]!="Control"||any(!grepl("^[A-Za-z][A-Za-z0-9_]{0,20}$",a$arm))||any(!is.finite(a$weight)|a$weight<=0)||any(!is.finite(a$dropout_rate)|a$dropout_rate<0))stop("组表三列arm,weight,dropout_rate；首行为Control，1–5试验臂，权重正、退出率非负，名称限英文数字下划线。");if(!cfg$control_model$id %in% c("exponential","weibull","pwe","lognormal","loglogistic","gompertz"))stop("多臂基准支持指数/Weibull/PWE/lognormal/loglogistic/Gompertz。");ma_validate_model(cfg$control_model)
  if(!ma_integer(cfg$n1,20,3000)||!ma_integer(cfg$n2,20,3000)||!ma_scalar(cfg$enroll_rate,1e-8,1e5)||!ma_scalar(cfg$stage1_day,1e-6,3650)||!ma_scalar(cfg$max_day,cfg$stage1_day,3650)||!ma_scalar(cfg$landmark_age,1e-6,3650)||!ma_scalar(cfg$alpha,.0001,.2)||!ma_scalar(cfg$w1,.01,.99)||!ma_scalar(cfg$screen_p,.0001,1)||!ma_integer(cfg$select_k,1,nrow(a)-1))stop("N1/N2为20–3000整数，入组率正；阶段日期≤3650日，alpha0.0001–0.2，权重/筛选阈值与保留臂数合法。");if(cfg$design!="final"&&cfg$stage1_day>=cfg$max_day)stop("两阶段Final须晚于Stage1。");if(cfg$test=="landmark_exact"&&any(a$dropout_rate>0))stop("精确landmark检验要求无永久退出；未完整随访的比较预定不拒绝，不删除患者。");if(cfg$design=="two_in_one"&&(!ma_scalar(cfg$progression_rate,1e-10,1e5)||!ma_scalar(cfg$death_rate,1e-10,1e5)))stop("2-in-1使用指数进展和状态无关指数死亡，两风险率须正。");if(!ma_integer(cfg$reps,20,3000)||!ma_integer(cfg$seed,0,.Machine$integer.max))stop("B20–3000，种子非负整数。");sc<-ma_scenarios(cfg);if(sum(rep(cfg$n1+if(cfg$design=="final")0 else cfg$n2,nrow(sc)))*cfg$reps>1e7)stop("患者×轮次上限1000万。");time_factor(cfg$display_unit);if(is.na(as.Date(cfg$origin))||!cfg$paramcd %in% c("PFS","OS"))stop("日期或单终点标签无效。");invisible(TRUE)}
ma_group_n <- function(n,arms){w<-arms$weight/sum(arms$weight);v<-floor(n*w);left<-n-sum(v);if(left>0)v[order(-(n*w-v),seq_along(v))[seq_len(left)]]<-v[order(-(n*w-v),seq_along(v))[seq_len(left)]]+1L;if(any(v<2))stop("预定配额每组至少2人，请提高N或调整权重。");setNames(v,arms$arm)}
ma_generate_stage <- function(cfg,sc,b,stage,selected=character()){a<-cfg$arms;if(stage==2)a<-a[a$arm %in% c("Control",selected),,drop=FALSE];n<-if(stage==1)cfg$n1 else cfg$n2;counts<-ma_group_n(n,a);group<-sample(rep(names(counts),counts));entry<-cumsum(rexp(n,cfg$enroll_rate))+if(stage==2)cfg$stage1_day else 0;id<-sprintf("MA%04d-S%d-%05d",b,stage,seq_len(n));event<-pfs<-os<-drop<-rep(Inf,n)
  for(g in names(counts)){ix<-which(group==g);hr<-if(g=="Control")1 else sc[[paste0("hr_",g)]];mu<-a$dropout_rate[match(g,a$arm)];if(mu>0)drop[ix]<-rexp(length(ix),mu)
    if(cfg$design=="two_in_one"){qp<-if(g=="Control")1 else sc[[paste0("prog_",g)]];pr<-rexp(length(ix),cfg$progression_rate*qp);de<-rexp(length(ix),cfg$death_rate*hr);pfs[ix]<-pmin(pr,de);os[ix]<-de;event[ix]<-de}
    else {event[ix]<-inverse_cumhaz(cfg$control_model,rexp(length(ix))/hr);pfs[ix]<-os[ix]<-event[ix]}
  };data.frame(SIMID=b,USUBJID=id,group=group,COHORT=stage,entry_day=entry,event_time_day=event,event_day=entry+event,dropout_time_day=drop,dropout_day=entry+drop,pfs_time_day=pfs,os_time_day=os)
}
ma_observe <- function(t,day,endpoint){z<-t;z$event_time_day<-if(endpoint=="PFS")z$pfs_time_day else z$os_time_day;z$event_day<-z$entry_day+z$event_time_day;o<-survival_at_cut(z,day);o$PARAMCD<-endpoint;o$COHORT<-z$COHORT[match(o$USUBJID,z$USUBJID)];o}
ma_test <- function(o,truth,arm,cfg,day){x<-o[o$group %in% c("Control",arm),,drop=FALSE];empty<-list(p=1,z=-Inf,performed=FALSE,note="信息不足，预定p=1且不拒绝。",n=nrow(x),events=sum(x$event));if(length(unique(x$group))<2)return(empty)
  if(cfg$test=="landmark_exact"){planned<-truth[truth$group %in% c("Control",arm),];if(any(planned$entry_day+cfg$landmark_age>day)){empty$note<-"预定队列未全部完成landmark随访，整项比较p=1；不删除未成熟患者。";return(empty)};if(any(x$status=="dropout"&x$time_day<cfg$landmark_age))stop("landmark不可有早期退出。");alive<-x$time_day>=cfg$landmark_age & !(x$event==1&x$time_day<=cfg$landmark_age);tab<-rbind(c(sum(alive&x$group==arm),sum(!alive&x$group==arm)),c(sum(alive&x$group=="Control"),sum(!alive&x$group=="Control")));p<-stats::fisher.test(tab,alternative="greater")$p.value
  }else {a<-study_logrank(x$time_day,x$event,as.integer(x$group==arm));if(!is.finite(a$variance)||a$variance<=0)return(empty);p<-pnorm(a$score/sqrt(a$variance))};list(p=p,z=qnorm(p,lower.tail=FALSE),performed=TRUE,note=if(cfg$test=="logrank")"普通log-rank正态近似；不是有限样本精确检验。" else "固定年龄生存二项比例的单侧Fisher精确检验。",n=nrow(x),events=sum(x$event))
}
ma_combine <- function(p1,p2,w){# Preserve p=1 as a conservative absorbing value; no favorable clipping.
  if(p1>=1||p2>=1)return(1);if(p1<=0||p2<=0)return(0);pnorm(w*qnorm(p1,lower.tail=FALSE)+sqrt(1-w^2)*qnorm(p2,lower.tail=FALSE),lower.tail=FALSE)
}
ma_trial_core <- function(cfg,sc,b,keep_sample=FALSE)mx_trial_core(cfg,sc,b,keep_sample)

ma_trial <- function(cfg,sc,b,prepared=NULL,keep_sample=FALSE)batch_with_rng(batch_replicate_seed(cfg$seed,sc$SCENARIO,b),tryCatch(ma_trial_core(cfg,sc,b,keep_sample),error=function(e)list(row=data.frame(SCENARIO=sc$SCENARIO,SIMID=b,replicate_seed=batch_replicate_seed(cfg$seed,sc$SCENARIO,b),generated=FALSE,decision_valid=FALSE,decision_reject=NA,fwer=NA,any_claim=NA,all_active_claim=NA,note=conditionMessage(e)),method_rows=data.frame(SCENARIO=sc$SCENARIO,SIMID=b,method="design",generated=FALSE,decision_valid=FALSE,decision_reject=NA,fwer=NA,any_claim=NA,all_active_claim=NA,action="failure"),looks=data.frame(),draw_rows=data.frame())))
ma_aggregate <- function(s){s<-research_aggregate(s,"design",ma_names,c("decision_reject","fwer","any_claim","all_active_claim"));d<-s$draw_rows;if(nrow(d)&&"record_kind" %in% names(d))d<-d[!is.na(d$record_kind)&d$record_kind=="arm_claim",,drop=FALSE];s$arm_overview<-data.frame();if(nrow(d))s$arm_overview<-batch_bind_columns(lapply(split(d,paste(d$SCENARIO,d$arm)),function(x)cbind(data.frame(SCENARIO=x$SCENARIO[1],arm=x$arm[1],true_null=x$true_null[1],metric="arm_claim"),jr_probability(x$reject,s$config$reps),selection_probability=sum(x$selected)/s$config$reps)));mx_attach(s)}
run_multiarm <- function(cfg,progress=function(s)NULL,should_cancel=function()FALSE,replay_keys=NULL,resume_state=NULL,continuation_operation="resume"){validate_multiarm(cfg);research_family_run(cfg,ma_scenarios(cfg),ma_trial,ma_aggregate,progress,should_cancel,replay_keys,resume_state,continuation_operation)}
ma_initial <- function(cfg,initial=NULL)research_initial(cfg,ma_scenarios(cfg),ma_aggregate,initial)
ma_sample <- function(r,scenario,replicate)ma_trial(r$config,r$scenarios[r$scenarios$SCENARIO==scenario,,drop=FALSE],replicate,NULL,TRUE)
ma_report <- function(r)c("# 多臂/独立两阶段/2-in-1开发稿",paste0("版本",r$version,"；设计",r$config$design,"；检验",r$config$test,"；校正",r$config$multiplicity),"主成功为至少一个真实有效臂声明；FWER为至少一个真实零效应或有害臂声明。所有试验臂从开始纳入多重性家族。Stage2只含新患者及新共享对照；2-in-1以PFS筛选、OS确认，未选择臂p=1。阶段权重预定，不随实际信息或选择数改变。精确分支检验固定年龄生存比例，log-rank分支为渐近近似。Dunnett型使用联合Cox Wald估计协方差/正态近似；两阶段按完整交集组合，未选择臂不能声明。事件目标未达不检验，Stage2仅新队列事件。可选固定权重组合Wald/Bonferroni近似区间，不宣称与闭合拒绝相容。不支持共享患者无缝改终点的正式检验。",capture.output(print(r$method_overview,row.names=FALSE)),capture.output(print(r$arm_overview,row.names=FALSE)),capture.output(print(r$intersection_overview,row.names=FALSE)),capture.output(print(r$interval_overview,row.names=FALSE)),"联合Cox协方差完整记录另见covariance_overview CSV/RDS。代码与方法待验证。")
