# Dunnett-type Gaussian contrasts use a single joint PH Cox fit, not invented
# independent log-rank correlations. Every stage contains disjoint patients.
mx_rule <- function(cfg)cfg$cut_rule %||% "fixed"
mx_cut <- function(truth,cfg,stage,endpoint){cap<-if(stage==1)cfg$stage1_day else cfg$max_day;target<-if(stage==1)cfg$event_d1 %||% 1L else cfg$event_d2 %||% 1L;if(mx_rule(cfg)=="fixed")return(list(day=cap,reached=TRUE,target=NA_integer_,events=NA_integer_,rule="fixed"));t<-if(endpoint=="PFS")truth$pfs_time_day else truth$os_time_day;calendar<-truth$entry_day+t;visible<-sort(calendar[is.finite(calendar)&calendar<=cap&t<=truth$dropout_time_day]);hit<-length(visible)>=target;list(day=if(hit)visible[target] else cap,reached=hit,target=target,events=if(hit)target else length(visible),rule="target")}
mx_empty_stage <- function(arms,note="没有正式分析",endpoint="OS"){k<-length(arms);R<-diag(k);dimnames(R)<-list(arms,arms);list(arms=arms,p=setNames(rep(1,k),arms),z=setNames(rep(-Inf,k),arms),beta=setNames(rep(NA_real_,k),arms),se=setNames(rep(NA_real_,k),arms),performed=setNames(rep(FALSE,k),arms),note=setNames(rep(note,k),arms),correlation=R,covariance=matrix(NA_real_,k,k,dimnames=list(arms,arms)),endpoint=endpoint)}
mx_stage <- function(o,planned,cfg,day,arms,endpoint,formal=TRUE){a<-mx_empty_stage(arms,endpoint=endpoint);if(!formal)return(a);a$n<-nrow(o);a$events<-sum(o$event)
  if(cfg$test!="cox_wald"){for(g in arms){x<-ma_test(o,planned,g,cfg,day);a$p[g]<-x$p;a$z[g]<-x$z;a$performed[g]<-x$performed;a$note[g]<-x$note};return(a)}
  o<-o[o$group %in% c("Control",arms),,drop=FALSE];present<-arms[arms %in% unique(o$group)];if(!"Control" %in% o$group||!length(present)||sum(o$event)==0)return(mx_empty_stage(arms,"两组风险集/事件不足，预定p=1",endpoint))
  o$arm<-factor(o$group,levels=c("Control",present));warn<-character();fit<-withCallingHandlers(survival::coxph(survival::Surv(time_day,event)~arm,data=o,ties="efron",control=survival::coxph.control(iter.max=80,timefix=FALSE)),warning=function(w){warn<<-c(warn,conditionMessage(w));invokeRestart("muffleWarning")});b<-unname(coef(fit));V<-unname(vcov(fit));if(length(warn)||length(b)!=length(present)||any(!is.finite(b))||any(!is.finite(V))||any(diag(V)<=0)||fit$iter>=80)stop(paste(c("联合Cox拟合未获得有效协方差，不修复或删臂后重拟合。",warn),collapse="；"));s<-sqrt(diag(V));R<-V/outer(s,s);dimnames(R)<-list(present,present);a$beta[present]<-b;a$se[present]<-s;a$z[present]<--b/s;a$p[present]<-pnorm(a$z[present],lower.tail=FALSE);a$performed[present]<-TRUE;a$note[present]<-"联合PH Cox Wald正态近似；Efron并列处理，非有限样本精确检验。";a$correlation[present,present]<-R;a$covariance[present,present]<-V;a}
mx_normal_max_p <- function(z,R,steps=128L){if(!length(z))return(1);if(anyNA(z)||anyNA(R))stop("交集Z/相关矩阵不完整。");if(all(z==-Inf))return(1);if(any(z==Inf))return(0);c<-max(z);if(length(z)==1)return(pnorm(c,lower.tail=FALSE));if(any(!is.finite(R))||max(abs(R-t(R)))>1e-8||max(abs(diag(R)-1))>1e-8)stop("Dunnett相关矩阵无效。");if(min(eigen(R,symmetric=TRUE,only.values=TRUE)$values)<=1e-8)stop("Dunnett相关矩阵奇异/接近奇异；不自动加ridge或改用独立矩阵。");v<-mvtnorm::pmvnorm(lower=rep(-Inf,length(z)),upper=rep(c,length(z)),corr=R,algorithm=mvtnorm::Miwa(steps=as.integer(steps),checkCorr=TRUE));p<-1-as.numeric(v);if(!is.finite(p)||p< -1e-8||p>1+1e-8)stop("多元正态积分返回非法概率。");pmin(pmax(p,pnorm(c,lower.tail=FALSE)),1)}
mx_intersections <- function(arms)unlist(lapply(seq_along(arms),function(k)combn(arms,k,simplify=FALSE)),recursive=FALSE)
mx_local_p <- function(a,I,steps){active<-I[a$performed[I] %in% TRUE];if(!length(active))return(1);mx_normal_max_p(a$z[active],a$correlation[active,active,drop=FALSE],steps)}
mx_adjust <- function(first,second,cfg,selected){arms<-first$arms;m<-length(arms);p<-first$p;local<-data.frame();steps<-cfg$dunnett_steps %||% 128L
  if(cfg$design!="final"){p[]<-1;for(g in selected)p[g]<-if(cfg$confirmation=="stage2")second$p[g] else ma_combine(first$p[g],second$p[g],cfg$w1)}
  if(cfg$multiplicity %in% c("bonferroni","holm"))return(list(p=p,adjusted=p.adjust(p,cfg$multiplicity,n=m),intersections=local))
  if(cfg$multiplicity=="dunnett"){adjusted<-setNames(vapply(arms,function(g){if(!first$performed[g])return(1);mx_normal_max_p(rep(first$z[g],m),first$correlation,steps)},numeric(1)),arms);return(list(p=p,adjusted=adjusted,intersections=local))}
  sets<-mx_intersections(arms);lp<-vapply(sets,function(I){p1<-mx_local_p(first,I,steps);p2<-if(cfg$design=="final")NA_real_ else mx_local_p(second,intersect(I,selected),steps);combined<-if(cfg$design=="final")p1 else if(cfg$confirmation=="stage2")p2 else ma_combine(p1,p2,cfg$w1);combined},numeric(1));local<-batch_bind_columns(lapply(seq_along(sets),function(i){I<-sets[[i]];data.frame(intersection=paste(I,collapse="&"),size=length(I),stage1_local_p=mx_local_p(first,I,steps),stage2_members=if(cfg$design=="final")"" else paste(intersect(I,selected),collapse="&"),stage2_local_p=if(cfg$design=="final")NA_real_ else mx_local_p(second,intersect(I,selected),steps),local_combination_p=lp[i],local_reject=lp[i]<=cfg$alpha)}));adjusted<-setNames(vapply(arms,function(g)if(!g %in% selected)1 else max(lp[vapply(sets,function(I)g %in% I,logical(1))]),numeric(1)),arms);list(p=p,adjusted=adjusted,intersections=local)}
mx_intervals <- function(first,second,cfg,selected,sc){arms<-first$arms;alpha<-cfg$interval_alpha %||% .05;m<-length(arms);out<-lapply(arms,function(g){lo<-0;hi<-Inf;estimate<-NA_real_;informative<-FALSE;engine<-"未选择/无信息，全参数空间";if(g %in% selected){if(cfg$design=="final"&&isTRUE(first$performed[g])||cfg$design!="final"&&cfg$confirmation=="stage2"&&isTRUE(second$performed[g])){a<-if(cfg$design=="final")first else second;beta<-a$beta[g];se<-a$se[g];informative<-is.finite(beta)&&is.finite(se)&&se>0;engine<-"单阶段Bonferroni Cox Wald近似"} else if(cfg$design!="final"&&isTRUE(first$performed[g])&&isTRUE(second$performed[g])){s1<-first$se[g];s2<-second$se[g];den<-cfg$w1/s1+sqrt(1-cfg$w1^2)/s2;beta<-(cfg$w1*first$beta[g]/s1+sqrt(1-cfg$w1^2)*second$beta[g]/s2)/den;se<-1/den;informative<-is.finite(beta)&&is.finite(se)&&se>0;engine<-"固定权重组合Wald反演/Bonferroni近似，非无偏MLE"};if(informative){c<-qnorm(1-alpha/(2*m));estimate<-exp(beta);lo<-exp(beta-c*se);hi<-exp(beta+c*se)}};true<-sc[[paste0("hr_",g)]];data.frame(arm=g,estimate_hr=estimate,hr_lower=lo,hr_upper=hi,interval_informative=informative,covered=lo<=true&&hi>=true,true_hr=true,simultaneous_level=1-alpha,interval_engine=engine,compatible_with_closed_rejection=FALSE)});batch_bind_columns(out)}
mx_stage_rows <- function(a,screen,cfg,stage,cut,sc,b){batch_bind_columns(lapply(a$arms,function(g)data.frame(SCENARIO=sc$SCENARIO,SIMID=b,arm=g,stage=stage,PARAMCD=a$endpoint,p=a$p[g],benefit_z=a$z[g],beta=a$beta[g],se_beta=a$se[g],screen_endpoint=screen$endpoint,screen_p=screen$p[g],performed=a$performed[g],note=a$note[g],DCO_DAY=cut$day,cut_rule=cut$rule,planned_events=cut$target,target_reached=cut$reached)))}
mx_covariance_rows <- function(a,stage,sc,b){arms<-a$arms;d<-expand.grid(arm_a=arms,arm_b=arms,stringsAsFactors=FALSE);d$SCENARIO<-sc$SCENARIO;d$SIMID<-b;d$stage<-stage;d$covariance<-mapply(function(g,h)a$covariance[g,h],d$arm_a,d$arm_b);d$correlation<-mapply(function(g,h)a$correlation[g,h],d$arm_a,d$arm_b);d}
mx_trial_core <- function(cfg,sc,b,keep_sample=FALSE){arms<-cfg$arms$arm[-1];endpt<-if(cfg$design=="two_in_one")"OS" else cfg$paramcd;screenpt<-if(cfg$design=="two_in_one")"PFS" else endpt;tr1<-ma_generate_stage(cfg,sc,b,1);cut1<-mx_cut(tr1,cfg,1,screenpt);o1<-ma_observe(tr1,cut1$day,endpt);s1<-if(screenpt==endpt)o1 else ma_observe(tr1,cut1$day,screenpt);a1<-mx_stage(o1,tr1,cfg,cut1$day,arms,endpt,cut1$reached);screen<-if(screenpt==endpt)a1 else mx_stage(s1,tr1,cfg,cut1$day,arms,screenpt,cut1$reached)
  selected<-if(!cut1$reached)character() else if(cfg$design=="final")arms else head(arms[order(screen$p,arms)][screen$p[order(screen$p,arms)]<=cfg$screen_p],cfg$select_k);a2<-mx_empty_stage(arms,endpoint=endpt);tr2<-NULL;o2<-data.frame();cut2<-list(day=cut1$day,reached=FALSE,target=NA_integer_,rule=mx_rule(cfg));working<-cfg;working$stage1_day<-cut1$day
  if(cfg$design!="final"&&length(selected)){tr2<-ma_generate_stage(working,sc,b,2,selected);cut2<-mx_cut(tr2,cfg,2,endpt);o2<-ma_observe(tr2,cut2$day,endpt);a2<-mx_stage(o2,tr2,cfg,cut2$day,selected,endpt,cut2$reached);# Lift back to the original family without invented evidence for dropped arms.
    full<-mx_empty_stage(arms,endpoint=endpt);for(k in c("p","z","beta","se","performed","note"))full[[k]][selected]<-a2[[k]][selected];full$correlation[selected,selected]<-a2$correlation[selected,selected,drop=FALSE];full$covariance[selected,selected]<-a2$covariance[selected,selected,drop=FALSE];a2<-full}
  mult<-mx_adjust(a1,a2,cfg,selected);null<-vapply(arms,function(g)sc[[paste0("hr_",g)]]>=1,logical(1));reject<-mult$adjusted<=cfg$alpha;claim<-data.frame(SCENARIO=sc$SCENARIO,SIMID=b,arm=arms,selected=arms %in% selected,p_stage1=a1$p,p_stage2=a2$p,p_final=mult$p,p_adjusted=mult$adjusted,reject=reject,true_null=null,hr=vapply(arms,function(g)sc[[paste0("hr_",g)]],numeric(1)));if(isTRUE(cfg$interval_enabled)){ci<-mx_intervals(a1,a2,cfg,selected,sc);claim<-cbind(claim,ci[match(claim$arm,ci$arm),setdiff(names(ci),"arm"),drop=FALSE])}
  row<-data.frame(SCENARIO=sc$SCENARIO,SIMID=b,replicate_seed=batch_replicate_seed(cfg$seed,sc$SCENARIO,b),generated=TRUE,decision_valid=TRUE,decision_reject=any(reject&!null),fwer=any(reject&null),any_claim=any(reject),all_active_claim=if(any(!null))all(reject[!null]) else NA,selected_n=length(selected),stage1_target_reached=cut1$reached,stage2_target_reached=if(cfg$design=="final"||!length(selected))NA else cut2$reached,stage1_day=cut1$day,note=if(cfg$test=="landmark_exact")"完整固定年龄精确生存比例检验" else "渐近生存检验；两阶段使用独立新患者；有限样本及事件停止分支待验证")
  obs<-batch_bind_columns(list(o1,o2));if(nrow(obs))obs$SCENARIO<-sc$SCENARIO;final<-if(cfg$design=="final"||!length(selected))cut1$day else cut2$day;mr<-data.frame(SCENARIO=sc$SCENARIO,SIMID=b,method="design",generated=TRUE,decision_valid=TRUE,decision_reject=row$decision_reject,fwer=row$fwer,any_claim=row$any_claim,all_active_claim=row$all_active_claim,target_reached=if(cfg$design=="final")cut1$reached else if(length(selected))cut2$reached else FALSE,final_day=final,n_observed=length(unique(obs$USUBJID)),events=sum(obs$event),future_analysis_count=as.integer(cut1$reached)+as.integer(cfg$design!="final"&&length(selected)>0&&cut2$reached),action=if(!cut1$reached)"stage1_window_no_test" else if(!length(selected))"screen_stop" else if(cfg$design!="final"&&!cut2$reached)"stage2_window_no_test" else if(any(reject))"claim" else "no_claim");looks<-mx_stage_rows(a1,screen,cfg,1L,cut1,sc,b);if(cfg$design!="final"&&length(selected))looks<-batch_bind_columns(list(looks,mx_stage_rows(a2,screen,cfg,2L,cut2,sc,b)));inter<-mult$intersections;if(nrow(inter)){inter$SCENARIO<-sc$SCENARIO;inter$SIMID<-b;inter$record_kind<-"closed_intersection"};cov<-batch_bind_columns(list(mx_covariance_rows(a1,1L,sc,b),if(cfg$design!="final"&&length(selected))mx_covariance_rows(a2,2L,sc,b)));cov$record_kind<-"joint_covariance";out<-list(row=row,method_rows=mr,looks=looks,draw_rows=batch_bind_columns(list(transform(claim,record_kind="arm_claim"),inter,cov)))
  if(keep_sample){out$truth<-batch_bind_columns(list(tr1,tr2));out$truth$SCENARIO<-sc$SCENARIO;if(nrow(s1))s1$SCENARIO<-sc$SCENARIO;out$observed<-if(cfg$design=="two_in_one")batch_bind_columns(list(obs,s1)) else obs;out$screen_observed<-s1;out$intersections<-inter;out$covariance<-cov};out}
mx_attach <- function(s){d<-s$draw_rows;s$intersection_overview<-s$covariance_overview<-s$interval_overview<-data.frame();if(!nrow(d))return(s);kind<-if("record_kind" %in% names(d))d$record_kind else rep("arm_claim",nrow(d));i<-d[!is.na(kind)&kind=="closed_intersection",,drop=FALSE];if(nrow(i))s$intersection_overview<-batch_bind_columns(lapply(split(i,paste(i$SCENARIO,i$intersection)),function(x)cbind(data.frame(SCENARIO=x$SCENARIO[1],intersection=x$intersection[1]),jr_probability(x$local_reject,s$config$reps))));v<-d[!is.na(kind)&kind=="joint_covariance",,drop=FALSE];if(nrow(v))s$covariance_overview<-v[,c("SCENARIO","SIMID","stage","arm_a","arm_b","covariance","correlation"),drop=FALSE];a<-d[!is.na(kind)&kind=="arm_claim",,drop=FALSE];if("covered" %in% names(a)){per_arm<-batch_bind_columns(lapply(split(a,paste(a$SCENARIO,a$arm)),function(x)cbind(data.frame(SCENARIO=x$SCENARIO[1],arm=x$arm[1],metric="arm_coverage",informative=sum(x$interval_informative %in% TRUE)),jr_probability(x$covered,s$config$reps))));joint<-batch_bind_columns(lapply(split(a,a$SCENARIO),function(x){m<-if(ds_is(s$config))nrow(s$config$base$arms)-1L else nrow(s$config$arms)-1L;trials<-split(x,x$SIMID);covered<-vapply(trials,function(t)if(nrow(t)!=m||anyNA(t$covered))NA else all(t$covered),logical(1));cbind(data.frame(SCENARIO=x$SCENARIO[1],arm="ALL_ORIGINAL_ARMS",metric="joint_coverage",informative=sum(vapply(trials,function(t)nrow(t)==m&&all(t$interval_informative %in% TRUE),logical(1)))),jr_probability(covered,s$config$reps))}));s$interval_overview<-batch_bind_columns(list(per_arm,joint))};s}
