# Clinical visit ledger and central availability ledger are distinct observed layers.
ob_is <- function(cfg)identical(cfg$research_family,"observation_process")
ob_names <- c(PFS_interval="PFS区间似然工作模型",PFS_naive="PFS检测时刻作精确事件参照",OS_interval="OS精确/右删失工作模型",OS_ipcw="OS已知退出机制IPCW")
ob_methods <- function(cfg)if(cfg$purpose=="backlog")"release" else names(ob_names)
ob_scenarios <- function(cfg){if(cfg$purpose=="backlog")return(data.frame(label="已知临床报告积压",SCENARIO=1L));d<-cfg$scenario_table;keys<-c("label","n","visit_scale","drop0_scale","drop1_scale","lag_scale");if(!is.data.frame(d)||!identical(sort(names(d)),sort(keys))||nrow(d)<1||nrow(d)>30||anyNA(d)||anyDuplicated(d$label)||any(!nzchar(d$label)))stop("观察情景严格六列label,n,visit_scale,drop0_scale,drop1_scale,lag_scale；1–30唯一名称。");for(k in setdiff(keys,"label"))if(!is.numeric(d[[k]])||any(!is.finite(d[[k]])))stop("情景需有限数值。");if(any(d$n<10|d$n>3000|d$n!=floor(d$n))||any(d$visit_scale<=0|d$visit_scale>10|d$drop0_scale<0|d$drop0_scale>10|d$drop1_scale<0|d$drop1_scale>10|d$lag_scale<0|d$lag_scale>10))stop("N10–3000整数；访视倍数(0,10]；退出/报告倍数0–10。");d$SCENARIO<-seq_len(nrow(d));d}
ob_lag_draw <- function(cfg,n=1L){switch(cfg$lag_model,none=rep(0,n),fixed=rep(cfg$lag_mean,n),gamma=rgamma(n,shape=cfg$lag_shape,scale=cfg$lag_mean/cfg$lag_shape),lognormal=rlnorm(n,log(cfg$lag_mean)-cfg$lag_sd^2/2,cfg$lag_sd),stop("报告分布错误。"))}
ob_lag_survival <- function(cfg,t){t<-pmax(t,0);switch(cfg$lag_model,none=rep(0,length(t)),fixed=as.numeric(t<cfg$lag_mean),gamma=pgamma(t,shape=cfg$lag_shape,scale=cfg$lag_mean/cfg$lag_shape,lower.tail=FALSE),lognormal=plnorm(t,log(cfg$lag_mean)-cfg$lag_sd^2/2,cfg$lag_sd,lower.tail=FALSE))}
ob_lag_pending <- function(cfg,elapsed){if(cfg$lag_model=="none")stop("零延迟模型不能有截至IA仍待送出的临床记录。");if(cfg$lag_model=="fixed"){if(elapsed>=cfg$lag_mean)stop("积压记录超出指定固定送出延迟支持。");return(cfg$lag_mean-elapsed)};S<-ob_lag_survival(cfg,elapsed);if(any(!is.finite(S)|S<=0))stop("积压年龄在指定延迟模型下没有剩余支持。");p<-runif(length(elapsed))*S;total<-if(cfg$lag_model=="gamma")qgamma(p,shape=cfg$lag_shape,scale=cfg$lag_mean/cfg$lag_shape,lower.tail=FALSE) else qlnorm(p,log(cfg$lag_mean)-cfg$lag_sd^2/2,cfg$lag_sd,lower.tail=FALSE);total-elapsed}
ob_batch_release <- function(time,cfg)if(cfg$release_period>0)ceiling(time/cfg$release_period)*cfg$release_period else time
ob_trial_config <- function(cfg,sc){c<-cfg$joint_base;c$n<-sc$n;c$reps<-1;for(j in seq_along(c$groups))c$groups[[j]]$dropout_rate<-0;c}
ob_generate_ledger <- function(truth,cfg,sc){c<-cfg;c$lag_mean<-cfg$lag_mean*sc$lag_scale;if(sc$lag_scale==0)c$lag_model<-"none";out<-list()
  for(i in seq_len(nrow(truth))){x<-truth[i,];entry<-x$entry_day;if(entry>cfg$max_day)next;interval<-cfg$visit_interval*sc$visit_scale
    planned<-if(cfg$max_day-entry>=interval)seq(interval,cfg$max_day-entry,by=interval) else numeric();if(!length(planned))planned<-numeric();visits<-sort(pmax(1e-9,planned+runif(length(planned),-cfg$visit_jitter,cfg$visit_jitter)));visits<-visits[visits<=cfg$max_day-entry&runif(length(visits))>=cfg$miss_probability]
    base_drop<-if(cfg$drop0_rate*sc$drop0_scale>0)rexp(1,cfg$drop0_rate*sc$drop0_scale) else Inf;det<-visits[visits>=x$progression_time_day&visits<x$death_time_day&visits<base_drop];det<-if(length(det))min(det) else Inf
    drop<-if(is.finite(det)){mu<-cfg$drop1_rate*sc$drop1_scale;if(mu>0)det+rexp(1,mu) else Inf} else base_drop
    truth$dropout_time_day[i]<-drop;truth$dropout_day[i]<-entry+drop;limit<-min(drop,x$death_time_day,cfg$max_day-entry);alive_visits<-visits[visits<min(drop,x$death_time_day)]
    make<-function(kind,age,state,lag=TRUE){day<-entry+age;delay<-if(lag)ob_lag_draw(c,length(age)) else rep(0,length(age));data.frame(SIMID=x$SIMID,USUBJID=x$USUBJID,group=x$group,entry_day=entry,kind=kind,clinical_day=day,report_day=if(lag)ob_batch_release(day+delay,c) else day,observed_state=state)}
    out[[length(out)+1L]]<-make("baseline",0,0L,FALSE)
    if(length(alive_visits))out[[length(out)+1L]]<-make("visit",alive_visits,ifelse(alive_visits>=det,1L,0L))
    if(x$death_time_day<=drop&&x$death_day<=cfg$max_day)out[[length(out)+1L]]<-make("death",x$death_time_day,2L)
    else if(drop<x$death_time_day&&entry+drop<=cfg$max_day)out[[length(out)+1L]]<-make("exit",drop,ifelse(det<=drop,1L,0L))
    else out[[length(out)+1L]]<-make("alive_cutoff",cfg$max_day-entry,ifelse(det<=cfg$max_day-entry,1L,0L))
  }
  list(truth=truth,ledger=batch_bind_columns(out))
}
ob_project <- function(ledger,day,feed="central",endpoint="PFS"){visible<-ledger[ledger$clinical_day<=day&(feed=="clinical"|ledger$report_day<=day),,drop=FALSE];baseline<-visible[visible$kind=="baseline",];if(!nrow(baseline))return(data.frame(USUBJID=character(),PARAMCD=character(),ENTRY=numeric(),L=numeric(),R=numeric(),TYPE=character(),EXIT=character(),TRTP=character(),detected_progression_age=numeric(),asof_day=numeric()));out<-lapply(unique(baseline$USUBJID),function(id){x<-visible[visible$USUBJID==id,];entry<-x$entry_day[1];vis<-x[x$kind=="visit",];death<-x[x$kind=="death",];exit<-x[x$kind=="exit",];positive<-x[x$observed_state==1&x$kind!="baseline",];knownpos<-if(nrow(positive))min(positive$clinical_day) else Inf;knownDeath<-if(nrow(death))min(death$clinical_day) else Inf
    if(endpoint=="OS"){if(is.finite(knownDeath)){L<-R<-knownDeath-entry;type<-"exact";status<-"event"} else {a<-x$clinical_day[x$kind %in% c("baseline","visit","exit","alive_cutoff")];L<-max(a)-entry;R<-Inf;type<-"right";status<-if(nrow(exit))"dropout" else "active"}}
    else {upper<-min(knownpos,knownDeath);neg<-vis$clinical_day[vis$observed_state==0];if(is.finite(upper)){L<-max(c(entry,neg[neg<upper]))-entry;R<-upper-entry;type<-if(L==0)"left" else "interval";status<-"event"} else {L<-max(c(entry,neg))-entry;R<-Inf;type<-"right";status<-if(nrow(exit))"dropout" else "active"}}
    data.frame(USUBJID=id,PARAMCD=endpoint,ENTRY=entry,L=L,R=R,TYPE=type,EXIT=status,TRTP=x$group[1],detected_progression_age=if(is.finite(knownpos))knownpos-entry else Inf,asof_day=day)
  });batch_bind_columns(out)
}
ob_ipcw <- function(d,t,cfg,sc){eligible<-d$ENTRY+t<=cfg$max_day;d<-d[eligible,,drop=FALSE];if(!nrow(d))stop("没有达到该风险年龄的入组患者。");stop<-ifelse(d$TYPE=="exact",d$R,d$L);alive<-ifelse(d$TYPE=="exact",stop>t,stop>=t);det<-pmin(d$detected_progression_age,t);G<-exp(-cfg$drop0_rate*sc$drop0_scale*det-cfg$drop1_rate*sc$drop1_scale*(t-det));if(any(!is.finite(G)|G<1e-8))stop("退出存活概率低于1e-8，IPCW不稳定；不自动截断权重。");w<-as.numeric(alive)/G;list(estimate=mean(w),se=if(length(w)>1)sd(w)/sqrt(length(w)) else NA_real_,eligible=nrow(d),max_weight=max(1/G))}
ob_estimates <- function(observed,cfg,sc){out<-list();fitcfg<-list(analysis_mode="pooled");methods<-names(ob_names)
  for(m in methods){endpoint<-if(grepl("PFS",m))"PFS" else "OS";d<-observed[observed$PARAMCD==endpoint,,drop=FALSE];model<-NULL;note<-"";failed<-FALSE
    if(m=="OS_ipcw"&&cfg$analysis_feed=="central"&&((cfg$lag_model!="none"&&sc$lag_scale>0)||cfg$release_period>0)){failed<-TRUE;note<-"IPCW仅适用临床实时OS随访层；中央迟报不是退出权重能够修正的删失。"}
    if(m!="OS_ipcw"){if(m=="PFS_naive"){event<-d$TYPE!="right";d$L[event]<-d$R[event];d$TYPE[event]<-"exact"};model<-tryCatch(fx_fit_one(d,"weibull",fitcfg),error=function(e){note<<-conditionMessage(e);NULL});failed<-is.null(model)}
    for(t in cfg$reference_ages){a<-tryCatch({if(failed)stop(note);if(m=="OS_ipcw")ob_ipcw(d,t,cfg,sc) else list(estimate=model_survival(model,t),se=NA_real_,eligible=nrow(d),max_weight=NA_real_)},error=function(e)list(estimate=NA_real_,se=NA_real_,eligible=NA_integer_,max_weight=NA_real_,note=conditionMessage(e)))
      out[[length(out)+1L]]<-data.frame(method=m,PARAMCD=endpoint,age_day=t,estimate_valid=is.finite(a$estimate),estimate=a$estimate,se=a$se,eligible=a$eligible,max_weight=a$max_weight,note=a$note %||% if(cfg$drop0_rate!=cfg$drop1_rate&&m!="OS_ipcw")"状态依赖退出下未修正的工作模型；不宣称独立删失。" else "工作模型；访视/报告可忽略条件需另行评估。")
    }
  };batch_bind_columns(out)
}
validate_observation <- function(cfg){if(!ob_is(cfg)||!cfg$purpose %in% c("design","backlog")||!cfg$lag_model %in% c("none","fixed","gamma","lognormal"))stop("选择观察研究或已知积压预测及报告分布。");if(cfg$lag_model!="none"&&(!is.finite(cfg$lag_mean)||cfg$lag_mean<=0)||!is.finite(cfg$lag_shape)||cfg$lag_shape<=0||!is.finite(cfg$lag_sd)||cfg$lag_sd<=0||!is.finite(cfg$release_period)||cfg$release_period<0)stop("非零报告均值正；Gamma形状/对数SD正，批次周期非负。");if(!is.finite(cfg$seed)||cfg$seed<0||cfg$seed>.Machine$integer.max||cfg$seed!=floor(cfg$seed)||cfg$reps<20||cfg$reps>10000||cfg$reps!=floor(cfg$reps))stop("B20–10000整数，种子非负整数。")
  if(cfg$purpose=="backlog"){d<-cfg$backlog;if(!is.data.frame(d)||!identical(sort(names(d)),sort(c("USUBJID","PARAMCD","CLINICAL_DAY","STATE","SENT_DAY")))||!nrow(d)||nrow(d)>5000||anyNA(d[,setdiff(names(d),"SENT_DAY")])||anyDuplicated(paste(d$USUBJID,d$PARAMCD))||any(!d$STATE %in% c("reported","unsent","sent"))||any(!is.finite(d$CLINICAL_DAY)|d$CLINICAL_DAY<0|d$CLINICAL_DAY>cfg$cut))stop("积压五列USUBJID,PARAMCD,CLINICAL_DAY,STATE,SENT_DAY；临床时点≤IA，每人每终点唯一。");if(any(d$STATE %in% c("reported","sent")&(!is.finite(d$SENT_DAY)|d$SENT_DAY<d$CLINICAL_DAY|d$SENT_DAY>cfg$cut)))stop("reported/sent需已知送出时点，临床日≤送出日≤IA。");if(any(d$STATE=="unsent"&!is.na(d$SENT_DAY)))stop("unsent记录不能填写尚未知送出日。");if(any(d$STATE=="sent")&&cfg$release_period<=0)stop("已送出尚未发布只用于指定固定批次；无批次时送出即reported。");if(any(d$STATE=="sent"&ob_batch_release(d$SENT_DAY,cfg)<=cfg$cut))stop("sent记录按指定批次应已发布，请修改状态/机制。");if(!length(cfg$horizons)||any(!is.finite(cfg$horizons))||length(cfg$horizons)>20||any(cfg$horizons<=cfg$cut|cfg$horizons>3650)||is.unsorted(cfg$horizons,strictly=TRUE))stop("积压未来截点正递增、IA之后≤3650日。");return(invisible(TRUE))}
  validate_joint_config(cfg$joint_base);sc<-ob_scenarios(cfg);if(any(cfg$visit_jitter>=cfg$visit_interval*sc$visit_scale/2))stop("各情景访视抖动须小于该情景半间隔。");
  if(!cfg$analysis_feed %in% c("clinical","central")||!cfg$primary %in% names(ob_names)||!is.finite(cfg$visit_interval)||cfg$visit_interval<=0||cfg$visit_jitter<0||cfg$visit_jitter>=cfg$visit_interval/2||cfg$miss_probability<0||cfg$miss_probability>=1||cfg$drop0_rate<0||cfg$drop1_rate<0||cfg$max_day<=0||cfg$max_day>3650)stop("访视间隔正，抖动小于半间隔，漏访率[0,1)，退出率非负；最大研究时间≤3650日。");if(length(cfg$reference_ages)<1||length(cfg$reference_ages)>10||any(cfg$reference_ages<=0|cfg$reference_ages>cfg$max_day)||is.unsorted(cfg$reference_ages,strictly=TRUE)||!cfg$primary_age %in% cfg$reference_ages)stop("1–10个预定参考年龄，主年龄须在列表内。");if(sum(sc$n)*cfg$reps>1e6||sum(sc$n*cfg$max_day/(cfg$visit_interval*sc$visit_scale))*cfg$reps>1e7)stop("患者×轮次最多100万，预定访视×轮次最多1000万。");invisible(TRUE)
}
ob_backlog_trial <- function(cfg,b,keep_sample=FALSE){d<-cfg$backlog;release<-rep(NA_real_,nrow(d));for(i in seq_len(nrow(d))){release[i]<-switch(d$STATE[i],reported=d$SENT_DAY[i],sent=ob_batch_release(d$SENT_DAY[i],cfg),unsent=ob_batch_release(cfg$cut+ob_lag_pending(cfg,cfg$cut-d$CLINICAL_DAY[i]),cfg))};out<-batch_bind_columns(lapply(cfg$horizons,function(day)batch_bind_columns(lapply(unique(d$PARAMCD),function(e){ix<-d$PARAMCD==e;data.frame(SCENARIO=1L,SIMID=b,DCO_DAY=day,PARAMCD=e,known_reported=sum(ix&d$STATE=="reported"),new_releases=sum(ix&d$STATE!="reported"&release<=day),remaining_backlog=sum(ix&release>day))}))));row<-data.frame(SCENARIO=1L,SIMID=b,replicate_seed=batch_replicate_seed(cfg$seed,1L,b),generated=TRUE,decision_valid=FALSE,decision_reject=NA,note="仅预测已知临床清单；不估算尚未知事件积压。");mr<-data.frame(SCENARIO=1L,SIMID=b,method="release",generated=TRUE,decision_valid=FALSE,decision_reject=NA,target_reached=NA,final_day=max(cfg$horizons),events=NA_real_,n_observed=nrow(d),action="known_backlog",future_analysis_count=0L);a<-list(row=row,method_rows=mr,draw_rows=out,looks=data.frame());if(keep_sample){a$truth<-transform(d,predicted_release_day=release);a$observed<-d;a$ledger<-d};a}
ob_trial <- function(cfg,sc,b,prepared=NULL,keep_sample=FALSE)batch_with_rng(batch_replicate_seed(cfg$seed,sc$SCENARIO,b),{tryCatch({if(cfg$purpose=="backlog")return(ob_backlog_trial(cfg,b,keep_sample));tc<-ob_trial_config(cfg,sc);truth<-simulate_joint_truth(tc,b);a<-ob_generate_ledger(truth,cfg,sc);clinical<-batch_bind_columns(lapply(c("PFS","OS"),function(e)ob_project(a$ledger,cfg$max_day,"clinical",e)));central<-batch_bind_columns(lapply(c("PFS","OS"),function(e)ob_project(a$ledger,cfg$max_day,"central",e)));observed<-if(cfg$analysis_feed=="clinical")clinical else central;est<-ob_estimates(observed,cfg,sc);est$SCENARIO<-sc$SCENARIO;est$SIMID<-b;est$truth_survival<-vapply(seq_len(nrow(est)),function(i)sum(vapply(tc$groups,function(g)g$weight*joint_marginal_survival(tc,est$age_day[i],g$name,est$PARAMCD[i]),numeric(1))),numeric(1));est$error<-est$estimate-est$truth_survival
    mr<-batch_bind_columns(lapply(names(ob_names),function(m){x<-est[est$method==m&est$age_day==cfg$primary_age,];data.frame(SCENARIO=sc$SCENARIO,SIMID=b,method=m,generated=TRUE,decision_valid=TRUE,decision_reject=x$estimate_valid,estimate_valid=x$estimate_valid,target_reached=NA,final_day=cfg$max_day,n_observed=sum(observed$PARAMCD==x$PARAMCD),events=sum(observed$PARAMCD==x$PARAMCD&observed$TYPE!="right"),future_analysis_count=1L,action=if(x$estimate_valid)"estimate" else "not_estimable") }));primary<-mr[mr$method==cfg$primary,];row<-data.frame(SCENARIO=sc$SCENARIO,SIMID=b,replicate_seed=batch_replicate_seed(cfg$seed,sc$SCENARIO,b),generated=TRUE,decision_valid=TRUE,decision_reject=primary$estimate_valid,note="主结果是可估计比例，不是检验功效。")
    process<-batch_bind_columns(lapply(c("PFS","OS"),function(e)data.frame(SCENARIO=sc$SCENARIO,SIMID=b,method="process",PARAMCD=e,DCO_DAY=cfg$max_day,clinical_known_events=sum(clinical$PARAMCD==e&clinical$TYPE!="right"),central_known_events=sum(central$PARAMCD==e&central$TYPE!="right"),known_clinical_unreported=sum(clinical$PARAMCD==e&clinical$TYPE!="right")-sum(central$PARAMCD==e&central$TYPE!="right"))))
    out<-list(row=row,method_rows=mr,draw_rows=est,looks=process);if(keep_sample){out$truth<-a$truth;out$observed<-observed;out$ledger<-a$ledger[a$ledger$clinical_day<=cfg$max_day&(cfg$analysis_feed=="clinical"|a$ledger$report_day<=cfg$max_day),];out$availability_truth<-a$ledger;out$clinical_ledger<-a$ledger[a$ledger$clinical_day<=cfg$max_day,];out$clinical_ledger$report_state<-ifelse(out$clinical_ledger$report_day<=cfg$max_day,"reported","unreported");out$clinical_ledger$report_day[out$clinical_ledger$report_day>cfg$max_day]<-NA_real_;if(cfg$analysis_feed=="clinical")out$ledger<-out$clinical_ledger;out$clinical_intervals<-clinical;out$central_intervals<-central;out$study_config<-tc};out
  },error=function(e)list(row=data.frame(SCENARIO=sc$SCENARIO,SIMID=b,replicate_seed=batch_replicate_seed(cfg$seed,sc$SCENARIO,b),generated=FALSE,decision_valid=FALSE,decision_reject=NA,note=conditionMessage(e)),method_rows=batch_bind_columns(lapply(ob_methods(cfg),function(m)data.frame(SCENARIO=sc$SCENARIO,SIMID=b,method=m,generated=FALSE,decision_valid=FALSE,decision_reject=NA,target_reached=NA))),looks=data.frame(),draw_rows=data.frame()))})
ob_aggregate <- function(state){cfg<-state$config;state<-research_aggregate(state,ob_methods(cfg),if(cfg$purpose=="backlog")c(release="已知报告积压") else ob_names,if(cfg$purpose=="backlog")"target_reached" else "estimate_valid");d<-state$draw_rows;state$recovery<-data.frame();state$process_overview<-data.frame();state$backlog_overview<-data.frame()
  if(cfg$purpose=="design"&&nrow(d)){state$recovery<-batch_bind_columns(lapply(split(d,paste(d$SCENARIO,d$method,d$age_day)),function(x){v<-x$estimate_valid %in% TRUE;data.frame(SCENARIO=x$SCENARIO[1],method=x$method[1],PARAMCD=x$PARAMCD[1],age_day=x$age_day[1],requested=cfg$reps,processed=nrow(x),valid=sum(v),mean_estimate=if(any(v))mean(x$estimate[v]) else NA_real_,truth=x$truth_survival[1],bias=if(any(v))mean(x$error[v]) else NA_real_,rmse=if(any(v))sqrt(mean(x$error[v]^2)) else NA_real_,note="仅有效轮次估计误差；真值仅用于评价，不参与观察层拟合/IPCW。") }));p<-state$looks;state$process_overview<-batch_bind_columns(lapply(split(p,paste(p$SCENARIO,p$PARAMCD)),function(x)data.frame(SCENARIO=x$SCENARIO[1],PARAMCD=x$PARAMCD[1],requested=cfg$reps,generated=nrow(x),mean_clinical_events=mean(x$clinical_known_events),mean_reported_events=mean(x$central_known_events),mean_known_unreported=mean(x$known_clinical_unreported))))}
  if(cfg$purpose=="backlog"&&nrow(d))state$backlog_overview<-batch_bind_columns(lapply(split(d,paste(d$PARAMCD,d$DCO_DAY)),function(x){q<-as.numeric(quantile(x$new_releases,c(.025,.5,.975)));data.frame(PARAMCD=x$PARAMCD[1],DCO_DAY=x$DCO_DAY[1],requested=cfg$reps,valid=nrow(x),known_reported=x$known_reported[1],mean_new_releases=mean(x$new_releases),release_lower=q[1],release_median=q[2],release_upper=q[3],mean_remaining=mean(x$remaining_backlog))}));state}
run_observation <- function(cfg,progress=function(state)NULL,should_cancel=function()FALSE,replay_keys=NULL,resume_state=NULL,continuation_operation="resume"){validate_observation(cfg);research_family_run(cfg,ob_scenarios(cfg),ob_trial,ob_aggregate,progress,should_cancel,replay_keys,resume_state,continuation_operation)}
ob_initial <- function(cfg,initial=NULL)research_initial(cfg,ob_scenarios(cfg),ob_aggregate,initial)
ob_sample <- function(r,scenario,replicate){if(!any(r$rows$SCENARIO==scenario&r$rows$SIMID==replicate&r$rows$generated))stop("请选择已生成轮次。");ob_trial(r$config,r$scenarios[scenario,,drop=FALSE],replicate,NULL,TRUE)}
ob_report <- function(r)c("# 复杂观察过程/已知报告积压开发稿",paste0("版本",r$version,"；需求",r$config$purpose,"；处理",r$completed,"/",r$total),capture.output(print(r$recovery,row.names=FALSE)),capture.output(print(r$process_overview,row.names=FALSE)),capture.output(print(r$backlog_overview,row.names=FALSE)),"PFS由访视或死亡界定区间，不能读取未观察真实进展。退出率依赖已检测进展状态，不是隐匿真实状态；IPCW已知机制只用于完整临床实时OS随访层。中央迟报不自动按独立删失分析。积压预测仅包含用户已知的临床清单，不推测未知积压。未运行验证。")
ob_interval_adtte <- function(d,cfg){if(!nrow(d))return(data.frame());age<-ifelse(d$TYPE=="right",d$L,d$R);date<-function(x)as.Date(cfg$origin)+floor(x);data.frame(USUBJID=d$USUBJID,PARAMCD=d$PARAMCD,TRTP=d$TRTP,STARTDT=date(d$ENTRY),ADT=date(d$ENTRY+age),AVAL=floor(d$ENTRY+age)-floor(d$ENTRY)+1,AVALU="DAYS",CNSR=ifelse(d$TYPE!="right",0L,ifelse(d$EXIT=="dropout",2L,1L)),CNSTYPE=d$TYPE,ENGINE_ENTRY_DAY=d$ENTRY,ENGINE_OBS_DAY=d$ENTRY+age,ENGINE_TIME_DAY=age,ENGINE_L_DAY=d$L,ENGINE_R_DAY=d$R,ANL01FL="Y")}
