register_research_workbench_server <- function(input,output,session,controller,prefix,family,task,tabs,builder,sampler,reporter,runner,extra=character(),input_tabs=NULL) {
  id<-function(x)paste0(prefix,x);result<-reactive({r<-controller$result();if(!is.null(r)&&identical(r$config$research_family,family))r else NULL})
  imported<-reactiveVal(NULL);import_note<-reactiveVal("请选择该研究家族的无损配置JSON。")
  observeEvent(input[[id("config_file")]],{imported(NULL);tryCatch({cfg<-batch_read_config(input[[id("config_file")]]$datapath);if(!identical(cfg$research_family,family))stop("配置文件的研究类型与当前入口不一致。");imported(cfg);if(task %in% c("multistate","joint_sequential","flexible_prediction","observation"))updateSelectInput(session,id("purpose"),selected=cfg$purpose);import_note(paste0("已载入",nrow(batch_scenarios(cfg)),"情景，每情景",cfg$reps,"轮；页面其他参数不参与运行。"))},error=function(e)import_note(conditionMessage(e)))},ignoreInit=TRUE)
  output[[id("import_note")]]<-renderUI(p(class="field-note",import_note()))
  observe({for(k in input_tabs %||% (if(task=="conditional_batch")"cb_inputs" else c("hg_baseline","hg_scenarios","hg_analysis")))if((input[[id("run_source")]] %||% "ui")=="config_json" || (task=="shared_adaptation"&&k=="sp_plan"&&identical(input[[id("purpose")]],"observed")))nav_hide(tabs,k,session=session) else if(task=="joint_sequential"&&k=="je_plan"&&identical(input[[id("purpose")]],"observed"))nav_hide(tabs,k,session=session) else if(task=="flexible_prediction"&&k=="fp_plan"&&identical(input[[id("purpose")]],"fit"))nav_hide(tabs,k,session=session) else nav_show(tabs,k,session=session)})
  observeEvent(input[[id("run")]],{tryCatch({if(!is.null(controller$job()))stop("本会话已有后台研究，请等待或取消。");cfg<-if((input[[id("run_source")]] %||% "ui")=="config_json")imported() else builder();if(is.null(cfg))stop("先准备有效配置。");validate_batch_config(cfg);store<-batch_create_run(cfg,input$ba_workspace_token,input[[id("run_name")]]);controller$start_saved(cfg,store=store);controller$workspace$refresh()},error=function(e){controller$error(conditionMessage(e));nav_select(tabs,id("results"),session=session)})},ignoreInit=TRUE)
  observeEvent(input[[id("cancel")]],{j<-controller$job();if(!is.null(j))file.create(file.path(j$dir,"cancel.flag"))},ignoreInit=TRUE)
  observeEvent(input[[id("library")]],{updateSelectInput(session,"task",selected="batch");nav_select("ba_tabs","ba_library",session=session)},ignoreInit=TRUE)
  output[[id("status")]]<-renderUI({r<-result();e<-controller$error();tagList(if(!is.null(e))p(class="field-note",e),if(is.null(r))p(class="field-note","运行后显示冻结配置的结果；当前开发稿待复核。") else p(class="field-note",paste0(r$run_title %||% "研究"," · v",r$version,"待复核；处理",r$completed,"/",r$total,"；",r$status,"；预定主方法",batch_method_label(r$config$primary,r$config),"。资源按成功生成轮次，概率保留全部请求分母。")))})
  display<-function(d,r){if(is.null(d)||!ncol(d))return(study_table(data.frame(记录=character())));for(k in names(d)[grepl("_day$|^DCO_DAY$",names(d))]){d[[k]]<-d[[k]]/time_factor(r$config$display_unit);names(d)[names(d)==k]<-paste0(k,"（",time_label(r$config$display_unit),"）")};study_table(d)}
  tables<-c("overview","method_overview","method_pairs","resources","stops",extra)
  for(k0 in tables)local({k<-k0;output[[id(k)]]<-renderDT({r<-result();req(r);display(r[[k]],r)})})
  observe({r<-result();if(is.null(r))return();old<-isolate(input[[id("view_scenario")]]);updateSelectInput(session,id("view_scenario"),choices=setNames(r$scenarios$SCENARIO,paste(r$scenarios$SCENARIO,r$scenarios$label)),selected=if(length(old)==1&&old %in% as.character(r$scenarios$SCENARIO))old else r$scenarios$SCENARIO[1])})
  observe({r<-result();req(r,input[[id("view_scenario")]]);v<-if(nrow(r$rows))r$rows$SIMID[r$rows$SCENARIO==as.integer(input[[id("view_scenario")]])&r$rows$generated] else integer();old<-isolate(input[[id("view_trial")]]);updateSelectInput(session,id("view_trial"),choices=v,selected=if(length(old)==1&&old %in% as.character(v))old else head(v,1))})
  sample_saved<-eventReactive(input[[id("sample_run")]],{r<-result();req(r,input[[id("view_scenario")]],input[[id("view_trial")]]);a<-sampler(r,as.integer(input[[id("view_scenario")]]),as.integer(input[[id("view_trial")]]));a$selection<-list(run_id=r$run_id,scenario=as.integer(input[[id("view_scenario")]]),replicate=as.integer(input[[id("view_trial")]]));a},ignoreInit=TRUE)
  sample<-reactive({r<-result();req(r,input[[id("view_scenario")]],input[[id("view_trial")]]);a<-sample_saved();req(identical(a$selection,list(run_id=r$run_id,scenario=as.integer(input[[id("view_scenario")]]),replicate=as.integer(input[[id("view_trial")]]))));a})
  for(pair in list(c("sample_rows","method_rows"),c("sample_looks","looks"),c("sample_observed","observed")))local({out<-pair[1];key<-pair[2];output[[id(out)]]<-renderDT({r<-result();req(r);display(sample()[[key]],r)})})
  for(k0 in unique(c("scenarios","rows","method_rows","looks","draw_rows",tables)))local({k<-k0;output[[id(paste0(k,"_download"))]]<-downloadHandler(filename=paste0(task,"_",k,"_days.csv"),content=function(file){r<-result();req(r);write.csv(r[[k]] %||% data.frame(),file,row.names=FALSE)})})
  output[[id("config_download")]]<-downloadHandler(filename=paste0(task,"_config.json"),content=function(file){r<-result();req(r);jsonlite::write_json(batch_config_document(r$config),file,auto_unbox=TRUE,pretty=TRUE,digits=NA)})
  output[[id("result_download")]]<-downloadHandler(filename=paste0(task,"_result_draft.rds"),content=function(file){r<-result();req(r);saveRDS(r,file,version=3)})
  output[[id("report_download")]]<-downloadHandler(filename=paste0(task,"_report_draft.md"),content=function(file){r<-result();req(r);writeLines(reporter(r),file,useBytes=TRUE)},contentType="text/markdown; charset=utf-8")
  output[[id("script_download")]]<-downloadHandler(filename=paste0(task,"_replay_draft.R"),content=function(file){r<-result();req(r);writeLines(research_replay_script(r,runner),file,useBytes=TRUE)})
  for(k0 in c("observed","truth"))local({k<-k0;output[[id(paste0(k,"_download"))]]<-downloadHandler(filename=paste0(task,"_selected_",k,"_days.csv"),content=function(file)write.csv(sample()[[k]],file,row.names=FALSE))})
  output[[id("adtte_download")]]<-downloadHandler(filename=paste0(task,"_selected_adtte.csv"),content=function(file){r<-result();req(r);o<-sample()$observed;if("design" %in% names(o))o$METHOD<-o$design;if("cohort" %in% names(o))o$COHORT<-o$cohort;write.csv(research_adtte(o,r$config,c("METHOD","COHORT","XBIN","XNORM","STRATUM","CENTER")),file,row.names=FALSE)})
  invisible(list(result=result,sample=sample,configuration=function(){if((input[[id("run_source")]] %||% "ui")=="config_json")imported() else builder()}))
}
register_conditional_batch_server <- function(input,output,session,controller) {
  draft<-reactiveVal(NULL);note<-reactiveVal("先在现有IA入口填写参数，再冻结到此处；也可导入本平台条件批量JSON。")
  stage<-function(data,engine,branch){p<-cb_freeze(data,engine,branch);draft(p);note(paste0("已冻结",nrow(p$data),"人、",sum(p$data$event),"个IA事件；类型",branch,"；",p$frozen_at,"。页面原参数再修改不会改变本快照。"));updateSelectInput(session,"cb_unit",selected=p$engine$display_unit);updateSelectInput(session,"cb_primary",choices=if(branch=="new_cohort")c("已选定新队列D2"="adaptive","原计划新队列D2"="original") else c("原设计log-rank"="logrank"),selected=if(branch=="new_cohort")"adaptive" else "logrank");updateRadioButtons(session,"cb_run_source",selected="ui");updateSelectInput(session,"task",selected="conditional_batch");nav_select("cb_tabs","cb_inputs",session=session)}
  output$cb_draft_note<-renderUI(p(class="field-note",note()))
  output$cb_draft_summary<-renderDT({p<-draft();req(p);c<-p$engine;study_table(data.frame(参数=c("类型","IA人数","IA事件","IA时间（日）","Control","事件参数处理","过程参数处理","冻结时间"),值=as.character(c(p$branch,nrow(p$data),sum(p$data$event),c$cut,c$control %||% c$prediction_control,c$uncertainty,c$process_uncertainty %||% "fixed",p$frozen_at))))})
  observeEvent(input$cb_open_existing,{updateSelectInput(session,"task",selected="conditional");updateSelectInput(session,"ci_purpose",selected="rejection")},ignoreInit=TRUE)
  observeEvent(input$cb_open_new,{updateSelectInput(session,"task",selected="adaptive");updateSelectInput(session,"ad_engine",selected="patient");updateSelectInput(session,"pa_purpose",selected="patient_prediction")},ignoreInit=TRUE)
  builder<-function(){p<-draft();if(is.null(p))stop("先冻结当前IA参数。");d<-tryCatch(read.csv(text=input$cb_scenario_csv,stringsAsFactors=FALSE,check.names=FALSE),error=function(e)stop("附加情景需CSV格式。"));c<-p$engine
    list(research_family="actual_ia_conditional",branch=p$branch,payload=p,mode="conditional",design_mode="fixed",effect_mode="conditional_future",primary=input$cb_primary,sided=c$prediction_sided %||% "benefit",alpha=c$prediction_alpha %||% c$alpha,paramcd=c$paramcd %||% "PFS",origin=c$origin,display_unit=input$cb_unit %||% c$display_unit,engine_unit="days",cut_rule=if(p$branch=="new_cohort")"new_cohort_events" else c$cut_mode,reps=input$cb_reps,seed=input$cb_seed,scenario_table=d,filter_enabled=FALSE,reference_scenario=1)}
  register_research_workbench_server(input,output,session,controller,"cb_","actual_ia_conditional","conditional_batch","cb_tabs",builder,cb_sample,cb_report,"run_conditional_batch",extra=c("scenario_pairs","ia_overview","model_overview"))
  output$cb_template<-downloadHandler(filename="conditional_batch_scenarios.csv",content=function(file)write.csv(data.frame(label=c("Treatment风险降低","脱落增加"),control_event_q=1,treatment_event_q=c(.8,1),control_enroll_q=1,treatment_enroll_q=1,control_dropout_q=c(1,1.5),treatment_dropout_q=c(1,1.5)),file,row.names=FALSE))
  invisible(list(stage=stage,draft=draft))
}
heterogeneity_input <- function(input) {
  u<-input$hg_unit %||% "months";f<-time_factor(u);values<-function(pre){d<-simulation_defaults(u);setNames(lapply(names(d),function(k)input[[paste0(pre,k)]] %||% d[[k]]),names(d))};v<-values("hgm_")
  cfg<-list(research_family="heterogeneous_survival",mode="fixed_truth",design_mode="fixed",effect_mode="conditional_ph_heterogeneous",display_unit=u,engine_unit="days",origin=as.character(input$hg_origin),paramcd=input$hg_endpoint,control_model=simulation_parameter_model(v$design_model,v,u),treatment_fraction=input$hg_allocation,
    strata=hg_strata(input$hg_strata),binary_probability=input$hg_binary_probability,binary_beta=input$hg_binary_beta,normal_mean=input$hg_normal_mean,normal_sd=input$hg_normal_sd,normal_beta=input$hg_normal_beta,n_centers=input$hg_n_centers,center_weights=parse_unit_numbers(input$hg_center_weights),center_analysis=input$hg_center_analysis,
    enroll_mode=input$hg_enroll_mode,dropout_rates=c(dropout_input_rate(values("hgdc_")),dropout_input_rate(values("hgdt_")))/f,cut_rule=input$hg_cut_rule,max_day=input$hg_max*f,target=if(input$hg_cut_rule=="target")input$hg_target else NULL,miss_policy=if(input$hg_cut_rule=="target")input$hg_miss else "analyze",
    primary=input$hg_primary,compare_methods=setdiff(input$hg_extra %||% character(),input$hg_primary),sided=input$hg_sided,alpha=input$hg_alpha,reps=input$hg_reps,seed=input$hg_seed,scenario_source=input$hg_scenario_source,filter_enabled=FALSE,reference_scenario=1)
  if(cfg$enroll_mode=="constant")cfg$enroll_rate<-input$hg_enroll_rate/f
  if(cfg$enroll_mode=="piecewise"){cfg$enroll_cuts<-parse_unit_numbers(input$hg_enroll_cuts)*f;cfg$enroll_rates<-parse_unit_numbers(input$hg_enroll_rates)/f}
  if(cfg$scenario_source=="csv"){if(is.null(input$hg_file))stop("请选择情景CSV。");cfg$scenario_table<-read.csv(input$hg_file$datapath,stringsAsFactors=FALSE,check.names=FALSE);cfg$scenario_filename<-input$hg_file$name}
  else cfg$axes<-list(n=parse_unit_numbers(input$hg_n_values),hr_scale=parse_unit_numbers(input$hg_hr_values),center_sd=parse_unit_numbers(input$hg_center_sd_values),subject_variance=parse_unit_numbers(input$hg_subject_variances))
  validate_heterogeneity(cfg);cfg
}
register_heterogeneity_server <- function(input,output,session,controller) {
  unit<-reactive(input$hg_unit %||% "months");previous<-reactiveVal("months");prefixes<-c("hgm_","hgdc_","hgdt_")
  register_parameter_controls(input,output,session,unit,prefixes,simulation_defaults,simulation_parameter_model)
  observeEvent(input$hg_primary,{choices<-hg_names[names(hg_names)!=input$hg_primary];old<-isolate(input$hg_extra);updateCheckboxGroupInput(session,"hg_extra",choices=setNames(names(choices),unname(choices)),selected=intersect(old,names(choices)))},ignoreInit=TRUE)
  observeEvent(input$hg_unit,{
    to<-unit();from<-previous();if(to==from)return();ratio<-time_factor(from)/time_factor(to);u<-time_label(to)
    update<-function(id,kind,label){v<-isolate(input[[id]]);if(is.null(v))return();value<-tryCatch(switch(kind,duration=v*ratio,rate=v/ratio,log_time=v+log(ratio),duration_text=paste(format(parse_unit_numbers(v)*ratio,digits=16,trim=TRUE),collapse=","),rate_text=paste(format(parse_unit_numbers(v)/ratio,digits=16,trim=TRUE),collapse=",")),error=function(e)v);freezeReactiveValue(input,id);if(kind %in% c("duration_text","rate_text"))updateTextInput(session,id,label=parameter_label(id,label),value=value) else updateNumericInput(session,id,label=parameter_label(id,label),value=value)}
    update("hg_max","duration",paste0("固定DCO / 最大窗口（",u,"）"));update("hg_enroll_rate","rate",paste0("总体入组率（人/",u,"）"));update("hg_enroll_cuts","duration_text",paste0("入组切点（",u,"）"));update("hg_enroll_rates","rate_text",paste0("各段总体入组率（人/",u,"）"))
    for(pre in prefixes){for(kind in names(base_unit_fields))for(k in intersect(base_unit_fields[[kind]],names(simulation_defaults(from)))){label<-switch(k,median=paste0("中位时间（",u,"；治愈模型为未治愈成分）"),median2=paste0("第二成分中位时间（",u,"）"),eta=paste0("Weibull尺度eta（",u,"）"),log_mu=paste0("对数位置mu=log(m/",u,")"),exp_rate=paste0("指数风险率（每",u,"）"),g_rate=paste0("初始风险率（每",u,"）"),g_shape=paste0("Gompertz形状（每",u,"）"),parameter_cuts=paste0("风险切点（",u,"）"),parameter_rates=paste0("各段风险率（每",u,"）"),dropout_rate=paste0("独立脱落风险率（每",u,"）"),drop_period=paste0("脱落概率窗口（",u,"）"),NULL);update(paste0(pre,k),kind,label)};update(paste0(pre,"survival_time"),"duration",paste0("随访时点（",u,"）"));update(paste0(pre,"pwe_last_rate"),"rate",paste0("末段风险率（每",u,"）"))};previous(to)
  },ignoreInit=TRUE)
  register_research_workbench_server(input,output,session,controller,"hg_","heterogeneous_survival","heterogeneity","hg_tabs",function()heterogeneity_input(input),hg_sample,hg_report,"run_heterogeneity",extra="recovery")
  output$hg_template<-downloadHandler(filename="heterogeneity_scenarios.csv",content=function(file)write.csv(data.frame(label=c("null_no_frailty","active_heterogeneous"),n=300,hr_scale=c(1,.67),center_sd=c(0,.3),subject_variance=c(0,.5)),file,row.names=FALSE))
}
