# Deterministic expected clinical events: initial cohort + finite uniform accrual.
rc_validate <- function(c){
  if(!c$solve %in% c("hazard","future_n","dco","survival")||!c$model$id %in% c("exponential","weibull","pwe","gompertz","lognormal","loglogistic"))stop("选择求解变量及支持的基准模型。")
  ma_validate_model(c$model);time_factor(c$display_unit)
  if(length(c$bounds)!=2||any(!is.finite(c$bounds))||c$bounds[1]>=c$bounds[2])stop("求解下界须小于上界，均为有限值。")
  if(c$solve %in% c("hazard","survival")&&any(c$bounds<.001|c$bounds>100)||c$solve=="dco"&&any(c$bounds<0|c$bounds>3650)||c$solve=="future_n"&&any(c$bounds<0|c$bounds>100000))stop("风险倍数界0.001–100，DCO界0–3650日，未来N界0–100000。")
  if(!ma_scalar(c$survival_age,1e-6,3650)||!ma_scalar(c$survival_target,.0001,.9999))stop("生存参考年龄正≤3650日，目标生存率0.0001–0.9999。")
  if(c$solve=="survival")return(invisible(TRUE))
  if(!ma_integer(c$n0,0,100000)||!ma_integer(c$future_n,0,100000)||c$n0+c$future_n<1||!ma_scalar(c$accrual_day,1e-6,3650)||!ma_scalar(c$dco_day,1e-6,3650)||!ma_scalar(c$dropout_rate,0,1e5)||!ma_scalar(c$hazard_q,.001,100)||!ma_scalar(c$target_events,0,200000))stop("初始/未来计划N非负整数且总N正；入组期/DCO≤3650日，退出非负，风险倍数0.001–100，目标事件数非负。")
  invisible(TRUE)
}
rc_density <- function(m,t,q,mu){H<-model_cumhaz(m,t);v<-log(q)+fx_density_any(m,t)+(1-q)*H-mu*t;v[is.infinite(H)&H>0]<--Inf;exp(v)}
rc_integral <- function(m,T,q,mu,A=NULL){if(T<=0)return(0);cuts<-sort(unique(c(0,T,as.numeric(m$cuts %||% numeric()),if(!is.null(A)&&T>A)T-A)));cuts<-cuts[cuts>=0&cuts<=T];values<-vapply(seq_len(length(cuts)-1L),function(j){lo<-cuts[j];hi<-cuts[j+1L];if(hi<=lo)return(0);a<-integrate(function(t){v<-rc_density(m,t,q,mu);if(!is.null(A))v<-v*pmin(pmax((T-t)/A,0),1);v},lo,hi,subdivisions=300L,rel.tol=1e-7,abs.tol=1e-9,stop.on.error=TRUE);a$value},numeric(1));sum(values)}
rc_expectation <- function(c,q=c$hazard_q,N=c$future_n,T=c$dco_day){initial<-if(T<=0)0 else if(c$dropout_rate==0)-expm1(-q*model_cumhaz(c$model,T)) else rc_integral(c$model,T,q,c$dropout_rate);future<-rc_integral(c$model,T,q,c$dropout_rate,c$accrual_day);list(total=c$n0*initial+N*future,initial=c$n0*initial,future=N*future,initial_probability=initial,future_probability=future,expected_entered=c$n0+N*min(T/c$accrual_day,1))}
run_reverse_calibration <- function(c){rc_validate(c);trace<-list();evaluate<-function(x){a<-switch(c$solve,hazard=rc_expectation(c,q=x),future_n=rc_expectation(c,N=x),dco=rc_expectation(c,T=x),survival=list(total=model_survival(c$model,c$survival_age)^x));target<-if(c$solve=="survival")c$survival_target else c$target_events;trace[[length(trace)+1L]]<<-data.frame(value=x,expected=a$total,target=target,residual=a$total-target);a$total-target}
  if(c$solve=="survival"){H<-model_cumhaz(c$model,c$survival_age);if(!is.finite(H)||H<=0)stop("该模型参考年龄风险没有有限正值，不能反求风险倍数。");value<--log(c$survival_target)/H;if(value<c$bounds[1]||value>c$bounds[2])stop("生存率反求风险倍数不在预定区间；不自动扩展。");evaluate(value);solved<-c;solved$hazard_q<-value;grid<-seq(0,c$survival_age*2,length.out=61);return(list(config=c,solved=solved,overview=data.frame(solve="survival",solution=value,unit="hazard_multiplier",target=c$survival_target,expected_survival_at_age=exp(-value*H),residual=exp(-value*H)-c$survival_target,solver_lower=c$bounds[1],solver_upper=c$bounds[2]),trace=batch_bind_columns(trace),curve=data.frame(day=grid,survival=exp(-value*model_cumhaz(c$model,grid))),version=batch_version,source_hash=batch_source_hash(),dependencies=batch_dependencies(list()),review_status="pending_v0.35_review",note="单一参考年龄潜在事件生存率反求共同风险倍数；不读取入组、退出或人数。"))}
  else {lo<-evaluate(c$bounds[1]);hi<-evaluate(c$bounds[2]);if(lo>0||hi<0)stop(paste0("目标不在预定区间支持内；下界残差",signif(lo,6),"，上界残差",signif(hi,6),"。不自动放宽区间。"));if(lo==0)value<-c$bounds[1] else if(hi==0)value<-c$bounds[2] else value<-uniroot(evaluate,c$bounds,tol=1e-7)$root}
  solved<-c;if(c$solve %in% c("hazard","survival"))solved$hazard_q<-value else if(c$solve=="future_n")solved$future_n<-value else solved$dco_day<-value;expect<-rc_expectation(solved);rounded<-if(c$solve=="future_n")ceiling(value) else NA_real_;roundexpect<-if(is.finite(rounded))rc_expectation(solved,N=rounded)$total else NA_real_;overview<-data.frame(solve=c$solve,solution=value,unit=if(c$solve=="dco")"days" else if(c$solve=="future_n")"persons" else "hazard_multiplier",expected_events=expect$total,expected_initial_events=expect$initial,expected_future_events=expect$future,expected_entered=expect$expected_entered,target=if(c$solve=="survival")c$survival_target else c$target_events,residual=if(c$solve=="survival")model_survival(c$model,c$survival_age)^value-c$survival_target else expect$total-c$target_events,rounded_future_n=rounded,rounded_expected_events=roundexpect,expected_survival_at_age=model_survival(c$model,c$survival_age)^solved$hazard_q,solver_lower=c$bounds[1],solver_upper=c$bounds[2]);grid<-seq(0,max(solved$dco_day,c$dco_day),length.out=61);curve<-batch_bind_columns(lapply(grid,function(t){a<-rc_expectation(solved,T=t);data.frame(day=t,expected_events=a$total,initial_events=a$initial,future_events=a$future,expected_entered=a$expected_entered)}));list(config=c,solved=solved,overview=overview,trace=batch_bind_columns(trace),curve=curve,version=batch_version,source_hash=batch_source_hash(),dependencies=batch_dependencies(list()),review_status="pending_v0.35_review",note="确定性期望临床事件，不是预测区间/功效/积压发布；初始队列年龄0、未来计划人数均匀入组、独立指数退出。")} 
rc_report <- function(r)c("# 期望事件反向校准开发稿",r$note,capture.output(print(r$overview,row.names=FALSE)),"只改变一个指定变量，其余参数冻结。固定有限计划入组均匀分布；尚未入组患者仅在其入组后贡献事件。风险倍数乘累计风险，不改变入组/退出机制。目标需处于预定求解区间，人数整数使用向上取整并重新给出期望。求解残差不是方法或数值校准通过证明。待验证。")
