round_three_values <- function(input,pre,unit,index=1L){d<-joint_defaults(unit,index);for(k in names(d))if(!is.null(input[[paste0(pre,k)]]))d[[k]]<-input[[paste0(pre,k)]];d}
ms_input <- function(input){u<-input$ms_unit %||% "months";f<-time_factor(u);cut<-input$ms_cut*f;source<-input$ms_data_source
  if(source=="parameters"){
    d<-batch_bind_columns(lapply(c("control","treatment"),function(g){pre<-paste0("ms_",g,"_");n0<-input[[paste0(pre,"n0")]];n1<-input[[paste0(pre,"n1")]];age<-input[[paste0(pre,"age")]]*f;p<-input[[paste0(pre,"prog")]]*f;if(any(c(n0,n1)<0)||any(c(n0,n1)!=floor(c(n0,n1)))||age<0||age>cut||n1>0&&(p<=0||p>age))stop("参数状态人数需非负整数，年龄≤IA，进展年龄须在(0,随访年龄]。");N<-n0+n1;if(!N)return(data.frame());data.frame(USUBJID=paste0(toupper(g),"_",seq_len(N)),GROUP=if(g=="control")"Control" else "Treatment",ENTRY=cut-age,TIME=age,STATE=c(rep(0L,n0),rep(1L,n1)),EXIT="active",PROG=c(rep(NA_real_,n0),rep(p,n1)))}));d<-ms_snapshot(d,cut)
  }else{if(is.null(input$ms_file))stop("请提供IA记录CSV。");raw<-read.csv(input$ms_file$datapath,check.names=FALSE,stringsAsFactors=FALSE);d<-if(source=="adtte")ms_from_adtte(raw,cut) else ms_snapshot(raw,cut,input$ms_file_unit)}
  if(!all(d$GROUP %in% c("Control","Treatment")))stop("GROUP需Control/Treatment。")
  specs<-setNames(lapply(seq_along(joint_transition_names),function(i){tr<-names(joint_transition_names)[i];pre<-paste0("ms",tr,"_");s<-if(source=="parameters")"parameters" else input[[paste0(pre,"source")]];if(s=="fit")list(source=s,method=input[[paste0(pre,"fit_method")]],cuts=if(input[[paste0(pre,"fit_method")]]=="pwe")parse_unit_numbers(input[[paste0(pre,"fit_cuts")]])*f else numeric()) else {v<-round_three_values(input,pre,u,i);list(source=s,model=parameter_input_model(v$design_model,v,u),treatment_q=input[[paste0("ms_q",tr)]])}}),names(joint_transition_names))
  cfg<-list(research_family="multistate_conditional",mode="conditional",design_mode="fixed",effect_mode="joint_transition",purpose=input$ms_purpose,primary="prediction",alpha=.025,sided="benefit",paramcd="PFS+OS",display_unit=u,engine_unit="days",origin=as.character(input$ms_origin),data=d,cut=cut,clock=input$ms_clock,transition_specs=specs,uncertainty=input$ms_uncertainty,group_weights=c(Control=1-input$ms_allocation,Treatment=input$ms_allocation),dropout_rates=c(Control=input$ms_drop_control,Treatment=input$ms_drop_treatment)/f,new_n=input$ms_new_n,enroll_rate=input$ms_enroll_rate/f,max_day=input$ms_max*f,reps=input$ms_reps,seed=input$ms_seed,cut_rule=input$ms_purpose,filter_enabled=FALSE,reference_scenario=1)
  if(cfg$purpose=="counts")cfg$horizons<-parse_unit_numbers(input$ms_horizons)*f else {cfg$target_endpoint<-input$ms_target_endpoint;cfg$target<-input$ms_target}
  validate_multistate(cfg);cfg
}
je_input <- function(input){u<-input$je_unit %||% "months";f<-time_factor(u);purpose<-input$je_purpose;v<-round_three_values(input,"je01_",u);death<-if(input$je_death_basis=="rate")input$je_death_rate/f else log(2)/(input$je_death_median*f);w<-parse_unit_numbers(input$je_mixture_weights)
  cfg<-list(research_family="joint_sequential_likelihood",mode=if(purpose=="design")"fixed_truth" else "conditional",design_mode="likelihood_sequential",effect_mode="state_invariant_death",purpose=purpose,primary=if(purpose=="observed")"original" else input$je_primary,compare_methods=if(purpose!="observed"&&isTRUE(input$je_compare))setdiff(names(je_names),input$je_primary) else character(),paramcd="PFS+OS",sided="benefit",alpha=input$je_alpha,display_unit=u,engine_unit="days",origin=as.character(input$je_origin),progression_model=parameter_input_model(v$design_model,v,u),death_model=list(id="exponential",params=c(rate=death),label="状态无关指数死亡"),predeclared=isTRUE(input$je_predeclared),mixture_hr=parse_unit_numbers(input$je_mixture_hr),mixture_weights=w/sum(w),policy=input$je_policy,success_goal=if(input$je_policy=="co_primary")"both" else input$je_success_goal,pfs_alpha_weight=input$je_weight,first_endpoint=input$je_first,cut=if(purpose=="design")0 else input$je_cut*f,seed=input$je_seed,filter_enabled=FALSE,reference_scenario=1)
  if(purpose!="design"){if(is.null(input$je_data_file))stop("请提供精确IA状态CSV。");cfg$data<-ms_snapshot(read.csv(input$je_data_file$datapath,check.names=FALSE,stringsAsFactors=FALSE),cfg$cut,input$je_file_unit)}
  if(purpose!="observed"){cfg<-c(cfg,list(reps=input$je_reps,monitor_endpoint=input$je_monitor,cut_rule="event_sequence",dplan=input$je_dplan,dmax=input$je_dmax,pilot_target=if(purpose=="design")input$je_d1 else NULL,max_day=input$je_max*f,enroll_rate=input$je_enroll_rate/f,treatment_fraction=input$je_allocation,dropout_rates=c(Control=input$je_drop_control,Treatment=input$je_drop_treatment)/f,look_fractions=parse_unit_numbers(input$je_look_fractions),adapt_rule=input$je_adapt_rule,cp_reps=input$je_cp_reps,cp_min=input$je_cp_min,cp_target=input$je_cp_target,inflation=input$je_inflation,planning_q01=input$je_planning_q01,planning_qdeath=input$je_planning_qdeath,scenario_table=read.csv(text=input$je_scenario_csv,check.names=FALSE,stringsAsFactors=FALSE)))}else{cfg$reps<-1L;cfg$monitor_endpoint<-"PFS";cfg$adapt_rule<-"promising";cfg$scenario_table<-data.frame(label="当前观察",n=max(10L,nrow(cfg$data)),q01=1,qdeath=1,enroll_scale=1,dropout_scale=1)}
  validate_joint_sequential(cfg);cfg
}
register_round_three_units <- function(input,output,session,pre,prefixes,specs){u<-reactive(input[[paste0(pre,"unit")]] %||% "months");previous<-reactiveVal("months");register_parameter_controls(input,output,session,u,prefixes,joint_defaults,parameter_input_model)
  observeEvent(input[[paste0(pre,"unit")]],{to<-u();from<-previous();if(to==from)return();ratio<-time_factor(from)/time_factor(to);for(k in names(specs))for(id in specs[[k]]){v<-isolate(input[[id]]);if(is.null(v))next;val<-tryCatch(if(k %in% c("duration_text","rate_text"))paste(format(parse_unit_numbers(v)*if(k=="duration_text")ratio else 1/ratio,digits=16,trim=TRUE),collapse=",") else v*if(k=="duration")ratio else 1/ratio,error=function(e)v);freezeReactiveValue(input,id);base<-if(grepl("median$",id))"中位时间" else if(grepl("eta$",id))"Weibull尺度eta" else if(grepl("fit_cuts$",id))"拟合风险切点" else if(grepl("parameter_cuts$",id))"参数风险切点" else if(grepl("parameter_rates$",id))"各段风险率" else if(grepl("exp_rate$|death_rate$",id))"指数风险率" else if(grepl("_age$",id))"共同随访年龄" else if(grepl("_prog$",id))"进展年龄" else switch(id,ms_cut="IA研究时间",je_cut="IA研究时间",ms_max="最大研究时间",je_max="最大研究时间",ms_horizons="未来研究时点",ms_enroll_rate="总体入组率",je_enroll_rate="总体入组率",ms_drop_control="Control永久退出风险",je_drop_control="Control永久退出风险",ms_drop_treatment="Treatment永久退出风险",je_drop_treatment="Treatment永久退出风险","风险参数");label<-paste0(base,"（",if(k %in% c("rate","rate_text"))"每" else "",time_label(to),"）");if(k %in% c("duration_text","rate_text"))updateTextInput(session,id,label=parameter_label(id,label),value=val) else updateNumericInput(session,id,label=parameter_label(id,label),value=val)};previous(to)},ignoreInit=TRUE)
  invisible(u)
}
register_round_three_server <- function(input,output,session,controller){specs<-function(pre,tr){p<-paste0(pre,tr,"_");list(duration=paste0(p,rep(c("median","eta"),each=length(tr))),rate=paste0(p,"exp_rate"),duration_text=paste0(p,"parameter_cuts"),rate_text=paste0(p,"parameter_rates"))}
  # Explicit vectors avoid mixing parameter labels or changing dimensionless values.
  ms_specs<-list(duration=c("ms_cut","ms_max",paste0("ms_",rep(c("control","treatment"),each=2),"_",rep(c("age","prog"),2)),unlist(lapply(c("01","02","12"),function(tr)paste0("ms",tr,"_",c("median","eta"))))),rate=c("ms_enroll_rate","ms_drop_control","ms_drop_treatment",paste0("ms",c("01","02","12"),"_exp_rate")),duration_text=c("ms_horizons",paste0("ms",c("01","02","12"),"_parameter_cuts"),paste0("ms",c("01","02","12"),"_fit_cuts")),rate_text=paste0("ms",c("01","02","12"),"_parameter_rates"))
  register_round_three_units(input,output,session,"ms_",paste0("ms",c("01","02","12"),"_"),ms_specs)
  je_specs<-list(duration=c("je_cut","je_max","je_death_median","je01_median","je01_eta"),rate=c("je_enroll_rate","je_drop_control","je_drop_treatment","je_death_rate","je01_exp_rate"),duration_text="je01_parameter_cuts",rate_text="je01_parameter_rates")
  register_round_three_units(input,output,session,"je_","je01_",je_specs)
  previous_death<-reactiveVal("median");observeEvent(input$je_death_basis,{to<-input$je_death_basis;from<-previous_death();if(to==from)return();if(to=="rate")updateNumericInput(session,"je_death_rate",value=log(2)/isolate(input$je_death_median)) else updateNumericInput(session,"je_death_median",value=log(2)/isolate(input$je_death_rate));previous_death(to)},ignoreInit=TRUE)
  ms<-register_research_workbench_server(input,output,session,controller,"ms_","multistate_conditional","multistate","ms_tabs",function()ms_input(input),ms_sample,ms_report,"run_multistate",extra=c("count_overview","target_overview","model_overview"),input_tabs=c("ms_inputs","ms_plan"))
  je<-register_research_workbench_server(input,output,session,controller,"je_","joint_sequential_likelihood","joint_sequential","je_tabs",function()je_input(input),je_sample,je_report,"run_joint_sequential",extra="ia_overview",input_tabs=c("je_inputs","je_plan"))
  observe({if(identical(input$je_purpose,"observed")||(input$je_run_source %||% "ui")=="config_json")nav_hide("je_tabs","je_plan",session=session) else nav_show("je_tabs","je_plan",session=session)})
  # Current-observation evidence is synchronous and never requests future patients.
  evidence<-reactiveVal(NULL);evidence_error<-reactiveVal(NULL)
  observeEvent(input$je_observed_run,{evidence(NULL);evidence_error(NULL);tryCatch({cfg<-je$configuration();if(is.null(cfg))stop("先载入有效配置。");if(cfg$purpose!="observed")stop("先选择当前观察证据。");a<-je_observed(cfg);a$config<-cfg;evidence(a);nav_select("je_tabs","je_results",session=session)},error=function(e)evidence_error(conditionMessage(e)))},ignoreInit=TRUE)
  output$je_observed_note<-renderUI({a<-evidence();tagList(if(!is.null(evidence_error()))p(class="field-note",evidence_error()),if(!is.null(a))p(class="field-note",a$note))})
  output$je_observed_statistics<-renderDT({a<-evidence();req(a);study_table(a$statistics)})
  output$je_observed_evidence_download<-downloadHandler(filename="joint_current_evidence.csv",content=function(file){a<-evidence();req(a);write.csv(a$statistics,file,row.names=FALSE)})
  output$je_observed_config_download<-downloadHandler(filename="joint_current_evidence_config.json",content=function(file){a<-evidence();req(a);jsonlite::write_json(batch_config_document(a$config),file,auto_unbox=TRUE,pretty=TRUE,digits=NA)})
  output$ms_intervals_download<-downloadHandler(filename="multistate_frozen_intervals_days.csv",content=function(file)write.csv(ms$sample()$intervals,file,row.names=FALSE))
  output$je_frozen_download<-downloadHandler(filename="joint_selected_frozen_ia_days.csv",content=function(file)write.csv(je$sample()$frozen_ia,file,row.names=FALSE))
  for(pre0 in c("ms_","je_"))local({pre<-pre0;output[[paste0(pre,"template")]]<-downloadHandler(filename="exact_state_snapshot.csv",content=function(file)write.csv(data.frame(USUBJID=c("C01","T01","T02"),GROUP=c("Control","Treatment","Treatment"),ENTRY=c(0,0,1),TIME=c(6,6,4),STATE=c(0,1,2),EXIT=c("active","active","event"),PROG=c(NA,3,NA)),file,row.names=FALSE))})
  # Override single-endpoint ADTTE export for these shared-patient families.
  for(pre0 in c("ms_","je_"))local({pre<-pre0;bridge<-if(pre=="ms_")ms else je;output[[paste0(pre,"adtte_download")]]<-downloadHandler(filename="joint_selected_adtte.csv",content=function(file){a<-bridge$sample();write.csv(ms_adtte(a$observed,a$study_config),file,row.names=FALSE)})})
  invisible(list(multistate=ms,joint=je))
}
