round_three_help <- function(){h<-get("parameter_help",envir=parent.frame())
  for(ns in c("ms","je"))for(tr in c("01","02","12"))for(k in c("design_model","exp_input","median","exp_rate","weibull_input","eta","shape","parameter_cuts","parameter_rates")){src<-paste0("js",tr,"_",k);if(src %in% names(h))h[paste0(ns,tr,"_",k)]<-h[[src]]}
  for(pre in c("ms_","je_"))for(k in c("run_source","run_name","config_file","reps","seed","view_scenario","view_trial","sample_run"))h[paste0(pre,k)]<-h[paste0("hg_",k)]
  extra<-c(ms_purpose="未来各时点事件数，或单一终点达标日期二选一；只填写该需求参数。",ms_data_source="无数据用已知状态人数和参数；有数据用精确状态CSV或双终点ADTTE。拟合仅用于实际记录。",ms_file="状态CSV七列USUBJID,GROUP,ENTRY,TIME,STATE,EXIT,PROG；双终点ADTTE使用连续日ENGINE字段。参见模板和手册44章。",ms_cut="IA研究经过时间，参数记录和active须确认到此时点，不能用最后一次访视当成IA。",ms_file_unit="状态CSV的ENTRY/TIME/PROG单位；双终点ADTTE ENGINE始终为日。改变显示单位不改变文件解释。",ms_clock="12进展后时间reset，或自入组时间forward；后者拟合需减去进入状态1前的累计风险。",ms_uncertainty="固定拟合参数plugin，或组内按完整患者路径有放回Bootstrap；拟合失败保留未知，B建议100起。",ms_horizons="从研究起点计算的未来截点列表，全部IA之后，例如12,18,24月。",ms_target_endpoint="只选择一个累计事件目标的触发终点PFS/OS；另一个终点在同一截点显示。",ms_target="累计事件目标含IA已知事件；正整数，已达目标则达标日期为IA。",ms_new_n="IA后新增人数，0表示仅旧患者续推；旧加新≤5000。",ms_enroll_rate="未来总体Poisson率，人/当前单位；只有新增人数>0才读取。",ms_max="最大研究经过时间，IA之后、最长3650日；不是从IA另计的窗口长度。",ms_allocation="未来Treatment分配概率，0.01–0.99；旧患者组别保留。",ms_q01="参数转移模型的Treatment风险倍数；不作用于按组实际拟合的转移。",ms_q02="参数02的Treatment风险倍数；不是边际OS HR。",ms_q12="参数12的Treatment风险倍数；适用时钟由clock决定。",
  je_purpose="设计阶段仅参数；实际IA条件研究或当前观察推断需精确状态记录。观察推断不读取未来计划/B。",je_data_file="实际IA七列状态CSV，组别必须Control/Treatment；模型和混合须事先指定，不能自动使用ms拟合结果。",je_predeclared="确认已知基准风险、混合节点/权重及联合规则在本研究结局查看之前指定；未确认则不运行正式检验。",je_policy="共同主要、加权Bonferroni、Holm或固定顺序，作用于各终点运行最大E的p=1/maxE；不假设两终点独立。",je_success_goal="运行前预定至少一个/两个/指定终点声明；共同主要固定为两者。",je_alpha="总体预定alpha，例如0.025；逐终点E的证据保护依赖各真零假设指定风险正确。",je_weight="加权Bonferroni的PFS权重w，OS为1-w，默认0.5；无事后alpha回收。",je_first="固定顺序预定首终点；首终点未声明不能声明第二终点。",je_mixture_hr="获益混合节点r在(0,1)，例如0.5,0.67,0.85；PFS按总强度倍数构造备择，OS按死亡风险倍数。",je_mixture_weights="与节点数一致的正权重，输入后归一化；原混合贯穿IA与Final，不能看数据后重建。",je_scenario_csv="严格六列label,n,q01,qdeath,enroll_scale,dropout_scale；qdeath同时用于02/12，OS因此保持指数PH，PFS通常非PH。",je_monitor="选择共同分析截点的触发终点，PFS或OS；两终点同一DCO查看。",je_d1="设计阶段首次规划IA的累计触发事件目标，正整数且小于Dplan。",je_dplan="原Final累计触发目标，实际IA时须大于已知事件数。",je_dmax="重估上限≥Dplan；事件目标增加不修改检验混合或alpha。",je_look_fractions="IA已知事件至选定Final目标之间的未来比例，正递增、末次1，例如0.5,1；最多10次。",je_primary="原事件计划或预定重估为主，附加规则同轮比较，禁止按结果择优。",je_adapt_rule="上下限：规划CP低于目标则增加；Promising：CP在CPmin至目标内增加。",je_cp_reps="IA条件下规划模拟次数M10–200；建议20起，有限M只决定目标，不保证达到CP。",je_cp_target="规划成功概率目标0–1，例如0.9；计算只比较IA/原Final，与未来更多分析次数区别记录。",je_cp_min="Promising最低规划CP，默认0.2，必须低于CPtarget。",je_inflation="增加事件目标的固定倍数1–5，默认1.25，受Dmax截断；不迭代搜索最优事件数。",je_planning_q01="IA规划预测进展倍数，须预先设定，例如0.7；不读取外层模拟真实情景的q。",je_planning_qdeath="规划预测02/12共同死亡倍数，例如0.85；基准风险保持外部已知。",je_death_basis="已知死亡风险可由指数中位时间或率输入；02与12完全相同，不能以一般OS中位数替代。",je_death_median="状态无关指数死亡风险的中位时间m>0，lambda=log2/m；例24月。",je_death_rate="状态0和1相同的死亡风险lambda>0，每当前单位。",
  ms_unit="显示/页面参数日、周、月；默认月；时间和风险率同步转换。",je_unit="默认月，可选日/周/月；内部连续日，已知风险和窗口同步转换。")
  for(pre in c("ms_","je_")){for(k in c("origin","cut","file_unit","max","allocation","enroll_rate","drop_control","drop_treatment")){id<-paste0(pre,k);if(!id %in% names(extra))extra[id]<-switch(k,origin="研究起点日期，用于导出日期。",cut="IA自研究起点经过时间；仍随访需确认到此时点。",file_unit="状态文件时间单位，独立于页面显示单位。",max="最大研究经过时间，IA之后且≤3650日。",allocation="未来Treatment简单随机分配概率，默认0.5。",enroll_rate="总体未来Poisson入组率，人/当前单位，例20人/月。","独立永久退出风险，非负，每当前单位；不等于停药。")}}
  for(g in c("control","treatment"))for(k in c("n0","n1","age","prog"))extra[paste0("ms_",g,"_",k)]<-switch(k,n0="IA尚未进展且仍随访人数，非负整数。",n1="IA已进展且仍随访人数，非负整数；PFS已知、OS待观察。",age="此组参数记录入组至IA的共同随访年龄，不超过IA。",prog="此组已进展患者的共同进展年龄，须正且不超过随访年龄。")
  for(tr in c("01","02","12")){extra[paste0("ms",tr,"_source")]<-"本转移二选一：按组实际精确路径拟合，或指定参数。参数记录模式仅指定；无风险暴露的转移须指定参数。";extra[paste0("ms",tr,"_fit_method")]<-"指数、Weibull或PWE；Weibull每组此转移至少2事件；PWE每段须有风险暴露。";extra[paste0("ms",tr,"_fit_cuts")]<-"拟合PWE风险年龄切点，正递增；12按所选时钟解释。例3,6月。"}
  h[names(extra)]<-extra;assign("parameter_help",h,envir=parent.frame())
}
ms_state_entry_ui <- function(g,label){pre<-paste0("ms_",g,"_");section(label,fields(numericInput(paste0(pre,"n0"),"IA未进展仍随访人数",50,min=0,step=1),numericInput(paste0(pre,"n1"),"IA已进展仍随访人数",10,min=0,step=1)),fields(numericInput(paste0(pre,"age"),"共同随访年龄（月）",6,min=0),numericInput(paste0(pre,"prog"),"已进展的进展年龄（月）",3,min=.001)))}
round_three_process_ui <- function(pre){tagList(fields(selectInput(paste0(pre,"unit"),"时间单位",c("日"="days","周"="weeks","月"="months"),"months"),dateInput(paste0(pre,"origin"),"研究起点","2025-01-01")),fields(numericInput(paste0(pre,"enroll_rate"),"总体入组率（人/月）",20,min=.001),numericInput(paste0(pre,"allocation"),"未来Treatment分配概率",.5,min=.01,max=.99)),fields(numericInput(paste0(pre,"drop_control"),"Control永久退出风险（每月）",.01,min=0),numericInput(paste0(pre,"drop_treatment"),"Treatment永久退出风险（每月）",.01,min=0)),numericInput(paste0(pre,"max"),"最大研究时间（月）",36,min=.001))}
multistate_ui <- function(){nav_panel("多状态条件预测",value="multistate",div(class="page-title",h2("多状态模型拟合与条件预测"),actionButton("ms_run","运行条件预测",class="btn-primary"),actionButton("ms_cancel","取消后台研究")),
  section("本次需求",selectInput("ms_purpose","需求",c("各未来时点事件数"="counts","累计事件达标日期"="target")),radioButtons("ms_run_source","参数来源",c("填写页面参数"="ui","无损JSON"="config_json"),inline=TRUE),textInput("ms_run_name","研究名称","多状态条件预测"),conditionalPanel("input.ms_run_source === 'config_json'",fileInput("ms_config_file","配置JSON",accept=".json"),uiOutput("ms_import_note"))),
  navset_card_tab(id="ms_tabs",nav_panel("IA记录与模型",value="ms_inputs",
    section("IA输入",selectInput("ms_data_source","输入方式",c("已知状态人数和参数"="parameters","精确状态CSV"="state","双终点ADTTE"="adtte")),numericInput("ms_cut","IA研究时间（月）",6,min=0),conditionalPanel("input.ms_data_source !== 'parameters'",fileInput("ms_file","IA记录CSV",accept=".csv"),conditionalPanel("input.ms_data_source === 'state'",selectInput("ms_file_unit","状态CSV时间单位",c("日"="days","周"="weeks","月"="months"),"months")),downloadButton("ms_template","精确状态CSV模板"),p(class="field-note","状态CSV：USUBJID,GROUP,ENTRY,TIME,STATE,EXIT,PROG。GROUP为Control/Treatment；STATE为0/1/2；PROG是入组至进展的时长。ADTTE需两终点及ENGINE连续日字段。")),conditionalPanel("input.ms_data_source === 'parameters'",ms_state_entry_ui("control","Control当前状态"),ms_state_entry_ui("treatment","Treatment当前状态"))),
    section("模型处理",selectInput("ms_clock","12风险时钟",c("进展后起算"="reset","自入组起算"="forward")),selectInput("ms_uncertainty","参数不确定性",c("固定参数plugin"="plugin","患者Bootstrap重拟合"="bootstrap"))),
    lapply(seq_along(joint_transition_names),function(i){tr<-names(joint_transition_names)[i];section(joint_transition_names[[tr]],conditionalPanel("input.ms_data_source !== 'parameters'",selectInput(paste0("ms",tr,"_source"),"本转移参数来源",c("按组实际路径拟合"="fit","指定参数"="parameters"))),conditionalPanel(paste0("input.ms_data_source !== 'parameters' && input.ms",tr,"_source === 'fit'"),selectInput(paste0("ms",tr,"_fit_method"),"拟合模型",c("指数"="exponential","Weibull"="weibull","PWE"="pwe")),conditionalPanel(paste0("input.ms",tr,"_fit_method === 'pwe'"),textInput(paste0("ms",tr,"_fit_cuts"),"拟合切点（月）","3,6"))),conditionalPanel(paste0("input.ms_data_source === 'parameters' || input.ms",tr,"_source === 'parameters'"),joint_transition_ui(tr,i,namespace="ms"),numericInput(paste0("ms_q",tr),"Treatment参数转移风险倍数",1,min=.01,max=100)))})),
    nav_panel("未来过程与运行",value="ms_plan",section("未来过程",round_three_process_ui("ms_"),numericInput("ms_new_n","IA后新增人数",100,min=0,step=1)),conditionalPanel("input.ms_purpose === 'counts'",section("事件数截点",textInput("ms_horizons","未来研究时点（月）","12,18,24"))),conditionalPanel("input.ms_purpose === 'target'",section("累计事件目标",fields(selectInput("ms_target_endpoint","触发终点",c("PFS","OS")),numericInput("ms_target","累计目标D*",150,min=1,step=1)))),section("重复预测",fields(numericInput("ms_reps","重复数B",100,min=20,max=10000),numericInput("ms_seed","种子",20261005,min=0,max=2147483647)))),
    nav_panel("结果",value="ms_results",ms_result_panels()),ms_export_panel(),nav_panel("状态路径导出",value="ms_paths",downloadButton("ms_intervals_download","冻结IA风险区间CSV")) ))}
joint_sequential_ui <- function(){nav_panel("联合序贯与重估",value="joint_sequential",div(class="page-title",h2("PFS/OS联合序贯与事件目标重估"),conditionalPanel("input.je_purpose !== 'observed'",actionButton("je_run","运行联合研究",class="btn-primary")),conditionalPanel("input.je_purpose === 'observed'",actionButton("je_observed_run","计算当前证据",class="btn-primary")),actionButton("je_cancel","取消后台研究")),
  section("本次需求",selectInput("je_purpose","需求",c("设计阶段重复研究"="design","实际IA条件研究"="conditional","当前观察证据"="observed")),radioButtons("je_run_source","参数来源",c("填写页面参数"="ui","无损JSON"="config_json"),inline=TRUE),textInput("je_run_name","研究名称","联合序贯研究"),conditionalPanel("input.je_run_source === 'config_json'",fileInput("je_config_file","配置JSON",accept=".json"),uiOutput("je_import_note"))),
  navset_card_tab(id="je_tabs",nav_panel("已知模型与原检验",value="je_inputs",section("时间与原模型",fields(selectInput("je_unit","时间单位",c("日"="days","周"="weeks","月"="months"),"months"),dateInput("je_origin","研究起点","2025-01-01")),checkboxInput("je_predeclared","模型、混合与联合规则已在查看本研究结局前指定",FALSE),p(class="field-note","本分支要求已知基准风险。02和12为相同指数死亡风险；一般三转移OS模型尚未接入正式检验。")),joint_transition_ui("01",1,namespace="je"),section("02与12共同已知死亡风险",selectInput("je_death_basis","指数参数",c("中位时间"="median","风险率"="rate")),conditionalPanel("input.je_death_basis === 'median'",numericInput("je_death_median","死亡中位时间（月）",24,min=.001)),conditionalPanel("input.je_death_basis === 'rate'",numericInput("je_death_rate","死亡风险率（每月）",log(2)/24,min=.000001))),
    conditionalPanel("input.je_purpose !== 'design'",section("实际IA",fileInput("je_data_file","精确状态CSV",accept=".csv"),fields(numericInput("je_cut","IA研究时间（月）",6,min=.001),selectInput("je_file_unit","状态CSV时间单位",c("日"="days","周"="weeks","月"="months"),"months")),downloadButton("je_template","状态CSV模板"))),
    section("预定混合",fields(textInput("je_mixture_hr","获益风险倍数节点","0.5,0.67,0.85"),textInput("je_mixture_weights","正权重","1,1,1"))),section("联合声明",selectInput("je_policy","联合规则",setNames(names(jr_policy_names)[1:4],unname(jr_policy_names[1:4])),"bonferroni"),conditionalPanel("input.je_policy !== 'co_primary'",selectInput("je_success_goal","主成功指标",c("至少一个终点"="any","两个终点"="both","PFS"="PFS","OS"="OS"))),numericInput("je_alpha","总体alpha",.025,min=.0001,max=.2),conditionalPanel("input.je_policy === 'bonferroni'",numericInput("je_weight","PFS alpha权重",.5,min=.01,max=.99)),conditionalPanel("input.je_policy === 'fixed_sequence'",selectInput("je_first","首终点",c("PFS","OS"))))),
    nav_panel("事件计划与情景",value="je_plan",section("研究过程",fields(numericInput("je_enroll_rate","总体入组率（人/月）",20,min=.001),numericInput("je_allocation","Treatment分配概率",.5,min=.01,max=.99)),fields(numericInput("je_drop_control","Control退出风险（每月）",.01,min=0),numericInput("je_drop_treatment","Treatment退出风险（每月）",.01,min=0)),numericInput("je_max","最大研究时间（月）",48,min=.001)),section("分析计划",selectInput("je_monitor","事件触发终点",c("PFS","OS")),conditionalPanel("input.je_purpose === 'design'",numericInput("je_d1","首次规划IA事件目标",80,min=1,step=1)),fields(numericInput("je_dplan","原Final事件目标",160,min=1,step=1),numericInput("je_dmax","重估事件上限",220,min=1,step=1)),textInput("je_look_fractions","未来分析比例","0.5,1"),selectInput("je_primary","主事件规则",setNames(names(je_names),unname(je_names)),"adaptive"),checkboxInput("je_compare","同轮比较另一事件规则",TRUE)),
    conditionalPanel("input.je_primary === 'adaptive' || input.je_compare",section("预定目标重估",selectInput("je_adapt_rule","重估规则",c("上下限"="bounded","Promising"="promising"),"promising"),fields(numericInput("je_cp_target","规划CP目标",.9,min=.001,max=.999),numericInput("je_cp_min","Promising最低CP",.2,min=0,max=.999)),fields(numericInput("je_cp_reps","规划预测次数M",20,min=10,max=200),numericInput("je_inflation","事件目标增加倍数",1.25,min=1,max=5)),fields(numericInput("je_planning_q01","规划进展风险倍数",.7,min=.01,max=10),numericInput("je_planning_qdeath","规划死亡风险倍数",.85,min=.01,max=10)))),section("外层情景",textAreaInput("je_scenario_csv","label,n,q01,qdeath,enroll_scale,dropout_scale","label,n,q01,qdeath,enroll_scale,dropout_scale\njoint_null,300,1,1,1,1\nactive,300,0.7,0.85,1,1",rows=4,width="100%"),fields(numericInput("je_reps","每情景B",100,min=20,max=10000),numericInput("je_seed","主种子",20261005,min=0,max=2147483647)))),
    nav_panel("结果",value="je_results",conditionalPanel("input.je_purpose === 'observed'",uiOutput("je_observed_note"),DTOutput("je_observed_statistics",fill=FALSE),downloadButton("je_observed_evidence_download","当前证据CSV"),downloadButton("je_observed_config_download","当前原配置JSON")),conditionalPanel("input.je_purpose !== 'observed'",research_result_panels("je_","联合序贯",c(ia_overview="实际IA原混合证据")))),research_export_panel("je_","联合序贯",c(ia_overview="IA证据CSV")),nav_panel("冻结状态导出",value="je_paths",downloadButton("je_frozen_download","所选轮次IA状态CSV")) ))}
ms_result_panels <- function()tagList(uiOutput("ms_status"),conditionalPanel("input.ms_purpose === 'counts'",section("累计与新增事件数",DTOutput("ms_count_overview",fill=FALSE))),conditionalPanel("input.ms_purpose === 'target'",section("达标日期与窗口达标概率",DTOutput("ms_target_overview",fill=FALSE))),section("转移模型与风险暴露",DTOutput("ms_model_overview",fill=FALSE)),section("关闭时间与资源",DTOutput("ms_resources",fill=FALSE)),section("观察样例",fields(selectInput("ms_view_scenario","保存情景",character()),selectInput("ms_view_trial","成功生成轮次",character())),actionButton("ms_sample_run","恢复所选轮次样例"),DTOutput("ms_sample_rows",fill=FALSE),DTOutput("ms_sample_observed",fill=FALSE)))
ms_export_panel <- function()nav_panel("导出与研究库",value="ms_exports",actionButton("ms_library","打开研究库"),div(class="export-bar",downloadButton("ms_rows_download","预测轮次CSV"),downloadButton("ms_draw_rows_download","截点事件数CSV"),conditionalPanel("input.ms_purpose === 'counts'",downloadButton("ms_count_overview_download","事件数分布CSV")),conditionalPanel("input.ms_purpose === 'target'",downloadButton("ms_target_overview_download","达标日期CSV")),downloadButton("ms_model_overview_download","模型CSV"),downloadButton("ms_resources_download","资源CSV"),downloadButton("ms_config_download","无损配置JSON"),downloadButton("ms_result_download","结果RDS"),downloadButton("ms_report_download","报告Markdown"),downloadButton("ms_script_download","复现R脚本"),downloadButton("ms_observed_download","所选双终点观察CSV"),downloadButton("ms_adtte_download","所选双终点ADTTE"),downloadButton("ms_truth_download","所选潜在真值CSV")))
