fp_input <- function(input){u<-input$fp_unit %||% "months";f<-time_factor(u);purpose<-input$fp_purpose;mode<-input$fp_analysis_mode;source<-if(input$fp_source=="parameters")"parameters" else "data";cut<-input$fp_cut*f
  cfg<-list(research_family="flexible_interval_prediction",purpose=purpose,source=source,analysis_mode=mode,mode="conditional",design_mode="fixed",effect_mode="assumed_blinded_ph",paramcd=input$fp_endpoint,primary="prediction",alpha=.025,sided="benefit",display_unit=u,engine_unit="days",origin=as.character(input$fp_origin),cut=cut,allocation=input$fp_allocation,assumed_hr=input$fp_assumed_hr,knots=if(nzchar(trimws(input$fp_knots)))parse_unit_numbers(input$fp_knots)*f else numeric(),tail=input$fp_tail*f,time_scale=input$fp_time_scale*f,rp_lower=(input$fp_rp_lower %||% .1)*f,reference_ages=parse_unit_numbers(input$fp_reference_ages)*f,seed=if(purpose=="fit")input$fp_fit_seed else input$fp_seed,filter_enabled=FALSE,reference_scenario=1,gap_mode=if(purpose=="fit")"complete" else input$fp_gap_mode)
  if(source=="parameters"){if(mode=="grouped")stop("按组参数尚未在此入口提供；选择合并/盲态参数，或上传已知组别记录。");n0<-if(purpose=="fit")0L else input$fp_active_n;n1<-if(purpose=="fit")0L else input$fp_known_n;age<-if(purpose=="fit")0 else input$fp_age*f;if(any(c(n0,n1)<0)||any(c(n0,n1)!=floor(c(n0,n1)))||age<0||age>cut||(n1>0&&age<=0))stop("状态人数非负整数，年龄0至IA，有事件时年龄须正。");N<-n0+n1;d<-data.frame(USUBJID=if(N)paste0("PARAM_",seq_len(N)) else character(),PARAMCD=rep(cfg$paramcd,N),ENTRY=rep(cut-age,N),L=rep(age,N),R=c(rep(Inf,n0),rep(age,n1)),TYPE=c(rep("right",n0),rep("exact",n1)),EXIT=c(rep("active",n0),rep("event",n1)),TRTP=rep("Combined",N));cfg$data<-d
    id<-input$fp_model;cfg$parameter_model<-switch(id,exponential={r<-if(input$fp_exp_basis=="rate")input$fp_rate/f else log(2)/(input$fp_median*f);list(id=id,label="指数",params=c(rate=r))},weibull=list(id=id,label="Weibull",params=c(location=log(input$fp_median*f/log(2)^(1/input$fp_shape)),scale=1/input$fp_shape)),gengamma=list(id=id,label="广义Gamma Prentice",params=c(mu=input$fp_gg_mu+log(f),sigma=input$fp_gg_sigma,Q=input$fp_gg_q)),loghaz_spline=list(id=id,label="自然样条log风险+恒定尾部",params=c(input$fp_spline_intercept-log(f),parse_unit_numbers(input$fp_spline_slopes)),knots=cfg$knots,tail=cfg$tail,time_scale=cfg$time_scale),rp_hazard=list(id=id,label="Royston-Parmar log累计风险",params=c(input$fp_rp_intercept,input$fp_rp_linear,if(nzchar(trimws(input$fp_rp_coefficients)))parse_unit_numbers(input$fp_rp_coefficients) else numeric()),knots=cfg$knots,tail=cfg$tail,lower=cfg$rp_lower,time_scale=cfg$time_scale),ispline_hazard={weights<-parse_unit_numbers(input$fp_ispline_weights);if(any(!is.finite(weights)|weights<=0)||!is.finite(input$fp_ispline_tail_rate)||input$fp_ispline_tail_rate<=0)stop("I-spline线性风险率和基函数系数须正。");list(id=id,label="正系数I-spline累计风险+正线性尾",params=c(log(input$fp_ispline_tail_rate/f),log(weights)),knots=cfg$knots,tail=cfg$tail,time_scale=cfg$time_scale)});cfg$uncertainty<-"plugin"
  }else{if(is.null(input$fp_file))stop("请提供单终点资料CSV。");raw<-read.csv(input$fp_file$datapath,check.names=FALSE,stringsAsFactors=FALSE);if(!"PARAMCD" %in% names(raw))stop("资料需PARAMCD。");cfg$data<-if(input$fp_source=="adtte")fx_from_adtte(raw,cfg$paramcd,cut,mode!="grouped") else fx_interval_data(raw[!is.na(raw$PARAMCD)&raw$PARAMCD==cfg$paramcd,,drop=FALSE],cut,input$fp_file_unit,mode!="grouped");cfg$combination<-input$fp_combination;cfg$candidates<-if(cfg$combination=="single")input$fp_single else input$fp_candidates;cfg$folds<-input$fp_folds;cfg$uncertainty<-if(purpose=="fit")"plugin" else input$fp_uncertainty}
  cfg$reps<-if(purpose=="fit")1L else input$fp_reps
  if(purpose!="fit"){groups<-if(mode=="grouped"){w<-read.csv(text=input$fp_group_weights,check.names=FALSE,stringsAsFactors=FALSE);if(!identical(names(w),c("group","weight"))||anyNA(w)||anyDuplicated(w$group)||nrow(w)<1||nrow(w)>8||any(!is.finite(w$weight)|w$weight<=0))stop("组权重CSV需group,weight；1–8个唯一组及正权重。");setNames(w$weight,w$group)} else c(Combined=1)
    cfg$group_weights<-groups;cfg$dropout_rates<-setNames(rep(input$fp_dropout_rate/f,length(groups)),names(groups));cfg$new_n<-input$fp_new_n;cfg$enroll_rate<-input$fp_enroll_rate/f;cfg$max_day<-input$fp_max*f;cfg$cut_rule<-purpose;if(purpose=="counts")cfg$horizons<-parse_unit_numbers(input$fp_horizons)*f else cfg$target<-input$fp_target}
  validate_flexible_prediction(cfg);cfg
}
ob_input <- function(input){u<-input$ob_unit %||% "months";f<-time_factor(u);purpose<-input$ob_purpose;cfg<-list(research_family="observation_process",purpose=purpose,mode=if(purpose=="design")"fixed_truth" else "conditional",design_mode="fixed",effect_mode="observed_state_dropout",paramcd="PFS+OS",primary=if(purpose=="design")input$ob_primary else "release",sided="benefit",alpha=.025,display_unit=u,engine_unit="days",origin=as.character(input$ob_origin),reps=input$ob_reps,seed=input$ob_seed,cut_rule="fixed",filter_enabled=FALSE,reference_scenario=1,lag_model=input$ob_lag_model,lag_mean=input$ob_lag_mean*f,lag_shape=input$ob_lag_shape,lag_sd=input$ob_lag_sd,release_period=input$ob_release_period*f)
  if(purpose=="backlog"){if(is.null(input$ob_backlog_file))stop("请选择已知临床事件清单。");d<-read.csv(input$ob_backlog_file$datapath,check.names=FALSE,stringsAsFactors=FALSE);if(!all(c("CLINICAL_DAY","SENT_DAY") %in% names(d)))stop("清单需CLINICAL_DAY和SENT_DAY。");fu<-time_factor(input$ob_file_unit);for(k in c("CLINICAL_DAY","SENT_DAY")){if(all(is.na(d[[k]])))d[[k]]<-as.numeric(d[[k]]);if(!is.numeric(d[[k]]))stop("清单时间列数值，未送出SENT_DAY留空。");d[[k]]<-d[[k]]*fu};cfg$backlog<-d;cfg$cut<-input$ob_cut*f;cfg$horizons<-parse_unit_numbers(input$ob_horizons)*f
  }else{base<-list(js_unit=u,js_origin=input$ob_origin,js_n=10,js_groups="2",js_allocation=input$ob_allocation,js_clock=input$ob_clock,js_drop_control=0,js_drop_treatment=0,js_enroll_mode="constant",js_enroll_rate=input$ob_enroll_rate,js_cut_mode="fixed",js_cuts=as.character(input$ob_max),js_fixed="1",js_q01=input$ob_q01,js_q02=input$ob_q02,js_q12=input$ob_q12,js_reps=1,js_seed=input$ob_seed)
    for(tr in names(joint_transition_names))for(k in c("design_model","exp_input","median","exp_rate","weibull_input","eta","shape","parameter_cuts","parameter_rates"))base[[paste0("js",tr,"_",k)]]<-input[[paste0("ob",tr,"_",k)]]
    cfg$joint_base<-joint_config_input(base);cfg$max_day<-input$ob_max*f;cfg$analysis_feed<-input$ob_analysis_feed;cfg$visit_interval<-input$ob_visit_interval*f;cfg$visit_jitter<-input$ob_visit_jitter*f;cfg$miss_probability<-input$ob_miss_probability;cfg$drop0_rate<-input$ob_drop0/f;cfg$drop1_rate<-input$ob_drop1/f;cfg$reference_ages<-parse_unit_numbers(input$ob_reference_ages)*f;cfg$primary_age<-input$ob_primary_age*f;cfg$scenario_table<-read.csv(text=input$ob_scenario_csv,check.names=FALSE,stringsAsFactors=FALSE)}
  validate_observation(cfg);cfg
}
round_four_units <- function(input,session,pre,specs){previous<-reactiveVal("months");observeEvent(input[[paste0(pre,"unit")]],{to<-input[[paste0(pre,"unit")]] %||% "months";from<-previous();if(to==from)return();r<-time_factor(from)/time_factor(to);for(kind in names(specs))for(id in names(specs[[kind]])){value<-isolate(input[[id]]);if(is.null(value))next;new<-tryCatch(switch(kind,duration=value*r,rate=value/r,log_time=value+log(r),log_rate=value-log(r),duration_text=if(!nzchar(trimws(value)))"" else paste(format(parse_unit_numbers(value)*r,digits=16,trim=TRUE),collapse=",")),error=function(e)value);label<-paste0(specs[[kind]][[id]],"（",if(kind %in% c("rate","log_rate"))"每" else "",time_label(to),"）");freezeReactiveValue(input,id);if(kind=="duration_text")updateTextInput(session,id,label=parameter_label(id,label),value=new) else updateNumericInput(session,id,label=parameter_label(id,label),value=new)};previous(to)},ignoreInit=TRUE)}
register_round_four_server <- function(input,output,session,controller){
  round_four_units(input,session,"fp_",list(duration=c(fp_cut="IA研究时间",fp_age="共同风险年龄",fp_median="中位时间",fp_tail="上边界 / 恒定尾起点",fp_rp_lower="RP下边界年龄",fp_time_scale="样条时间尺度",fp_max="最大研究时间"),rate=c(fp_ispline_tail_rate="I-spline线性基准风险率",fp_rate="指数风险率",fp_enroll_rate="总体入组率",fp_dropout_rate="独立退出风险"),log_time=c(fp_gg_mu="log时间位置mu"),log_rate=c(fp_spline_intercept="log风险截距"),duration_text=c(fp_knots="内部切点",fp_reference_ages="参考风险年龄",fp_horizons="未来研究截点")))
  specs<-list(duration=c(ob_cut="IA研究时间",ob_max="固定研究时间",ob_visit_interval="访视间隔",ob_visit_jitter="访视抖动",ob_lag_mean="送出延迟均值",ob_release_period="发布批次周期",ob_primary_age="主风险年龄"),rate=c(ob_enroll_rate="总体入组率",ob_drop0="未检测进展退出风险",ob_drop1="已检测进展退出风险"),duration_text=c(ob_horizons="未来发布研究时点",ob_reference_ages="参考风险年龄"))
  for(tr in names(joint_transition_names)){specs$duration<-c(specs$duration,setNames(c("潜在时钟中位","Weibull尺度eta"),paste0("ob",tr,"_",c("median","eta"))));specs$rate<-c(specs$rate,setNames("转移风险率",paste0("ob",tr,"_exp_rate")));specs$duration_text<-c(specs$duration_text,setNames("转移切点",paste0("ob",tr,"_parameter_cuts")))}
  # Piecewise rates use their own inverse-duration conversion.
  round_four_units(input,session,"ob_",specs);old_ob_unit<-reactiveVal("months");observeEvent(input$ob_unit,{to<-input$ob_unit %||% "months";from<-old_ob_unit();if(to==from)return();ratio<-time_factor(to)/time_factor(from);for(tr in names(joint_transition_names)){id<-paste0("ob",tr,"_parameter_rates");v<-isolate(input[[id]]);if(!is.null(v))updateTextInput(session,id,label=parameter_label(id,paste0("各段转移风险率（每",time_label(to),"）")),value=paste(format(parse_unit_numbers(v)*ratio,digits=16,trim=TRUE),collapse=","))};old_ob_unit(to)},ignoreInit=TRUE)
  register_parameter_controls(input,output,session,reactive(input$ob_unit %||% "months"),paste0("ob",names(joint_transition_names),"_"),joint_defaults,parameter_input_model)
  old_basis<-reactiveVal("median");observeEvent(input$fp_exp_basis,{to<-input$fp_exp_basis;from<-old_basis();if(to==from)return();if(to=="rate")updateNumericInput(session,"fp_rate",value=log(2)/isolate(input$fp_median)) else updateNumericInput(session,"fp_median",value=log(2)/isolate(input$fp_rate));old_basis(to)},ignoreInit=TRUE)
  fp<-register_research_workbench_server(input,output,session,controller,"fp_","flexible_interval_prediction","flexible_prediction","fp_tabs",function()fp_input(input),fp_sample,fp_report,"run_flexible_prediction",extra=c("count_overview","target_overview","model_overview","model_reference","fold_records"),input_tabs=c("fp_inputs","fp_plan"))
  ob<-register_research_workbench_server(input,output,session,controller,"ob_","observation_process","observation","ob_tabs",function()ob_input(input),ob_sample,ob_report,"run_observation",extra=c("recovery","process_overview","backlog_overview"),input_tabs=c("ob_inputs","ob_plan"))
  observe({if(identical(input$fp_purpose,"fit"))nav_hide("fp_tabs","fp_exports",session=session) else nav_show("fp_tabs","fp_exports",session=session)})
  draw_curve<-function(a){d<-a$model_reference;req(nrow(d));u<-time_factor(a$config$display_unit);groups<-unique(d$group);plot(range(d$age_day/u),c(0,1),type="n",xlab=paste0("风险年龄（",time_label(a$config$display_unit),"）"),ylab="S(t)");for(j in seq_along(groups)){x<-d[d$group==groups[j],];lines(x$age_day/u,x$survival,col=j,lwd=2)};legend("topright",legend=groups,col=seq_along(groups),lty=1,bty="n")}
  output$fp_curve<-renderPlot({a<-fp$result();req(a);draw_curve(a)})
  fitted<-reactiveVal(NULL);fit_error<-reactiveVal(NULL);observeEvent(input$fp_fit_run,{fitted(NULL);fit_error(NULL);tryCatch({cfg<-fp$configuration();if(is.null(cfg)||cfg$purpose!="fit")stop("先选择模型拟合需求或载入相应配置。");a<-fp_fit_only(cfg);a$status<-"fit_only";fitted(a);nav_select("fp_tabs","fp_results",session=session)},error=function(e){fit_error(conditionMessage(e));nav_select("fp_tabs","fp_results",session=session)})},ignoreInit=TRUE)
  output$fp_fit_curve<-renderPlot({a<-fitted();req(a);draw_curve(a)})
  output$fp_fit_note<-renderUI(tagList(if(!is.null(fit_error()))p(class="field-note",fit_error()),if(!is.null(fitted()))p(class="field-note","冻结模型参考；指定的盲态HR不由资料估计。开发稿待复核。")))
  for(pair in list(c("fp_fit_models","model_overview"),c("fp_fit_reference","model_reference"),c("fp_fit_folds","fold_records")))local({out<-pair[1];key<-pair[2];output[[out]]<-renderDT({a<-fitted();req(a);d<-a[[key]];for(k in names(d)[grepl("_day$",names(d))]){d[[k]]<-d[[k]]/time_factor(a$config$display_unit);names(d)[names(d)==k]<-paste0(k,"（",time_label(a$config$display_unit),"）")};if("hazard_per_day" %in% names(d)){d$hazard_per_day<-d$hazard_per_day*time_factor(a$config$display_unit);names(d)[names(d)=="hazard_per_day"]<-paste0("风险率/",time_label(a$config$display_unit))};study_table(d)})})
  output$fp_fit_config_download<-downloadHandler(filename="flexible_fit_config.json",content=function(file){a<-fitted();req(a);jsonlite::write_json(batch_config_document(a$config),file,auto_unbox=TRUE,pretty=TRUE,digits=NA)})
  output$fp_fit_result_download<-downloadHandler(filename="flexible_fit_result.rds",content=function(file){a<-fitted();req(a);saveRDS(a,file,version=3)})
  output$fp_fit_report_download<-downloadHandler(filename="flexible_fit_report.md",content=function(file){a<-fitted();req(a);writeLines(fp_report(a),file,useBytes=TRUE)})
  output$fp_fit_script_download<-downloadHandler(filename="flexible_fit_replay.R",content=function(file){a<-fitted();req(a);dump<-paste(capture.output(dput(a$config,control=c("keepNA","keepInteger","niceNames","showAttributes","hexNumeric"))),collapse="\n");writeLines(c('source("R/research_sources.R")',paste0("cfg <- ",dump),paste0('if(batch_version!="',a$version,'" || batch_source_hash()!="',a$source_hash,'")stop("Source/version differs")'),paste0("expected_dependencies <- ",paste(capture.output(dput(a$dependencies)),collapse="\n")),'if(!identical(batch_dependencies(cfg),expected_dependencies))stop("Dependencies differ")','result <- fp_fit_only(cfg)','saveRDS(result,"flexible_fit_replayed.rds")','write.csv(result$model_overview,"flexible_models_replayed.csv",row.names=FALSE)','write.csv(result$model_reference,"flexible_reference_replayed.csv",row.names=FALSE)'),file,useBytes=TRUE)})
  output$fp_template<-downloadHandler(filename="interval_snapshot.csv",content=function(file)write.csv(data.frame(USUBJID=c("C01","C02","T01","T02"),PARAMCD="PFS",ENTRY=c(0,0,1,1),L=c(3,6,0,3),R=c(5,NA,2,3),TYPE=c("interval","right","left","exact"),EXIT=c("event","active","event","event"),TRTP=c("Control","Control","Treatment","Treatment")),file,row.names=FALSE))
  output$ob_backlog_template<-downloadHandler(filename="known_backlog.csv",content=function(file)write.csv(data.frame(USUBJID=c("P01","P02"),PARAMCD="PFS",CLINICAL_DAY=c(4,5.5),STATE=c("reported","unsent"),SENT_DAY=c(4.5,NA)),file,row.names=FALSE))
  output$ob_ledger_download<-downloadHandler(filename="selected_visible_ledger_days.csv",content=function(file)write.csv(ob$sample()$ledger,file,row.names=FALSE))
  output$ob_clinical_download<-downloadHandler(filename="selected_clinical_visible_ledger_days.csv",content=function(file)write.csv(ob$sample()$clinical_ledger,file,row.names=FALSE))
  output$ob_central_download<-downloadHandler(filename="selected_central_intervals_days.csv",content=function(file)write.csv(ob$sample()$central_intervals,file,row.names=FALSE))
  output$ob_availability_truth_download<-downloadHandler(filename="selected_report_process_truth_days.csv",content=function(file)write.csv(ob$sample()$availability_truth,file,row.names=FALSE))
  output$ob_adtte_download<-downloadHandler(filename="selected_interval_adtte.csv",content=function(file){a<-ob$sample();r<-ob$result();req(r);if(r$config$purpose!="design")stop("已知积压是报告清单，不是生存ADTTE。");write.csv(ob_interval_adtte(a$observed,r$config),file,row.names=FALSE)})
  output$fp_adtte_download<-downloadHandler(filename="selected_predictive_adtte.csv",content=function(file){a<-fp$sample();o<-a$observed;d<-simulation_adtte(o,a$study_config);d$ENGINE_ENTRY_DAY<-o$entry_day;d$ENGINE_OBS_DAY<-o$obs_day;d$ENGINE_TIME_DAY<-o$time_day;write.csv(d,file,row.names=FALSE)})
  invisible(list(flexible=fp,observation=ob))
}
