register_study_help <- function() {
  h<-c(st_goal="功效评价给定HR；Ⅰ类错误固定两组分布相同；候选网格可组合N、效应情景和截点。建议先20–100轮核对配置，再确定正式重复数。",
    st_unit="默认月；1月=30.4375日。切换同步换算时间、风险率和入组率，概率与HR不变。",
    st_origin="研究时间0对应日期，用于样例ADTTE导出。例如计划首例入组日期。",st_endpoint="每次模拟一个终点PFS或OS；按方案选择，不生成两个相关终点。",
    st_n="两组计划总人数N，10–5000整数。例如300。仅截点前已入组者进入分析。",st_n_grid="逗号分隔、不重复的N整数候选值，10–5000。例如200,300,400。固定日程使用前N个时间。",
    st_hr="Treatment相对Control的恒定HR，0.01–100；HR<1表示获益。给定S_T(t)=S_C(t)^HR；例如0.75。",
    st_hr_grid="不重复的正HR候选值，例如0.7,0.8。HR=1标记H0；单侧获益检验中HR>1不是获益备择。",
    st_h0="另外模拟两组分布相同的零假设情景，估计Ⅰ类错误。与备择情景的试验使用独立随机数。",
    st_allocation="每个患者简单随机分配到Treatment的概率p，0.01–0.99；默认0.5表示1:1，实际人数随机。",
    st_enroll_mode="恒定/分段Poisson入组，或固定日程；达到N后停止。建议先根据预计研究招募过程选择。",
    st_enroll_rate="总体Poisson入组强度，人/所选单位，需为正。例如15人/月，实际每月人数随机。",
    st_enroll_cuts="自研究起点起的正递增入组切点，例如3,6月。数量比入组率少1。",
    st_enroll_rates="各段非负入组强度，人/所选单位，例如9,18,12；零尾段可能使入组无法完成。",
    st_schedule="最大候选N个非负、非递减研究时间，逗号分隔，可同日入组。例：N=10时可填10个0。",
    st_cut_mode="固定DCO为研究起点至截点时间；事件目标为首次可观察事件累计达到D*的时间。两者选其一。",
    st_dco="固定研究DCO，正时间，换算后不超过3650日。例如36月。",st_dco_grid="不重复的正DCO候选时间，例如24,36,48月。相同N/HR的截点共享患者轨迹。",
    st_target="目标事件数D*，正整数。例如180；目标超过可观察事件数时保留未达标状态。",
    st_target_grid="不重复的正D*整数候选值，例如120,180,240。相同N/HR的事件目标共享患者轨迹。",
    st_max="未达到事件目标时的最大研究时间，换算后最多3650日。例如48月。",
    st_miss="预先规定未达D*的决策：窗口末照常检验，或记为不拒绝H0。不要剔除未达标轮次。",
    st_primary="主检验选标准/加权log-rank、Cox Wald、RMST差值或固定时点生存率差。后两者需要预设tau，加权检验需要预设FH权重。",
    st_sided="双侧比较任意方向；单侧Treatment获益在log-rank/Cox用负Z，在RMST/生存率差用正差值。加权检验方向不等同于所有时点均获益，按方案预设。",
    st_alpha="主检验名义显著性水平，0.0001–0.2。常用双侧0.05或单侧0.025；切换方向不会自动改变alpha。",
    st_estimate="附加Cox估计，仅保留有限且收敛的轮次。PH提供log HR偏倚/RMSE及95%覆盖；NPH只描述拟合HR分布，不指定单个恒定HR真值。",
    st_precision="直接给重复数B，或用最坏Bernoulli方差0.25预先计算B=ceil(0.25/epsilon²)。不按中途结果停止。",
    st_reps="每情景20–10000个独立重复试验。例如1000；p≈0.8时MCSE≈0.0126。正式精度应按研究目的确定。",
    st_epsilon="预定最坏情形MCSE上界epsilon，0.005–0.1。例如0.01对应B=2500；仅适用于所有计划轮次决策有效。",
    st_power="解析参照的目标功效，例如0.8；只用于近似所需事件数，不改变模拟检验的alpha或拒绝规则。",
    st_seed="0至2147483647整数；保存配置、版本和依赖可复现。各N/效应情景独立，多个截点配对。",
    st_view_scenario="选择已完成至少一轮的情景，用于查看KM及导出对应观察数据。",
    st_view_rep="选择已成功生成的重复轮次。样例按保存种子重新生成，不读取未观察时间作分析。")
  h<-c(h,st_inf_look="选择当前情景与重复轮次中已完成且有效的分析。建议先查看最后一次已执行分析；选择较早次序时只读取截至该次的记录，不使用后续Z、未来HR或未观察的患者真值。",st_design_mode="选择一次固定分析或多次组序贯。组序贯目前使用PH标准log-rank，按预设事件目标逐次决策；拒绝率按完整试验计数。",st_gs_timing="含最终分析的2–5个递增计划信息比例，首个至少0.1、末值为1。例0.5,1；事件目标向上取整后，按实际目标比例生成边界。",st_gs_spending="预设OBF型或Pocock型Lan–DeMets alpha消耗。计算整个路径的累计跨界概率，不把每次分析都与同一个alpha比较。",st_gs_futility="单侧选择不设、手工非约束性Z，或约束性beta消耗。非约束性Z不参与效力界校准；约束性beta联合生成效力/无效界，运行时必须执行。beta分支本轮待复核。",st_gs_futility_z="每个期中分析一个非约束性无效Z界值，共K−1个，范围−5至5且低于效力界。正Z表示获益；如两次分析可填0。",
    st_gs_beta_input="选择输入设计beta或目标功效，两者满足power=1−beta，切换自动换算，只读取当前所选字段。常用目标功效0.8对应beta0.2；与Monte Carlo重复数精度分别设置。",
    st_gs_beta="设计备择下累计不拒绝概率beta，0.01–0.5。常用0.2；用于联合生成beta无效界，不是每次分析单独允许的错误率。",
    st_gs_power="设计目标功效1−beta，0.5–0.99。常用0.8或0.9；对应完整原停止规则和表中隐含设计HR，不能直接当作任意实际模拟HR的功效。",
    st_gs_beta_spending="预设OBF型、Pocock型或HSD型累计beta消耗。仅约束性beta模式使用；与alpha消耗函数分别选择，不按本轮结果改变。",
    st_gs_beta_gamma="HSD型beta消耗的形状参数gamma，−10至5。可从−4开始；gamma=0为线性消耗，负值使早期累计消耗较少，正值使早期较多。",
    st_gs_design_hr="事件数参照所用设计备择HR，Treatment/Control，在0.01至小于1之间，例如0.7。与真实模拟HR和假设未来HR分别保存；不会自动替换最终D*。",st_cp_look="选择该轮已经实际完成的分析。条件功效只读取该次Z和事前计划；若当时已经停止则直接显示已决策状态，不读取未来轨迹。",st_cp_hr="条件功效假设的未来恒定HR，Treatment/Control，0.01–100。例0.7；HR=1表示以后无差异，与真实生成HR和已观察效应分别设置。",st_cp_futility="继续路径是否执行预设无效停止。执行对应模拟方案；忽略用于比较非约束规则下的效力跨界概率，不改变已保存试验结果。",st_effect="效应定义在个体入组后的随访时间上：恒定PH、延迟获益、前后HR交叉或任意分段。先按生成假设选择，不把研究DCO当作HR切点。",
    st_delay="Treatment从无差异HR=1转为获益的个体随访时间，需正数。例如6月；每位患者按自己的随访年龄改变风险。",
    st_late_hr="延迟后Treatment/Control的HR，0.01至小于1。例如0.65；延迟之前固定为1，作用于总体事件风险。",
    st_change="前后HR改变的个体随访时间，需正数。例如6月；HR在1两侧表示风险方向交叉，生存曲线不一定同时交叉。",
    st_early_hr="改变时点之前的Treatment/Control HR，0.01–100。例如1.3表示早期风险较高；前后HR必须处于1两侧。",
    st_cross_hr="改变时点之后的Treatment/Control HR，0.01–100。例如0.65表示后期风险降低；切点按个体随访时间定义。",
    st_hr_cuts="0–20个正递增个体随访HR切点，逗号分隔。例如3,9月对应三个HR段；与入组切点和Control分布风险切点分别设置。",
    st_hr_profile="各段真实HR，数量=HR切点数+1，0.01–100。例如1,0.8,0.6；最后一段延续至无限随访时间。",
    st_tau="事前固定的个体随访时间tau，需为正。RMST积分从0到tau，固定时点比较S(tau)。例如12月；超过任一组观察支持且KM未降至0时该轮无效。",
    st_weight_preset="预先选择FH(rho,gamma)权重：00标准、10偏早期、01偏后期、11偏中间，也可自定义。使用合并KM的事件前生存率，不能看到结果后选最小p。",
    st_fh_rho="FH权重S(t−)^rho × [1−S(t−)]^gamma的rho，0–5。例如rho=1、gamma=0偏重早期；必须在运行前指定。",
    st_fh_gamma="FH权重中的gamma，0–5。例如rho=0、gamma=1偏重后期；这是一个预设检验，不是MaxCombo或多重检验校正。")
  guidance<-c(st_origin="各日程时间均以此日期为零点，事件分析仍采用连续经过时间。",st_endpoint="终点标签写入导出PARAMCD；HR与脱落假设应与所选终点一致。",st_n="N表示计划入组上限，不保证截点前完成入组。",st_h0="保留H0可同时检查该分析规则是否接近名义alpha。",st_enroll_cuts="切点使用研究日历时间，不能代入个体风险切点。",st_enroll_rates="切点有2个时应给出3个率；尾段0需核对未入组比例。",st_dco="这是从研究起点开始的时间，不是每位患者的随访时间。",st_target="两组事件合计计数，考虑脱落后的可观察事件而非潜在事件。",st_max="所有未达标轮次保留该窗口末分析或预定不拒绝决策。",st_miss="按方案选择并在运行前固定，改变该规则会改变设计拒绝率。",st_view_scenario="情景号对应提交时的矩阵；建议先查看基准N/HR情景。",st_view_rep="轮次与种子记录在每轮结果中，选择不会重启整批模拟。")
  for(id in names(guidance))h[id]<-paste0(h[id],guidance[id])
  parameter_help<<-c(parameter_help,h)
  for(pre in c("p_","pc_","pt_")) {
    ids<-c(names(group_input_defaults()),"survival_time","survival_prob","pwe_input","pwe_survivals","pwe_last_rate")
    for(id in ids) { value<-parameter_help[paste0("s1_",id)]; if(is.na(value))value<-parameter_help[id]; if(!is.na(value))parameter_help[[paste0(pre,id)]]<<-unname(value) }
  }
}
study_ui <- function() nav_panel("重复试验与设计评价",value="study",
  div(class="page-title",h2("重复试验与设计评价"),div(class="study-actions",actionButton("st_run","运行模拟研究",class="btn-primary"),actionButton("st_cancel","取消运行",disabled=TRUE))),
  p(class="field-note","设计阶段 · 两组PH或NPH情景。对照组分布与HR(t)确定事件真值，检验使用截点观察记录。"),
  uiOutput("st_status"),
  navset_card_tab(id="st_tabs",
    nav_panel("需求与设计",value="st_design",
      section("评价需求",selectInput("st_design_mode","分析设计",c("一次固定分析"="fixed","组序贯（PH / log-rank）"="sequential")),selectInput("st_goal","本次评价",c("功效与零假设核对"="power","Ⅰ类错误"="type1","候选设计网格"="grid")),
        fields(selectInput("st_unit","时间单位",c("日"="days","周"="weeks","月"="months"),"months"),dateInput("st_origin","研究起点日期","2025-01-01")),
        fields(selectInput("st_endpoint","终点",c("PFS","OS")),numericInput("st_allocation","Treatment分配概率 p",.5,min=.01,max=.99,step=.05)),
        conditionalPanel("input.st_goal !== 'grid'",numericInput("st_n","计划总人数 N",300,min=10,max=5000,step=10)),
        conditionalPanel("input.st_goal === 'grid'",textInput("st_n_grid","N候选值","200,300")),
        conditionalPanel("input.st_goal !== 'type1' && input.st_design_mode !== 'sequential'",selectInput("st_effect","真实效应形式",c("恒定HR（PH）"="ph","延迟获益"="delayed","交叉风险"="crossing","任意分段HR"="piecewise")),
          conditionalPanel("input.st_effect === 'delayed'",fields(numericInput("st_delay","获益开始随访时间（月）",6,min=.001),numericInput("st_late_hr","延迟后真实HR",.65,min=.01,max=.9999))),
          conditionalPanel("input.st_effect === 'crossing'",numericInput("st_change","HR改变随访时间（月）",6,min=.001),fields(numericInput("st_early_hr","改变前HR",1.3,min=.01,max=100),numericInput("st_cross_hr","改变后HR",.65,min=.01,max=100))),
          conditionalPanel("input.st_effect === 'piecewise'",fields(textInput("st_hr_cuts","HR改变随访切点（月）","3,9"),textInput("st_hr_profile","各段真实HR","1,0.8,0.6")))),
        conditionalPanel("input.st_goal === 'power' && (input.st_effect === 'ph' || input.st_design_mode === 'sequential')",numericInput("st_hr","真实HR（Treatment / Control）",.7,min=.01,max=100,step=.05)),
        conditionalPanel("input.st_goal === 'grid' && (input.st_effect === 'ph' || input.st_design_mode === 'sequential')",textInput("st_hr_grid","真实HR候选值","0.7,0.8")),
        conditionalPanel("input.st_goal !== 'type1'",checkboxInput("st_h0","加入两组分布相同的H0情景",TRUE))),
      section("分析截点",conditionalPanel("input.st_design_mode !== 'sequential'",selectInput("st_cut_mode","截点规则",c("固定研究DCO"="fixed","达到目标事件数 D*"="target"),"target")),
        conditionalPanel("input.st_design_mode !== 'sequential' && input.st_cut_mode === 'fixed' && input.st_goal !== 'grid'",numericInput("st_dco","研究DCO（月）",36,min=.001)),
        conditionalPanel("input.st_design_mode !== 'sequential' && input.st_cut_mode === 'fixed' && input.st_goal === 'grid'",textInput("st_dco_grid","DCO候选值（月）","24,36")),
        conditionalPanel("input.st_cut_mode === 'target' || input.st_design_mode === 'sequential'",
          conditionalPanel("input.st_goal !== 'grid'",numericInput("st_target","目标事件数 D*",180,min=1,step=1)),
          conditionalPanel("input.st_goal === 'grid'",textInput("st_target_grid","D*候选值","120,180")),
          numericInput("st_max","最大研究窗口（月）",48,min=.001),
          conditionalPanel("input.st_design_mode !== 'sequential'",selectInput("st_miss","窗口末未达D*时的决策",c("窗口末照常检验"="analyze","记为不拒绝H0"="no_reject"))))),
      conditionalPanel("input.st_design_mode === 'sequential'",section("预设分析次数与边界",textInput("st_gs_timing","计划信息比例（含最终分析）","0.5,1"),selectInput("st_gs_spending","alpha消耗函数",c("OBF型 Lan–DeMets"="asOF","Pocock型 Lan–DeMets"="asP")),conditionalPanel("input.st_sided === 'benefit'",selectInput("st_gs_futility","无效停止",c("不设"="none","手工非约束性Z边界"="z","约束性beta消耗"="beta")),conditionalPanel("input.st_gs_futility === 'z'",textInput("st_gs_futility_z","期中无效性Z界值","0")),
        conditionalPanel("input.st_gs_futility === 'beta'",
          selectInput("st_gs_beta_input","设计beta / 目标功效输入",c("目标功效"="power","设计beta"="beta"),"power"),
          conditionalPanel("input.st_gs_beta_input === 'power'",numericInput("st_gs_power","设计目标功效 1−beta",.8,min=.5,max=.99,step=.05)),
          conditionalPanel("input.st_gs_beta_input === 'beta'",numericInput("st_gs_beta","设计beta",.2,min=.01,max=.5,step=.05)),
          uiOutput("st_gs_beta_conversion"),
          selectInput("st_gs_beta_spending","beta消耗函数",c("OBF型"="bsOF","Pocock型"="bsP","HSD型"="bsHSD"),"bsOF"),
          conditionalPanel("input.st_gs_beta_spending === 'bsHSD'",numericInput("st_gs_beta_gamma","HSD beta形状 gamma",-4,min=-10,max=5,step=.5)),
          numericInput("st_gs_design_hr","事件数参照设计HR（Treatment / Control）",.7,min=.01,max=.999999,step=.05),
          p(class="field-note","所填最终D*保留。所需事件数和隐含设计HR在下表显示；新增beta分支待复核。")))),uiOutput("st_gs_plan_note"),DTOutput("st_gs_plan",fill=FALSE),conditionalPanel("input.st_sided === 'benefit' && input.st_gs_futility === 'beta'",section("设计事件数参照",DTOutput("st_gs_beta_reference",fill=FALSE),downloadButton("st_gs_beta_plan_download","当前beta计划 CSV"))),plotlyOutput("st_gs_boundary_plot",height="300px"))),
      section("待运行设计矩阵",p(class="field-note","矩阵跟随当前参数更新；结果页对应已提交运行的配置快照。"),div(class="field-note",textOutput("st_matrix_note")),DTOutput("st_matrix",fill=FALSE),plotlyOutput("st_truth_plot",height="340px"),conditionalPanel("input.st_goal !== 'type1' && input.st_design_mode !== 'sequential' && input.st_effect !== 'ph'",plotlyOutput("st_hr_plot",height="240px")))),
    nav_panel("生成分布与过程",value="st_generation",
      section("Control事件时间分布",event_parameter_fields("p_",d=simulation_defaults(),simulation=TRUE),
        p(class="field-note","Treatment使用H_T(t)=∫HR(u)dH_C(u)。HR切点基于个体随访时间；混合或治愈分布按总体风险转换。")),
      section("总体入组",selectInput("st_enroll_mode","入组方式",c("恒定Poisson"="constant","分段Poisson"="piecewise","固定日程"="schedule")),
        conditionalPanel("input.st_enroll_mode === 'constant'",numericInput("st_enroll_rate","总体入组率（人/月）",15,min=.000001)),
        conditionalPanel("input.st_enroll_mode === 'piecewise'",fields(textInput("st_enroll_cuts","入组切点（研究月数）","3,6"),textInput("st_enroll_rates","分段入组率（人/月）","9,18,12"))),
        conditionalPanel("input.st_enroll_mode === 'schedule'",textInput("st_schedule","最大N个入组时间（月）",""))),
      fields(section("Control独立脱落",dropout_parameter_fields("pc_",d=simulation_defaults())),section("Treatment独立脱落",dropout_parameter_fields("pt_",d=simulation_defaults())))),
    nav_panel("分析与运行",value="st_analysis",
      section("预设分析",conditionalPanel("input.st_design_mode === 'sequential'",p(class="field-note","主检验：PH标准log-rank。正Z表示Treatment获益；双侧可在两方向跨越效力边界。")),fields(conditionalPanel("input.st_design_mode !== 'sequential'",selectInput("st_primary","主检验",c("标准log-rank"="logrank","FH加权log-rank"="fh","Cox Wald"="cox","RMST差值"="rmst","固定时点生存率差"="survival"))),selectInput("st_sided","检验方向",c("双侧"="two","单侧Treatment获益"="benefit"))),
        conditionalPanel("input.st_design_mode !== 'sequential' && input.st_primary === 'fh'",selectInput("st_weight_preset","FH预设权重",c("FH(0,0) 标准"="00","FH(1,0) 早期"="10","FH(0,1) 后期"="01","FH(1,1) 中间"="11","自定义"="custom"),"01"),
          conditionalPanel("input.st_weight_preset === 'custom'",fields(numericInput("st_fh_rho","FH rho",0,min=0,max=5),numericInput("st_fh_gamma","FH gamma",1,min=0,max=5)))),
        conditionalPanel("input.st_design_mode !== 'sequential' && ['rmst','survival'].includes(input.st_primary)",numericInput("st_tau","预设个体随访tau（月）",12,min=.001)),
        numericInput("st_alpha","名义alpha",.05,min=.0001,max=.2,step=.005),
        conditionalPanel("input.st_design_mode !== 'sequential' && input.st_primary !== 'cox'",checkboxInput("st_estimate","附加Cox估计（PH下恢复与覆盖）",TRUE)),
        conditionalPanel("input.st_design_mode !== 'sequential' && input.st_goal !== 'type1' && input.st_effect === 'ph' && ['logrank','cox'].includes(input.st_primary)",numericInput("st_power","解析参照目标功效",.8,min=.5,max=.99,step=.05))),
      section("重复数与精度",selectInput("st_precision","重复数设定",c("直接输入B"="fixed","按预定最坏MCSE计算B"="mcse")),
        conditionalPanel("input.st_precision === 'fixed'",numericInput("st_reps","每情景重复数 B",500,min=20,max=10000,step=100)),
        conditionalPanel("input.st_precision === 'mcse'",numericInput("st_epsilon","预定最坏MCSE epsilon",.01,min=.005,max=.1,step=.001)),
        numericInput("st_seed","随机种子",20261004,min=0,step=1),uiOutput("st_precision_note"))),
    nav_panel("评价结果",value="st_results",uiOutput("st_result_note"),
      section("拒绝率与模拟误差",plotlyOutput("st_probability_plot",height="330px"),DTOutput("st_probabilities",fill=FALSE)),
      conditionalPanel("output.st_is_sequential === 'yes'",section("组序贯停止与资源",DTOutput("st_gs_stopping",fill=FALSE),p(class="field-note","停止概率按已完成试验为分母。达到最终D*只表示实际走到最终目标，早期效力或无效停止单列。"))),
      section("截点与分析状态",DTOutput("st_diagnostics",fill=FALSE),tags$details(tags$summary("失败与无效分析原因"),DTOutput("st_failure_reasons",fill=FALSE))),
      conditionalPanel("output.st_has_cox === 'yes'",section("Cox估计 · 有效估计条件下",uiOutput("st_cox_note"),DTOutput("st_recovery",fill=FALSE))),
      conditionalPanel("output.st_contrast_on === 'yes'",section("预设差值的估计与覆盖",uiOutput("st_contrast_note"),DTOutput("st_contrasts",fill=FALSE))),
      conditionalPanel("output.st_has_pairs === 'yes'",section("同一N/效应情景的截点配对比较",p(class="field-note","差值为情景B减情景A；仅在两种决策均有效的配对轮次中计算。"),DTOutput("st_pairs",fill=FALSE))),
      conditionalPanel("output.st_show_reference === 'yes'",section("PH解析近似参照",p(class="field-note","以平均事件数代入D×p×(1−p)；不用于代替模拟结果，分组风险集变化或大量脱落时信息量近似可能偏离。"),DTOutput("st_reference",fill=FALSE)))),
    nav_panel("样例观察数据",value="st_sample",fields(selectInput("st_view_scenario","情景",character()),selectInput("st_view_rep","重复轮次",character())),
      conditionalPanel("output.st_is_sequential === 'yes'",section("选定试验逐次记录",DTOutput("st_gs_path",fill=FALSE))),plotlyOutput("st_km",height="360px"),DTOutput("st_sample_data",fill=FALSE),uiOutput("st_sample_note"),
      div(class="export-bar",downloadButton("st_observed_download","连续时间观察数据 CSV"),downloadButton("st_adtte_download","ADTTE CSV"))),
    nav_panel("期中条件功效",value="st_cp",p(class="field-note","条件功效使用所选模拟试验已完成分析的Z、原计划边界和指定未来HR；采用PH/log-rank的canonical正态近似。"),fields(selectInput("st_cp_look","已完成分析",character()),numericInput("st_cp_hr","假设未来HR（Treatment / Control）",.7,min=.01,max=100,step=.05)),conditionalPanel("output.st_gs_has_futility === 'yes'",selectInput("st_cp_futility","未来无效停止规则",c("执行预设规则"="respect","忽略非约束性规则"="ignore"))),conditionalPanel("output.st_gs_binding === 'yes'",p(class="field-note","约束性beta无效边界固定执行，不提供忽略该规则的CP选项。")),uiOutput("st_cp_note"),DTOutput("st_cp_result",fill=FALSE),downloadButton("st_cp_download","条件功效记录 CSV")),
    nav_panel("组序贯推断",value="st_inference",
      p(class="field-note","使用“样例观察数据”中所选情景与重复轮次的原设计和已完成分析记录。HR=Treatment / Control；采用PH/log-rank事件信息近似。"),
      selectInput("st_inf_look","推断截至已完成分析",character()),uiOutput("st_inf_note"),
      section("观察效应与重复推断",uiOutput("st_inf_repeated_note"),DTOutput("st_inf_repeated",fill=FALSE),downloadButton("st_inf_repeated_download","观察与重复推断 CSV")),
      section("停止后的阶段排序推断",p(class="field-note","支持单侧获益设计，以及不设无效停止的双侧设计。单侧无效规则须按原计划执行。双侧p为两倍较小方向尾概率；调整推断保留观察Z的方向，不改写原试验决策。"),uiOutput("st_inf_final_note"),DTOutput("st_inf_final",fill=FALSE),downloadButton("st_inf_final_download","阶段排序记录 CSV")),
      section("推断记录与复现",downloadButton("st_inf_config_download","观察路径与原设计 JSON"),downloadButton("st_inf_script_download","推断复现 R 脚本"))),
    nav_panel("导出与记录",value="st_exports",p(class="field-note","导出对应本次已提交运行；取消时保存已完成轮次及未完成标记。CSV时间量（含RMST差值及恢复指标）统一为日，生存率差为概率；显示单位另记在配置。真值单独导出，含未观察的事件/脱落时间，检验不读取真值。"),
      div(class="export-bar",downloadButton("st_summary_download","情景汇总 CSV"),downloadButton("st_trials_download","每轮检验 CSV"),downloadButton("st_failures_download","失败记录 CSV"),conditionalPanel("output.st_has_pairs === 'yes'",downloadButton("st_pairs_download","配对比较 CSV")),conditionalPanel("output.st_contrast_on === 'yes'",downloadButton("st_contrasts_download","差值恢复 CSV")),conditionalPanel("output.st_is_sequential === 'yes'",downloadButton("st_looks_download","逐次分析 CSV"),downloadButton("st_stopping_download","停止汇总 CSV")),downloadButton("st_truth_download","选定轮次真值 CSV"),downloadButton("st_config_download","配置 JSON"),downloadButton("st_script_download","复现 R 脚本"),downloadButton("st_report_download","研究报告 Markdown"))))
)
